### ISSUE TITLE
Error: /proc must be mounted

### ISSUE THREAD

**Issue by raducostea** [Microsoft/BashOnWindows#105]
```
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"

```

The /proc is already mounted

```
root@localhost:~# mount
rootfs on / type rootfs (ro,relatime)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600)
proc on /proc type proc (rw,relatime)
sysfs on /sys type sysfs (rw,seclabel,relatime)
root@localhost:~#
```

**Comment by tycho** [comment]
What app was complaining? It probably looks for something specific that it's expecting in /proc and doesn't find it.

**Comment by raducostea** [comment]
Can't remember, but uptime or w also triggers that.

**Comment by benhillis** [comment]
This has been fixed internally and will be making its way to the insider fast ring.

**Comment by benhillis** [comment]
@tyco I remember seeing this block java install through apt-get.

**Comment by benhillis** [comment]
I've verified this is fixed in build 14352, please reopen if you continue to see this issue. Thanks!

**Comment by ashtonsix** [comment]
@benhillis I'm seeing this after upgrading to Ubuntu 16 & running `ps` with build 14352

**Comment by brunosaboia** [comment]
same as @ashtonsix here, I upgrade to Ubuntu 16 and I am seeing this after trying to run a simple source on a script file (trying to install ruby's rvm)

**Comment by aseering** [comment]
@ashtonsix -- build 14352 has a *very* old version of WSL.  Ubuntu 16.04 was not yet supported at that time.  (WSL was only 36 builds old at that point, as it was released in build 14316.  It's now 730 builds old as of the current Fast Ring release, 15046.  It has been under continuous development since its release.  For reference, the current stable release of Windows is based on build 14393.)  Could you try a more-recent build?

@brunosaboia -- what Windows build are you on?  And would you be willing to try a more-recent [Insider build](http://insider.windows.com)?

For what it's worth, the Ubuntu 16.04 version of this command works fine for me on build 15046.

Tangent -- you're both referring to "Ubuntu 16".  Do you mean Xenial or Yakkety?  "16.04" and "16.10" are actually not version numbers.  They are release dates.  Ubuntu Xenial was released in April (04) 2016; Ubuntu Yakkety was released in October (10) 2016.  And Yakkety is not simply "the next version":  Xenial will continue to receive new service packs for several more years.  Yakkety is an interim release and will be deprecated in a few months.  I assume for that reason, WSL officially supports Xenial (16.04) rather than Yakkety (16.10).

**Comment by brunosaboia** [comment]
@aseering 
**Version**: Microsoft Windows [Version 10.0.14393]

And I would be more than willing to try it :)

**Comment by aseering** [comment]
@brunosaboia -- well, you're more than welcome to try it :-)  Just go to https://insider.windows.com/ and follow the directions to sign up.

Note that, if you decide to install through Windows Update (the easiest way when it works), it can take up to a day or two for new updates to appear after you switch your machine to the Fast Ring or Slow Ring.  (If you want to install right away, you can download official Windows Insider ISOs [from here](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewadvanced) after you have signed up for the program.)

**Comment by brunosaboia** [comment]
@aseering OK, I have registered to it. What I am trying to do is to put either elasticsearch or docker to work inside Windows bash. I will try to make it public if I can, with the relevant steps
