### ISSUE TITLE
Manual override of /etc/resolv.conf for custom DNS setups

### ISSUE THREAD

**Issue by gjonespf** [Microsoft/BashOnWindows#1055]
Using:
Microsoft Windows [Version 10.0.14393]

Currently, /etc/resolv.conf is autogenerated  - which is perfect for most situations.  I'm annoying, however, and run a local DNS server on my dev boxes to allow custom DNS overrides. So for

ipconfig /all

I get several DNS servers, e.g. one public:
8.8.8.8

and one custom loopback
10.99.1.1

These are autogenerated into the resolv.conf:
nameserver 8.8.8.8
nameserver 10.99.1.1
search Home

Problem is, when I try to resolve any custom domain, it'll resolve using the first one and fail. I kinda want to remove the first nameserver, and just use my custom local one which also does caching from public servers:

nameserver 10.99.1.1
search Home

So ultimately I need some way of overriding /etc/resolv.conf autogeneration, or disabling it.

I've tried using resolvconf, expecting this may be used to update the conf:
> sudo resolvconf --disable-updates
> resolvconf: Error: /run/resolvconf/interface either does not exist or is not a directory

Have also looked into modifying:
/etc/network/interfaces.d/eth0.cfg

auto eth0
iface eth0 inet dhcp
dns-search Home
dns-nameservers 10.99.1.1

Have also tried modifying the dhcpclient stuff, no avail.

**Comment by rodrymbo** [comment]
Since `/etc/resolv.conf` is autogenerated by a Windows process (not by Linux), using Linux tools is not going to help much.

About the only way to fix it (until more options become available) is to tell the Windows side to use your custom name resolver, or at least put it first. With a bit of luck the autogenerated `/etc/resolv.conf` might put your custom resolver first then, with the public one second, and it will work as you want. Perhaps someone knows how the autogeneration process chooses which nameservers from which adapters are put first in `/etc/resolv.conf`, if the obvious changes don't work.

Or I suppose you could put a script in .bashrc or something that overwrites the autogenerated resolv.conf with one more to your liking every time you log in, until such time as WSL gives more options.

**Comment by sunilmut** [comment]
@gjonespf Please see #1028 on how WSL currently does DNS and our thoughts around it (and the issue with not keeping DNS entry not in sync between Windows and WSL). In short, and, also as @rodrymbo points out, the way currently to manage your `/etc/resolv.conf` is by updating your Windows DNS entries. Hopefully, we can soon fix the issue that is preventing the WSL DNS entries to stay in sync with the Windows side, on a continuous basis. As a workaround, a fresh bash launch should regenerate the `/etc/resolv.conf`.

**Comment by gjonespf** [comment]
@sunilmut Yeah, for now I've just removed all public DNS from the Windows side and run everything with caching through custom local DNS server/proxy.  It's a little simpler to debug that way.
@rodrymbo cheers for the info, it's a little difficult to know how much WSL uses the Linux/Ubuntu networking model, so thought I'd try.  And yeah, the .bashrc idea also works, tried that before just simplifying DNS resolution on the Windows side.  Will close this as I'd imagine the work around will work for most people.

**Comment by meffect** [comment]
anyone know how this is fixed in the insider builds?

**Comment by rehangit** [comment]
1. In bash/wsl add 8.8.8.8 as first entry in resolv.conf (`sudo nano /etc/resolv.conf`)
2. For dos use [these instructions](https://www.windowscentral.com/how-change-your-pcs-dns-settings-windows-10)
