### ISSUE TITLE
Russian localization has Y / N commands translated to Russian while expecting user input in English

### ISSUE THREAD

**Issue by gudenuff** [Microsoft/BashOnWindows#1061]
* A brief description
Russian localization incorrectly translates Y / N commands to Russian while expecting user input in English.

Tools ask for user input using localized format (Russian), and wait for the input in non-localized format (English)

*For example*:

'Продолжить загрузку: [д / н]:'

*I have corrected the initially wrong observed result*
Used input is accepted either in Russian (then the input is incorrectly displayed) or in English (them you must use 'y' or 'n' as usual).

##Expected results
System commands such as confirmations awaited from used input must be left in English despite the program output. For example, if an utility is awaiting user confirmation in YES / NO format, the utility must output to stdout messages that follow the convention:

<QUERY_LOCALIZED> [Y / N]:

where <QUERY_LOCALIZED> is a query for user input localized for the target language.

*For example:*

'Продолжить загрузку: [y / n]:'

* Actual results (with terminal output if applicable)

Everything including system commands is now localized, so the currently used convention is

[[QUERY_LOCALIZED]] [[LOCALIZED_CONFIRM / LOCALIZED_DECLINE]]:

for example:

'Продолжить загрузку: [д / н]:'

* Your Windows build number

10.0.14393.105

* Steps / commands required to reproduce the error
Run any utility that requests some user confirmation.

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by sunilmut** [comment]
@bitcrazed, @miniksa might be able to provide more information on localization.

**Comment by miniksa** [comment]
"Run any utility" isn't enough data for me to reproduce this. Please provide an exact example of what command you are running and what the output is. Screenshots are also appreciated.

cc: @paulcam206

**Comment by gudenuff** [comment]
Here's the sample output screen:

![image](https://cloud.githubusercontent.com/assets/22033543/18346731/8b22660a-75ca-11e6-872b-45be3bb6b93a.png)

**Comment by wizardist** [comment]
@gudenuff this is an upstream issue with Debian/Ubuntu. It totally depends on translations done by translation teams for respective utilities and packages. It is definitely NOT A BUG for WSL.

To sum up, the translation strings were translated incorrectly. That's it.

**Comment by gudenuff** [comment]
@wizardist Meaning that MSFT has no ties with whoever is localizing Ubuntu builds they host on WSL? So the quality and assurance here is made on Cannonical's side, did I get this right?

In Windows you generally expect to respond using original commands (Y or N), despite the localization:
![image](https://cloud.githubusercontent.com/assets/22033543/18433307/791b968e-78ef-11e6-8048-823ee7071f41.png)
(courtesy of computia.ru)
As you see from the above example, the strings within the chkdsk tool were translated into Russian, however, the tool expects the user to input Y or N.

Okay, I am closing the issue as per Pavel's note.

**Comment by aseering** [comment]
@gudenuff , "Canonical" -- that matches my understanding.

WSL is aiming to provide bug-for-bug compatibility with Linux-Ubuntu.  As a general heuristic, if an application behaves incorrectly on regular Linux-Ubuntu 14.04 and it also behaves incorrectly on WSL, then Canonical must first fix it for Linux-Ubuntu; WSL can then pull in the fix for Windows.

Though, if you're looking for quality and assurance, you may be in for a bit of a rude awakening :-)  WSL aims to provide bug-for-bug compatibility with Ubuntu Linux.  Which means the goal for now is to work as well, or as poorly, as Linux itself.  Linux in general is community-driven; there are distributions that aim to provide commercial support, but in my opinion/experience only a very few of them actually have the staffing and experience to do that in a rigorous way.  Most of them depend on the open-source community for support.
