### ISSUE TITLE
WSL is unkillable without rebooting (permissions/security problems for admins)

### ISSUE THREAD

**Issue by fpqc** [Microsoft/BashOnWindows#1086]
In my previous issue, I gave a way to turn WSL into a zombie process that is unkillable.

I continued testing ways to kill it, and I think it's worth having its own issue

The only way to kill the service is rebooting, once it hangs.  I tried launching a command prompt as NT Authority\System with psexec from the sysinternals tools, and this happened:

![2016-09-15 1](https://cloud.githubusercontent.com/assets/6083371/18568722/8f4da26a-7b6c-11e6-898b-7e4b1be9210a.png)

Not sure how access is being denied to NT Authority\System, which should not have any restrictions in Ring 0, or so I thought.  Maybe this means that it's being locked by the Windows 10 hypervisor (I have hyper-V installed, so maybe it's a hypervisor-level lockout using VSM? The process explorer screenshot below says that it's not using Virtualization, so what is securing it?!)

It's running with such a high level of security that even process explorer running as admin cannot remove its protections:

![accessdenied](https://cloud.githubusercontent.com/assets/6083371/18569167/01e3610a-7b6f-11e6-8ee3-c54f871de57a.png)

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  The service is a "locked down" process since it runs as a protected process (light) so access is limited from other non-protected processes - https://msdn.microsoft.com/en-us/library/windows/desktop/dn313124(v=vs.85).aspx.  The service hang reported in the other issue is a bug we should fix.

**Comment by fpqc** [comment]
@stehufntdev So is there a way for an admin to manually kill this kind of protected process without rebooting (like a protected-mode task killer? I have no idea).

**Comment by therealkenc** [comment]
I just about asked this same question last week when I managed to hose WSL a bunch of times. Unfortunately I don't have a useful repro<sup>1</sup> which is why I didn't bring it up. In my case the process couldn't be killed, and if I closed the shell and tried to open another it would hang with no prompt. Reboot was the only way out. It would be nice to have a `lxrun.exe /nukeinstance`.

<br><sup>1</sup> <sub>run gdb on a huge project with lots of threads and mutexes that call lots of unimplemented surface under memory pressure while reading and writing to files pipes and sockets</sub>

**Comment by fpqc** [comment]
@therealkenc Well luckily I spent an hour and found a pretty minimal configuration on Trusty to get a repro.  Hopefully they will fix both the underlying bug as well as provide the nukeinstance interface (or add a nukeinstance timer to the session manager service on manual stop).

**Comment by dmex** [comment]
@stehufntdev 

Can you please share some information about why lxss even needs to run as a protected process? This would be very useful information since I may need to change the way our kernel-mode 'anti-rootkit' feature (included in Process Hacker) is presently able to terminate the LxssManager service and WSL processes.

@fpqc 

You can do one of two things to terminate the LxssManager service:

1. Open regedit and navigate to the following key:
HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\LxssManager
2. Delete the LaunchProtected value.
3. Reboot.

That will enable full access to the LxssManager service (including termination rights) but you're likely going to open up a security hole by doing so.

Alternatively, Process Hacker is able to terminate 'protected' processes such as WSL:
https://github.com/processhacker2/processhacker2/releases
https://wj32.org/processhacker/

1. Elevate Process Hacker with administrative rights.
2. Right-click the process or service and click Terminate.

**Comment by fpqc** [comment]
@dmex How is process hacker doing that? An exploit?  If process hacker can do this, mustn't it be using a local privilege escalation?  What would stop malware doing the same?

**Comment by dmex** [comment]
@fpqc 

Process Hacker simply calls ZwTerminateProcess from kernel-mode using a kernel driver? That function allows 'protected' processes to be terminated (when called from kernel-mode) and is officially documented and supported by Microsoft - feel free to review our source code, you'll find calls to that function are very well protected :)

The major problem is that anti-virus/malware software is unable to defend against zero-day attacks (or the majority of malicious executables compiled within the last month or so) and vendors usually take up to several weeks (or even months) to create signatures and remove malicious software from your machine - instead Process Hacker allows you to terminate and remove rootkits and malware yourself.

Rootkits and malware can obviously use the same function if they create a kernel driver and obtain an EV certificate to sign it but EVs are expensive and require a lots of legal documentation to be granted (and their expensive certificate is easily revoked).

The serious question is why LXSS needs to run as a protected process... If something executing inside Bash manages to exploit WSL then it would be unkillable by everything except Process Hacker (at minimum for several weeks until the majority of Anti-virus software created signatures and starting blocking the malicious code).

Hopefully @stehufntdev or someone can share some details about why this protection level is needed so I can decide if I need to make changes to Process Hacker to prevent LxssManager from being terminated (if it's just to protect calls to/from lxcore.sys then I can suggest a much better alternative!) .

**Comment by fpqc** [comment]
@dmex Yeah I thought about it a bit more, and it seems like it doesn't matter that much bc in order to call the process hacker kill functionality you already need ring 3 admin, in which case you can probably find some other way to obtain persistence.  The point, I guess, is that unless the driver itself is vulnerable, it probably won't allow arbitrary execution of code in Supervisor mode even from Ring 3 adminland, and I assume that even from Ring 3 adminland you can't disable secure boot without exploiting the firmware, in which case certs will be enforced and unsigned/self signed rootkits can't be installed with only Ring3 admin (unless you find a bug that allows you to jump from admin into the kernel in the first place).

Makes sense, and I guess I trust process hacker to install drivers into kernel mode as much as I trust NVidia, lol.

**Comment by stehufntdev** [comment]
For now, we only want Windows signed code accessing the lxss device driver.  This is accomplished today by marking the lxss device driver ACL as local system Windows PPL, and running the lxssmanager service as local system Windows PPL.

**Comment by fpqc** [comment]
@stehufntdev Is that also enforced at the COM interface on the service?  Is that the reason why I'm getting an immediate crash with @ionescu007 's lxlaunch (because bash.exe is a signed Windows component, it's being allowed to connect to the service, but other binaries may not be able to do so)?  

Or is it just a weird thing that's happening bc of something I screwed up while compiling it??

**Comment by benhillis** [comment]
@fpqc - Non windows signed binaries should be able to connect to LxssManager (just not the driver).  We are still refining the COM interface which is a large part of the reason we have not yet documented it.  I suspect the version of the interface Alex is using is out of date an he should look at the new idl file to see what has changed.

**Comment by fpqc** [comment]
@benhillis He just rewrote the interface 3 days ago, I'm pretty sure it's up-to-date.  It actually does a check to see if the build is >=15000, bizarrely enough (maybe someone over at MS is giving him nightly builds?  No idea).

**Comment by ionescu007** [comment]
The build number check is simply a bug on my end. It was meant to be 14500. The code does not crash for me, so I will have to debug what's wrong with it. The COM interface changed to allow the creation of an unnamed IPC channel with the launcher.

Also, your questions on Protected Processes & etc, and why MS locked down the driver this way (I asked them to) are explained in the BlackHat presentation.

**Comment by ionescu007** [comment]
@benhillis You're shipping an IDL file for Lxss? ;-)

**Comment by benhillis** [comment]
@ionescu007 No, don't you have as source access though? I know you have private symbols :)

**Comment by benhillis** [comment]
Joking aside - we plan on documenting the com interfaces at some point but we want to make sure we don't do that while they are still in flux.

**Comment by ionescu007** [comment]
That's actually really cool. And yes, the proper thing is to update the IID Version when you add a parameter ;-) Understandable not to have done it for the 'beta' I guess.

No source/privates used in my research, sadly (except ole32/combase which are on the symbol server) -- too much of an NDA risk. Public symbols + the intense debug output is enough :)

**Comment by benhillis** [comment]
Turns out kernel developers aren't the best at following COM best practices :)

**Comment by dmex** [comment]
@stehufntdev 

It might be an idea to add a /kill parameter to lxrun or somewhere (as @therealkenc suggested) that sends an ioctl to lxcore and terminates all running pico processes? It should be possible to terminate/recover your session without having to reboot (or use 3rd party software).

@ionescu007 

I know you asked for PPL ;) but I was hoping ntdev might consider some changes that allow non-critical PPL processes (such as LxssManager) to be terminated using Task manager and other software. If Lxss was somehow compromised or become a runaway processes the ability to terminate it would improve both reliability and security?

**Comment by ionescu007** [comment]
The COM interface does have a Stop/Terminate command that sends the IOCTL.
I could add it to my tools :)

Best regards,
Alex Ionescu

**Comment by stehufntdev** [comment]
Stopping the service through scm will end up do the same thing as the COM interface's stop\terminate command.

In the hang caused by zsh, a thread was deadlocked in the kernel (non alterable wait) so it wouldn't have been possible to kill without a restart.  All bugs aside in WSL, stopping the service is the right way to terminate the running instance.

**Comment by dmex** [comment]
@stehufntdev 
"a thread was deadlocked in the kernel so it wouldn't have been possible to kill without a restart"

You can kill/terminate kernel threads using Process Hacker ;) It's obviously very (very) unsafe and likely to cause a BSOD (unless you know what you're doing) but it's a highly valuable and useful feature required to remove rootkits and does let you kill deadlocked threads without restarting (e.g. during testing and development).

@ionescu007 

Thanks! Please add that into the next version 👍

**Comment by gdh1995** [comment]
I could not stop the service `LxssManager`: it also hanged when I wanted to restart it on Taskmgr's service panel, and then `sc stop LxssManager` reported `Error 1061: The service cannot accept control messages at this time`.

Env: Windows 10 ver 1607 (build 14955.1000)

**Comment by flrngel** [comment]
@gdh1995 In my case, I booted as safe mode. I just deleted most recent files from `C:\Users\<My Account>\Local\lxss` which seems to cause deadlock.

**Comment by EmberQuill** [comment]
I somehow managed to freeze the entire WSL by running a mv command in bash. Just renaming a folder which itself contains a single non-critical file. Could not kill the mv process by any means, nor could I kill LxssManager even with the Process Explorer method mentioned above.

**Comment by fpqc** [comment]
@EmberQuill let me guess you're on Windows 10 1607 right?

**Comment by fpqc** [comment]
quietly closing this up @benhillis . Should be marked "bydesign" by merit of it being a kernel driver.

**Comment by jefferai** [comment]
FWIW, I realize the discussion went elsewhere, but going back to the OP on this issue, I just encountered this. Ran a normal session, then hit Ctrl-D to logout. Got "logout" in the terminal, and it hung. Ctrl-C does nothing, attempts to kill it do nothing, and of course it doesn't show up in task manager.

I tried stopping LxssManager, which timed out, and now its status just pegged at "Stopping".

**Comment by fpqc** [comment]
@jefferai This is gonna happen with any deadlock in the driver.  There are instructions in some of the documentation on enabling a system memory dump and manually crashing windows to generate it if you get into a deadlocked state like this.  Memory will be written out to disk, and you can host the dump on onedrive and submit it to secure@microsoft.com attn: Ben Hillis or Sunil Muthuswamy

Or, if you have a reliable repro, you can submit it as a new bug report.  

The problem is that if the driver deadlocks, restarting the service sends an ioctl to the kernel to stop the driver, but the driver is deadlocked so it just sorta hangs.

**Comment by jefferai** [comment]
@fpqc any chance you can point me to those docs? Happy to submit the dump if so.

**Comment by fpqc** [comment]
Yep! https://msdn.microsoft.com/en-us/commandline/wsl/troubleshooting#bash-is-hung

**Comment by MaxPleaner** [comment]
hmm, I seem to be getting this error whenever I run `mv`

**Comment by fpqc** [comment]
@MaxPleaner Update Windows. You are on 1607. The mv bug has been fixed for ages.

**Comment by MaxPleaner** [comment]
@fpqc It seems like I'm all updated though.

![updates](https://user-images.githubusercontent.com/5035719/31361611-f58f1cce-ad08-11e7-9b13-9c56f06f75e3.PNG)

**Comment by benhillis** [comment]
@MaxPleaner - You need to install Windows 10 Creators Update to get this fix.

https://support.microsoft.com/en-us/help/4028685/windows-get-the-windows-10-creators-update

**Comment by MaxPleaner** [comment]
@benhillis i appreciate this help. It says my PC running version 14393, but version 15063 is available. The problem is that it required 8GB of free space, which I don't have. So I'll need to shuffle my partitions a bit first.

**Comment by Biswa96** [comment]
@dmex In this comment https://github.com/Microsoft/WSL/issues/1086#issuecomment-249382267 you've said to delete `LaunchProtected` registry to kill LxssManager service. Deleting the `LaunchProtected` REG_DWORD value shows `Error: 5 Access Denied`. May be the protected mode required as there are some `RequiredPrivileges` values for LxssManager service.

![lxssmanager_access_denied](https://user-images.githubusercontent.com/31443074/37616672-b2724afe-2bd6-11e8-91e3-aeeedc02e710.png)

@benhillis Can you guys just remove that service and do the WSL things like a normal process?

**Comment by benhillis** [comment]
@Biswa96 - The service is an integral part of the current design.

**Comment by Biswa96** [comment]
I mean to say that place those LxssManager.dll and associates as it is now, just don't run it as a service.

**Comment by dmex** [comment]
@Biswa96

That method is no longer applicable with the newer builds of Windows 10 and you'll either need to use Process Hacker to terminate those processes or reboot the machine.

@benhillis 

I've come across a few WSL implementation issues that are related to this. It's probably not a good idea to discuss undocumented internals and other things on a public tracker... Are you able to drop me an email (dmex04 at gmail.com)?

**Comment by Herz3h** [comment]
I have the same problem. WSL stop responding at all. So when I try to restart the LxssManager service I get a 1053 error.

I don't know under what circumstences the Ubuntu 18.04 freezes, but it happened twice randomly during vim editing......
Is there a workaround other than rebooting Windows ?

**Comment by ignorabilis** [comment]
Microsoft Windows [Version 10.0.18362.207]

```
SERVICE_NAME: LxssManager
        TYPE               : 30  WIN32
        STATE              : 3  STOP_PENDING
                                (NOT_STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x2
        WAIT_HINT          : 0xea60
        PID                : 11111
        FLAGS              :
```

I've tried a lot of things but nothing seems to be working. Here's a list of them: 
1. `wslconfig /t Ubuntu (Default)' just hangs
2. Trying to stop `LxssManager` from `Services` shows a loading window, but after some time this message appears:
```
Windows could not stop the LxssManager service on Local Computer.
Error 1053: The service did not respond to the start or control request in a timely fashion
```
Then in `Services` `LxssManager` hangs at `Stopping`.
3. Finding the pid and trying `taskkill /f /pid 11111` returns an error (yes, I'm admin):
```
ERROR: The process with PID 11111 could not be terminated.
Reason: Access is denied.
```
4. Although the same, but for completeness - doing `Stop-Process 11111 -Force` yields ` Access is denied`
5. Using the built-in admin and trying `taskkill` or `Stop-Process` yields the same errors.
6. After reading everything here and trying to kill the process with process hacker (as admin):
```
Unable to terminate svchost.exe (PID 11111): An attempt was made to access an exiting process
```

Trying to kill the thing before trying to stop it with ph2 throws another error, though I don't remember it now - I'll add it here when this happens again. 

Rebooting windows is horrible... I have multiple virtual desktops, each of which running different things, multiple servers, multiple ides, multiple browsers, etc. Before this issue I would restart Windows once a... never?, because the cost of getting everything up and running is just ridiculous. I really need an option different from `reboot` - any ideas are welcome.

**Comment by mewbow1** [comment]
I have found a solution, but it requires the use of third party software.
Download KProcessHacker3 from https://processhacker.sourceforge.io/
**Note: Antivirus softwares may detect it as a virus as it can be used to modify or kill system processes. Please disable your Antivirus software before proceeding.**

**Step 1:** Write click on ProcessHacker.exe and Run As Administrator.
![image](https://user-images.githubusercontent.com/20864021/68136278-04d1d000-ff4b-11e9-8828-62c2d632da1c.png)


**Step 2:** Go to services tab, search for LxssManager, right click on it and select Go to process.
![image](https://user-images.githubusercontent.com/20864021/68136479-5aa67800-ff4b-11e9-9b7f-471c134ec3fc.png)


It will automatically highlight the **svchost.exe** process associated with LxssManager.
![image](https://user-images.githubusercontent.com/20864021/68136724-c092ff80-ff4b-11e9-9ef1-f716c0be8a98.png)

**Step 5:** Since it is automatically selected, just press **Del** button on your keyboard to terminate the process and click on **Terminate** to confirm the same.
![image](https://user-images.githubusercontent.com/20864021/68136816-e5877280-ff4b-11e9-8150-250b6d748b6c.png)

**Step 6:** Again go to services tab, search for LxssManager, right click and click on **Start** to start the LxssManager service.
![image](https://user-images.githubusercontent.com/20864021/68137077-5c247000-ff4c-11e9-89d8-ab118af5f15c.png)

**Step 7:** Since KProcessHacker3 creates a SYSTEM level service to manage and kill system services, open Administrator Command Prompt and use the command
`sc stop kprocesshacker3`
![image](https://user-images.githubusercontent.com/20864021/68137340-cfc67d00-ff4c-11e9-9953-0410b2e30c0b.png)

Now enjoy WSL.
Before enabling antivirus again, delete the KProcessHacker folder from your Downloads folder.

**Comment by edemen** [comment]
Looks like even KProcessHacker won't help if you already have initiated the service stopping. It just brings up an error about trying to access a process that is in a shutdown already.

**Comment by jjgh** [comment]
Can't believe this hasn't been fixed after 4 years...

**Comment by LoganDark** [comment]
@mewbow1 Nope.

![image](https://user-images.githubusercontent.com/4723091/76171519-9778ba80-6149-11ea-8a83-76e25d1e9edd.png)

Running Process Hacker as administrator.

**Comment by dmex** [comment]
> Running Process Hacker as administrator.

Try using the nightly builds of Process Hacker - the v2.39 release doesn't support Windows 10 @LoganDark

**Comment by LoganDark** [comment]
@dmex When running as administrator, it says it can't load the kernel module because access is denied.

When not running as administrator it didn't. So being the idiot that I am, I tried to start up bash and then tested if PH could terminate it.

It couldn't.

Now I have to reboot **again**, and I don't say that lightly.

![image](https://user-images.githubusercontent.com/4723091/76710177-876d5780-66c2-11ea-9a95-4918cbbe645a.png)

**Comment by dmex** [comment]
>  it can't load the kernel module because access is denied.

The kernel driver is required for WSL process termination. That access_denied error can only occur when Antivirus software and/or malicious software has blocked the driver from loading. You will need to add exceptions to your security software or remove the malicious software to be able to use the driver.

**Comment by LoganDark** [comment]
> The kernel driver is required for WSL process termination.

Which is why I included it in my post.

> That access_denied error can only occur when Antivirus software and/or malicious software has blocked the driver from loading. You will need to add exceptions to your security software or remove the malicious software to be able to use the driver.

It was my antivirus, thanks. I have it on silent to stop ad popups (shitty I know), but when I turned off silent mode, it made a popup about the kernel module. Should be able to add an exception. I am not going to test this again till later.

**Comment by iamdevlinph** [comment]
Just encountered this recently. When I boot up my PC, the WSL doesn't launch properly and when I try to stop it through the `services.msc` then it gets stuck on `STOPPING`.

And so far the only solution that I found was to reboot.

Windows version: Version 1909 (OS Build 18363.720)

**Comment by Kagami** [comment]
Happens to me every day. Should be somehow related to [EACCESS issue in WSL1](https://code.visualstudio.com/docs/remote/wsl#_i-see-eaccess-permission-denied-error-trying-to-rename-a-folder-in-the-open-workspace) because the process than can't be killed is `node`  and seems to be a file watcher. Those unkillable processes probably appear when I remove folders while VS Code Remote is running.

@mewbow1 thank you so much, this actually helped. (I used current 2.39 release of Process Hacker.)

Killing svchost didn't stop the LxssManager though, so I clicked restart, Process Hacked became unresponsive, I forcibly closed it, reopened and LxssManager showed as stopped this time. Then I started the service, started Ubuntu terminal and unkillable processes has gone. Yay, no more reboots.

>Looks like even KProcessHacker won't help if you already have initiated the service stopping

I didn't try to stop the service via Task Manager this time, maybe that's why it worked.

**Comment by Kagami** [comment]
Unfortunately this led to another problem: I couldn't rename folder which  was probably occupied by that process. Search for handle didn't show anything. At the same time I could restart LxssManager service perfectly fine. So it has to be some issue with WSL/NTFS interop...

**Comment by CherryDT** [comment]
I have the same issue recently. I'm also using VS Code Remote with WSL and I also had mysterious issues with renaming or removing folders while it's open (or running npm install).

Furthermore, a reproducible way for me to cause a hung WSL is running Jekyll with the watch option for a while and changing some files. It won't take more than a few minutes to get everything stuck.

I'm on 18363.1139. Is this fixed in newer versions? The problem is just that for many months my update screen says that the 2004 version is "being prepared" and I will get notified when it's available for my machine... (still waiting to get that notification...)

**Comment by Ronak-59** [comment]
Still not fixed after 5 years. All commands hang and LxssManager is permanently in the "Stop Pending" state even after Reboot. Spent 6+ hours trying different suggestions mentioned in this thread and none working. This needs to be fixed ASAP though.

**Comment by CherryDT** [comment]
> LxssManager is permanently in the "Stop Pending" state even after Reboot.
That doesn't sound possible, are you sure you rebooted and didn't just turn it "off" and on again (possible not executing an actual restart but for example hibernation)?

**Comment by Ronak-59** [comment]
@CherryDT I'm sure I "rebooted". I tried all possible ways I found on internet including Registry Edit. It's just not working and seems constantly in "Stop Pending" state. No command works except `sc query LxssManager` 

Elevated CMD and elevated Powershell are not helping too.

**Comment by SalehAce1** [comment]
Will this ever actually be fixed or are we supposed to reboot our system every time LxssManager fails forever?

**Comment by iamdevlinph** [comment]
I'm at Version 20H2 (OS Build 19042.985) and haven't encountered this issue anymore.

But yeah, as far as I know, the only solution is to reboot.

**Comment by Pyker** [comment]
I can confirm this still happens in 20H2 (19042.985). I'm not sure if it's related to hibernation or just WSL being unused for a while.

**Comment by cristianuibar** [comment]
Just happened to me on 21H1 so still not fixed.

I believe the Bitdefender AV caused this glitch due to a PHP script virus it encountered during a GIT clone operation.

**Comment by MysteryMS** [comment]
This just happened to me on the insider builds of Windows 11.
Thanks to this thread I could find a way to fix this - ending the process related to the service (used Process Hacker tho but I'll try with normal task manager next time it happens)

> I can confirm this still happens in 20H2 (19042.985). I'm not sure if it's related to hibernation or just WSL being unused for a while.

Can relate that I'm having this issue hibernating my PC, too.

**Comment by abdennour** [comment]
happen also with the corporate laptop. 

PS C:\> Restart-Service -Name "LxssManager"
WARNING: Waiting for service 'LxssManager (LxssManager)' to stop...
WARNING: Waiting for service 'LxssManager (LxssManager)' to stop...
WARNING: Waiting for service 'LxssManager (LxssManager)' to stop...
WARNING: Waiting for service 'LxssManager (LxssManager)' to stop...

**Comment by abdennour** [comment]
i used taskkill command (https://www.youtube.com/watch?v=e7IsO51eTYw).
I faced another issue, i reached this point (https://stackoverflow.com/a/19341022/747579)
At the end, the machine has been rebooted because i killed the process with PID 80, 
then after reboot, things work

**Comment by MCXIV** [comment]
Did someone find a solution after all these years?

**Comment by FinalFortune** [comment]
Install linux as main OS, easiest fix. No need to use windows anymore.

**Comment by CherryDT** [comment]
This doesn't work, as mentioned it is **unkillable** until rebooting. Doing what you wrote will get the process stuck in a "terminating" state. It stays and when you try a second time you get the error that the process is already being terminated so you can't terminate it again. From a service perspective it will stay stuck "stopping" so start-service will also fail because the service is in an invalid state for starting it.

**Comment by FinalFortune** [comment]
> @FinalFortune This doesn't work, as mentioned it is **unkillable** until rebooting. Doing what you wrote will get the process stuck in a "terminating" state. It stays and when you try a second time you get the error that the process is already being terminated so you can't terminate it again. From a service perspective it will stay stuck "stopping" so start-service will also fail because the service is in an invalid state for starting it.

Well I'm fairly certain my WSL had borked from hibernate.  It wasn't terminating, so I ran the above command, which was derived from the stackoverflow solution, and it worked.  However im not sure it was the exact same state mentioned earlier in this issue, I will confirm next time with the appropriate commands.

This issue has been a constituent in making using docker on windows a collosal pain the ass to use in windows, I just come from the C# side so using docker from WSL was a natural progression, and plain Hyper V docker was far slower.  However gorging myself on a bed of blades may have been a more enjoyable experience.

**Comment by pabbasi** [comment]
> **@fpqc**  quietly closing this up @benhillis . Should be marked "bydesign" by merit of it being a kernel driver.

Since this is 'by design' , has an official workaround to this issue also been designed?  😆 ? 

 `wsl --shutdown` hangs indefinitely every time, and restarting windows gets old rather quickly.

**Comment by mtrin** [comment]
I am having a much better time after creating a powershell script that runs `wsl --shutdown`, waits and then hibernates the computer. Just make sure to close vscode before doing it.
