### ISSUE TITLE
unable to initiate postgresql cluster with sudo pg_createcluster 9.5 main --start

### ISSUE THREAD

**Issue by eugen-don** [Microsoft/BashOnWindows#1089]
Build: latest
Hi,
after updating to 16.04 LTS with do-release-upgrade -d and installing postgresql 9.5, the system fails to initiate a database cluster.

heres the feedback of the cluster init command:
```
root@WS1:/mnt/c/Windows/System32# sudo pg_createcluster 9.5 main --start
Creating new cluster 9.5/main ...
  config /etc/postgresql/9.5/main
  data   /var/lib/postgresql/9.5/main
  locale en_US.UTF-8
FATAL:  could not create shared memory segment: Function not implemented
DETAIL:  Failed system call was shmget(key=1, size=56, 03600).
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/9.5/main"
Error: initdb failed
root@WS1:/mnt/c/Windows/System32#
```

FATAL:  could not create shared memory segment: Function not implemented

seems like not all common kernel-functions are implemented yet?

**Comment by fpqc** [comment]
No. 

https://msdn.microsoft.com/en-us/commandline/wsl/release_notes

If you have a fatal error coming from a program with the result "Function not implemented", it means that there's a missing syscall or socket mode or option or whatever.  I think for this, you should have searched for Postgresql in the issues page before opening up a new issue, since there is an open thread with lots of comments and information already:

https://github.com/Microsoft/BashOnWindows/issues/61

iirc the thing that's failing in this case is something involving sysVipc

(If you could close this topic and subscribe to the linked one, the devs would probably appreciate it)

**Comment by eugen-don** [comment]
this topic propvides some further info, thanks for the link...
