### ISSUE TITLE
stop service when closed bash

### ISSUE THREAD

**Issue by xtoolkit** [Microsoft/BashOnWindows#1096]
hi
i install tor & use this.
but i see a problem.
when start tor service, tor working, when closed bash window, tor service stoped!
how fix this problem?
sry 4 my bad english

**Comment by aseering** [comment]
Hi @xtoolkit -- right now, WSL is not really designed for running services.  When it stops running, it stops any processes that you may have started.  Normally that happens when you close the bash window.  So what you are seeing is expected behavior.

Some people have figured out how to make other services work in the background.  There are instructions here for ssh:
http://wsl-forum.qztc.io/viewtopic.php?f=6&t=10
And the comments underneath that post discuss how you might make the same thing work for other services.
