### ISSUE TITLE
Blue screen when access a rails app running on bash on windows

### ISSUE THREAD

**Issue by edsonlima** [Microsoft/BashOnWindows#1136]
After last update to `10.0.14936` (Build `14936.rs_prerelease.160923-1700`) version, all times that I try to access a running rails app on any browser or even using curl/wget in the same running bash, Windows crashes and shows the blue screen bellow:

![img_20160928_235202798_hdr](https://cloud.githubusercontent.com/assets/154353/18940218/9355beae-85dc-11e6-866d-65d62f8a1a04.jpg)

Note that this error occurs only when I try to access the rails app, not when I start , and before the update everything worked very well.

**Comment by benhillis** [comment]
This is a known issue and we are working on a fix. I apologize for the inconvenience, we will get this fixed ASAP.

**Comment by fpqc** [comment]
@benhillis 

Beta means never having to say you're sorry =]

**Comment by aseering** [comment]
For what it's worth, I've also seen a blue-screen on the latest release.  Just once so far (when running `apt-get install clang-3.5`).  It sounds like y'all have this in hand, but if there's any additional information that you could use, I (and, I'm sure, others) would be happy to try stuff out.

**Comment by edsonlima** [comment]
@benhillis, don't worry, this is the first situation that I see a blue screen :)
As a workaround for now, I'm using docker.

**Comment by ktrinanm** [comment]
I'm seeing this with mlton and other compilers

**Comment by sunilmut** [comment]
Yes, this seems to be the same issue mentioned in our [14936 release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes?f=255&MSPPError=-2147217396). The fix is already being fast-tracked to the release branch.

**Comment by marlesson** [comment]
me too. In my case, this happens when i access my mysql server in ubuntu. Only i open one conection, with rails app or php app.

(Build 14936.rs_prerelease.160923-1700)

**Comment by fpqc** [comment]
@marlesson Lol come on man it's a known issue look at @sunilmut 's link.  

By the way @sunilmut How come your thing doesn't say "Microsoft Member" like most of the other people on the team?

**Comment by benhillis** [comment]
@fpqc He shows up as Microsoft Member to me.

**Comment by fpqc** [comment]
@benhillis Weird, you don't either.  Only bitcrazed and zadjii do, lol.  Maybe it's because you're not only MSFT members but also admins of this particular project (so it would say MSFT member if you posted on like the powershell github issues page).  I dunno. 
![2016-10-06](https://cloud.githubusercontent.com/assets/6083371/19172504/30d6be62-8bf0-11e6-8ad8-75033d953dd1.png)

Probably github's fault.

**Comment by benhillis** [comment]
@fpqc I think I figured it out.  I was listed as a "Private" member of Microsoft.  I suspect it'll show up now.

**Comment by dreyks** [comment]
Can't wait for this to pull through to the fast-ring. Checking for updates every day. I understand however that's what they warn you about when you switch to fast ring so no sweat =)

**Comment by sunilmut** [comment]
@all The BSOD should be fixed in 14942 (see [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)), which just got released.

@fqpc - Thanks for letting me know about the membership :). Just like @benhillis, to me it was always showing as "Microsoft member". I have updated my settings following @benhillis.

**Comment by dreyks** [comment]
fixed indeed. can be closed

**Comment by benhillis** [comment]
Thank you for confirming.
