### ISSUE TITLE
Cannot build openssl using windows bash

### ISSUE THREAD

**Issue by marinat** [Microsoft/BashOnWindows#1139]
I need to build openssl using bash. On ubuntu all ok. But when I use windows bash I got error:

make[2]: Entering directory `/mnt/e/workspace/openssl/openssl/crypto/md2'
gcc -I.. -I../.. -I../modes -I../asn1 -I../evp -I../../include  -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -m64 -DL_ENDIAN -O3 -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM   -c -o md2_dgst.o md2_dgst.c
In file included from md2_dgst.c:62:0:
../../include/openssl/md2.h:64:4: error: #error MD2 is disabled.
 #  error MD2 is disabled.

How to fix this? Or bash on windows has no md2 support yet? When it will be added?

**Comment by aseering** [comment]
Hi @marinat  -- MD2 is a feature of OpenSSL; it's enabled or disabled based on the options passed to OpenSSL's configure script and what that configure script detects about your environment.  So this error happens if there's either a bug in OpenSSL's build script (possibly triggered by a missing feature in WSL) or if something about how you are building OpenSSL isn't quite right.

How are you building OpenSSL?  (What commands are you using to configure and make it?  Are you building it in your Linux home directory or on the Windows filesystem?)

If you are building it as part of an existing project that you've had to try to build a couple of times to get it to work, have you tried again with a clean build?

Also -- do you actually need to build OpenSSL?  Ubuntu ships with a copy that you can develop against, which works fine for me.  (I realize that your answer may be "yes" -- I have compiled OpenSSL 1.0.1 myself within WSL and it worked fine, though that was some time ago and using an older version of WSL.)

**Comment by marinat** [comment]
Sorry, it was my mistake, I used old openssl version

**Comment by misenesi** [comment]
I am glad your issue is solved @marinat! Let me close the bug for you.
