### ISSUE TITLE
the 'd' key doesn't work

### ISSUE THREAD

**Issue by scottidler** [Microsoft/BashOnWindows#1225]
**A brief description**

The 'd' key doesn't work in the shell that is opened.  However, sshing into another computer, it works fine.

**Expected results**

d's appear on the screen

**Actual results (with terminal output if applicable)**

no d's

**Your Windows build number**

version 1607 (OS Build 14393.321)

**Comment by fpqc** [comment]
What's your locale/localization settings?

**Comment by scottidler** [comment]
I would assume American, US.  I just did the default install.  I also
completely removed Bash for Windows last night, rebooted, reinstalled and
rebooted again.  The issue remains.  I also should mention that initially
the 'd' key did work because I have commands in the shell history with 'd's
in them.  Copying pasting text from another program that has d's in them
and attempting to paste them also drops them.

-Scott

**Comment by zadjii-msft** [comment]
... what? I've never heard or seen ANYTHING like this. I'll forward this to the team, because honestly I have no idea where to begin. I'd think that your language setting might be messed up, but if you're on en-us I doubt that's it.

Does Ctrl+D work in applications? Is it only the 'D' key and nothing else?

**Comment by scottidler** [comment]
Yeah it's crazy and I don't know how to debug it!  Shift 'd' works I am
pretty sure Ctrl 'd' does too, but I don't have the machine in front of me
to confirm.

I am considering reinstalling Windows to fix it.  I might hold off to help
debug.

-Scott

**Comment by zadjii-msft** [comment]
Yea I'd love to debug this. When you get a chance:
 * is it specific to bash.exe? Or does it not work in cmd or powershell either?
 * If you input a command like `dir`, and only `ir` shows up, does executing the command execute `ir` or `dir`?

**Comment by scottidler** [comment]
Some of these things I can't test right now as the laptop is at home.  I
haven't tried cmd or powershell since this started.  I primarily use Linux
these days and mostly just ssh into one of my servers downstairs.

On your second question, I can confirm that the d never gets drawn in the
terminal and therefore when the command is executed, it only executes the
remaining letters.  So in your case only ir would be executed.  Here is
another example, If I wanted to run 'cd repos' 'c repos' would be in the
shell and I would get an error.

-Scott

**Comment by scottidler** [comment]
To answer your question both cmd.exe and powershell register 'd's when
pressed.  However, bash for windows does not.

-Scott

**Comment by scottidler** [comment]
Another peculiarity is that sshing to my ubuntu server restores the normal operation of 'd's!  So it something tied specifically to bash for windows running on my windows computer.

**Comment by fpqc** [comment]
@scottidler Honestly this sounds like a corrupt terminfo file?

**Comment by sidler-mozilla** [comment]
I reinstalled the ncurses-term package and rebooted the computer.  There is no change in the behavior. 

Things to consider:
  - it used to work
  - removing Bash for Windows DOES NOT reset the behavior (it lingers)
  - it does not affect cmd.exe and powershell in the same way (they work fine)
  - sshing to another computer does not carry the problem over
  - reinstalling ncurses-term does not affect the change (not surprised because of #2 above)
  - it affects copy and paste behavior as well
  - shift-d and ctrl-d both work properly
  - CAPSLOCK + shift-d does not work

Is there anything else that can be done?  Are there logs somewhere that might help?

**Comment by zadjii-msft** [comment]
What does `stty -a` output?
What's in your `/etc/inputrc`?
Does using `tmux` fix it?

**Comment by sidler-mozilla** [comment]
@zadjii-msft you nailed it!  There was a line that should have been commented out in the /etc/inputrc

do not bell on tab-completion

added a # in front of that and it works again.

I must have accidentally done that when trying to turn off the incessant bell sounds.  Very strange behavior for that text in that file to disable all 'd's because "do not..." starts with a 'd'.

Anyway thank you very much for helping me debug it.

**Comment by zadjii-msft** [comment]
👍 Awesome! I'm glad to hear we found it. That was an interesting one no doubt.

I'll close this now that it's figured out.

**Comment by Jared975** [comment]
/etc/inputrc

removing the comment from `do not bell on tab-completion` breaks the D key still in WSL still.  

I was editing that file to get rid of that super annoying bell.  Just removing the comment from 
`set bell-style none` removes all the bells and more torture is over.

**Comment by Kantzow** [comment]
I have the same problem.. and need some help on what to do, because:
1. I can't ssh into my wsl because it hasn't been set up.
2. I can't edit such files without using the 'sudo' command.
3. I can't make an alias in .bashrc e.g., "alias new='sudo' because the 'd' will either way be removed in the terminal.  
Any suggestions on what I can do without reinstall?

**Comment by Kantzow** [comment]
> I have the same problem.. and need some help on what to do, because:
> 
> 1. I can't ssh into my wsl because it hasn't been set up.
> 2. I can't edit such files without using the 'sudo' command.
> 3. I can't make an alias in .bashrc e.g., "alias new='sudo' because the 'd' will either way be removed in the terminal.
>    Any suggestions on what I can do without reinstall?

SOLVED:
Opened emacs and ran a shell inside of it --> sudo gedit /etc/inputrc --> uncommented the line.
(I tried to edit the inputrc file from the windows system, but it wouldn't let me.)

**Comment by MalingaTee** [comment]
> @zadjii-msft you nailed it! There was a line that should have been commented out in the /etc/inputrc
> 
> do not bell on tab-completion
> 
> added a # in front of that and it works again.
> 
> I must have accidentally done that when trying to turn off the incessant bell sounds. Very strange behavior for that text in that file to disable all 'd's because "do not..." starts with a 'd'.
> 
> Anyway thank you very much for helping me debug it.

**Comment by AD007xD** [comment]
This issue still exists. You have to keep the `# do not bell on tab-completion` commented out and doing `set bell-style none` removes the bell sound as this comment mentions https://github.com/microsoft/WSL/issues/1225#issuecomment-443452212.

If you absolutely have to use `d` anywhere in WSL, be sure to have that character copied in your clipboard as that still works.
