### ISSUE TITLE
Updater uses non-secure http fetches

### ISSUE THREAD

**Issue by David-dp-** [Microsoft/BashOnWindows#1227]
A terminal process just popped up for 2 minutes on my Win10 machine and then disappeared. While it was up, I changed focus to it to have a look, and it was logging that it was making http requests to ubuntu domains, apparently for this bash console I enabled.

I'm very concerned that the fetches are using http instead of https.

**Comment by aseering** [comment]
You have observed Ubuntu's package-update process.  Ubuntu uses GPG signatures rather than HTTPS encryption so that it can guarantee secure package distribution even if packages are passed through untrusted intermediate mirror-servers.  (HTTPS only protects data while it's in transit over the network.  GPG protects data while it's in transit and additionally while it's at rest on Ubuntu's content-distribution servers; Canonical needs to make sure that, even if someone somehow does hack into the Ubuntu software-update servers directly, they still can't cause insecure packages to be distributed, which is not a problem that HTTPS is designed to solve.)

Ubuntu has a document explaining why this approach is secure, and how to work with their security model, [here](https://help.ubuntu.com/community/SecureApt).  Ubuntu seems to consider GPG to be sufficient, and has not configured HTTPS access to their update servers.  WSL is running Ubuntu on Windows; it's therefore required by specification to do what Ubuntu does.

If, given this new information, you're still concerned about Ubuntu's security, you should follow up with Canonical and convince them to host their data over HTTPS.  I personally think they should because HTTPS is very easy to implement these days, and it does afford a tiny amount of additional privacy.  (If two packages have the same size and were updated at the same time, and if neither is a built-in package so you could have either one installed, then an eavesdropper can't tell which of the two you downloaded if HTTPS is used.)
