### ISSUE TITLE
Sudo lacks an allocated tty

### ISSUE THREAD

**Issue by gczuczy** [Microsoft/BashOnWindows#1264]
When trying to sudo, the following happens:

```
$ sudo su -
sudo: no tty present and no askpass program specified
```

I have to start sudo with -S, that is, to make it read from stdin, and not from the tty.

Also, other processes might require a terminal, like screen, or editors, etc.

Winver: Microsoft Windows [Version 10.0.14393
On the ubuntu, did a do-release-upgrade last week

**Comment by fpqc** [comment]
Update to the insider builds.  This is fixed since 14915.

**Comment by gczuczy** [comment]
Could you please point me to some material that describes how to do that, without upgrading windows to the insider build? This is a workstation, and not a sandbox, so I can't follow the insider windows build.

**Comment by fpqc** [comment]
You need to run the insider builds if you want it early. Otherwise the soothsayers (the blogs) say that RS2 is releasing in March.

**Comment by gczuczy** [comment]
@fpqc  Thank you, March is fine by me. I like this direction, and it's kinda usable even in this state. Just keep on the good work going :)

**Comment by fpqc** [comment]
Here's a workaround for you, because you are so nice: get a copy of the sudo binary from Ubuntu 14.04, and extract it to /usr/local/bin.

**Comment by benhillis** [comment]
My recommendation is for users on Windows Anniversary Update to not upgrade to 16.04.

**Comment by fpqc** [comment]
@benhillis Oh yeah, ps is broken, top is broken, etc. TheRealKenC gave a list of utilities you'd have to install from 14.04 to get it working halfway decently.

**Comment by rodrymbo** [comment]
@benhillis 

There seem to be a lot of people with 14393 reporting things that have long since been fixed. Maybe the [reporting template](https://github.com/Microsoft/BashOnWindows/blob/master/CONTRIBUTING.md#3-windows-version--build-number) could include a mention that 14393 is a bit old, and point them to the [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes) or suggest a way, before reporting something, to search the github issues, to learn how others dealt with it back in that version?

**Comment by fpqc** [comment]
@rodrymbo Lol, you could file a pull request on the template.
