### ISSUE TITLE
launching a .exe stored outside of drvfs with a relative path can result in launching another .exe in Win32 search path with the same name

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#1325]
* A brief description

IIRC .exe outside of DrvFs are not supposed to be executable with WSL interop.
However, trying to launch one with a relative path apparently results in the default win32 lookup rules being used based on the filename. This can result in a wrong program being invoked.

* Expected results

Nothing is launched because the .exe was not in DrvFs

* Actual results (with terminal output if applicable)

Another .exe with a corresponding name can be launched, depending on win32 exe search rules

* Your Windows build number

14959

* Steps / All commands required to reproduce the error from a brand new installation 

Example:

    ~$ cp /mnt/c/Windows/System32/cmd.exe notepad
    ~$ ./notepad

=> Launches notepad.exe... (I actually don't expect cmd.exe to run because this binary copy is not in DrvFs, but I certainly not want /mnt/c/Windows/System32/notepad.exe to launch, which is what happens here)

Because WSL only runs on Win64 installs, and Win64 installs do not support Win16, I would recommend always using lpApplicationName of CreateProcess and doing name resolution under WSL (like with readlink -f, so that we can use symlink to DrvFs in LxFs and execute through them properly)

It would also be worth to consider if a "\\\\?\\" prefix or similar can be used, in order for extra long paths to work.

**Comment by benhillis** [comment]
@xilun Thanks for opening this.  What you're seeing is some "legacy" behavior of the binfmt interpreter, essentially the ability to run "/init notepad".  We attempt to translate the first argument (in this case notepad) into a full NT path but if that fails we end up passing it to the CreateProcess api as-is.

This behavior exists from before the binfmt interpreter work and we decided to keep this in to see how the community responded.  I agree is causes some strangeness in cases like this.  However, I do also feel like the ability to create NT processes using NT path resolution is valuable.  Rather than what we do today it should probably be explicit though (perhaps revive the winrun symlink and only do the NT path lookup if using winrun).

**Comment by xilun** [comment]
I guess it would be good to be able to do that explicitly (it would be weird for me to declare it to be not good, given what I did in outbash/wrun :p ). But when it goes through binfmt, with the behavior like in the example I gave, I think the potential for confusion is quite important...

**Comment by benhillis** [comment]
@xilun - Agreed.

**Comment by benhillis** [comment]
I've checked in a fix that resolves this issue. It will be in an upcoming Windows Insider build.

**Comment by ddfznt** [comment]
@benhillis So basically I can use `/init` with anything that is in my "Win-Side" PATH? I love that!❤👍✨
``` 
 /mnt/c/Windows/System32/calc.exe <=> /init calc 
```

**Comment by benhillis** [comment]
That's the current behavior in insider builds but that functionality is going away for the reason @xilun described.

**Comment by shawnz** [comment]
@ddfznt you could maybe use "cmd.exe /c calc" instead.

**Comment by benhillis** [comment]
Yes that would still work.

**Comment by xilun** [comment]
Note that there is a drawback in using cmd though: its command line character escaping rules are insane. This can be annoying if you want to pass a funny filename (or URL, etc.)
