### ISSUE TITLE
nodejs --inspect fails to work properly

### ISSUE THREAD

**Issue by nickolasclarke** [Microsoft/BashOnWindows#1339]
* A brief description
using `nodejs --inspect` fails to load properly
* Expected results
I should be able to execute `nodejs --inspect` and use the resulting URL to debug issues in chrome
* Actual results (with terminal output if applicable)
I get a proper URL, but when I try to actually use the console in chrome, nothing seems to be interpreted properly and eventually my terminal "Freezes" so to speak. It becomes unresponsive to a `cntrl + c/z` and I have to  close the window manually and begin a new session. 
``` chrome-devtools://devtools/remote/serve_file/@60cd6e859b9f557d2312f5bf532f6aec5f284980/inspector.html?experiments=true&v8only=true&ws=localhost:9229/b3791592-f268-423f-8a69-14922fb056fa ```

* Your Windows build number
Version 1607, build 14393.351
* Steps / All commands required to reproduce the error from a brand new installation 

* Strace of the failing command

* Required packages and commands to install
nodejs v6.9.1
See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by therealkenc** [comment]
Seems okay in 14959 FWIW so it's something fixed since Anniversary. It's actually kind of cool with Chrome on Windows and Node on WSL.

**Comment by nickolasclarke** [comment]
@therealkenc it worked for me the first time I launched it, but subsequent launches, I try to send anything to the console, and I get nothing back.

**Comment by therealkenc** [comment]
Can't say I've played with it a lot. Send a link to a gist with the output of `strace -ff node --inspect [whatever] 2> node.strace` and it will hopefully show where the last syscall froze. If you are on 14393 there was a known freeze type problem unresponsive SIGINT (ctrl-c). Might be the same; either way you'll have to  move onto insider builds for a fix though.

**Comment by noinkling** [comment]
@nickolasclarke I've actually had issues with the devtools console when running Node apps from Windows, like the sources tab will function fine but the console (both the tab and the popup) seems a bit temperamental sometimes, so maybe this isn't a WSL issue? On the other hand I don't think I've had my terminal freeze while debugging.

**Comment by nickolasclarke** [comment]
@noinkling hehe yes, indeed it is experimental. I am seeing the exact same thing actually. It worked the very first time I launched by I've not been able to get the console to work at all since that first launch. It takes any input, but nothing is ever returned. Have you found any way to reproduce that and better yet, how to get around it?

**Comment by noinkling** [comment]
@nickolasclarke yeah that was the issue I was running into, but it was more intermittent for me, i.e. sometimes the console would work properly for a debug session and other times it wouldn't. I don't know a proper fix, I can only tell you that  it seemed more likely to work properly if:

1. I either didn't or did (can't remember) use `--debug-brk` to automatically break on the first line.
2. I made sure that the console drawer (the popup one that appears when you press esc) was closed the last time I had dev tools open, so that it doesn't *initially* appear at the bottom of the source panel when I navigate to the debug URL.

But both of those could just be placebo.

As an aside, I've had far more luck using the Node debugger (the new one that uses the same protocol) in VS Code.

**Comment by nickolasclarke** [comment]
yep, digging further I found nodejs/node#7891 and found if I use `127.0.0.1` in lieu of `localhost` in the url given that it seems to work, mostly. Regardless, this probably is not a WSL issue as mentioned. closing.  @noinkling thanks for the feedback.
