### ISSUE TITLE
Python netifaces.interfaces() returns [Errno 22] when connected with internet on build 14965

### ISSUE THREAD

**Issue by DaGrumb** [Microsoft/BashOnWindows#1414]
I'm having problems with roscore returning Errno 22 on build 14965, while being connected with the internet. However, when I disable the connection, roscore runs just fine. Roscore should work on build 14965, but it doesn't. 

Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/__init__.py", line 307, in main
    p.start()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/parent.py", line 279, in start
    self.runner.launch()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 654, in launch
    self._setup()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 630, in _setup
    self._launch_master()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 394, in _launch_master
    validate_master_launch(m, self.is_core, self.is_rostest)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/roslaunch/launch.py", line 83, in validate_master_launch
    if not rosgraph.network.is_local_address(m.get_host()):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 176, in is_local_address
    local_addresses = ['localhost'] + get_local_addresses()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 219, in get_local_addresses
    for iface in netifaces.interfaces():
OSError: [Errno 22] Invalid argument

My Windows build is Windows 10 Pro Insider Preview Build 14965

**Comment by fpqc** [comment]
This is a known issue related to ip addr not working.  One way to fix this is to use netsh in windows to disable the teredo tunneling interface.

**Comment by sunilmut** [comment]
Just FYI that the teredo issue is fixed and is making its way to the insider build. Thanks @JasonLinMS, who can also provide more information about the issue. Something to do with the fixed size buffer in the 'ip' tool to store the address and the incompatibility with what the 'teredo' interface reports on Windows.

**Comment by JasonLinMS** [comment]
Thanks @sunilmut 
Yes, the root cause is that the Teredo network adapter has a 32-byte hardware address, which is not handled well inside WSL (and has just been fixed recently).
We also found that the Linux "ip addr show" tool does not handle 32-byte hardware addresses well either - it will crash when trying to display the HW address due to a string buffer overflow. You will see this crash in "ip" in the next Insider build if you have Teredo enabled.
Note that these are two different issues with the handling of 32-byte HW addresses - one in WSL, and one in "ip". The issue in WSL has been fixed, so in the next Insider build you will see the issue in "ip". (Most other tools handle this correctly)

We think that the fix should be in the "ip" code, and plan to reach out to them. If anyone here is familiar with the standards regarding hardware address (not MAC address) length, please let us know.

**Comment by gavanderhoorn** [comment]
Related: #1391?

**Comment by sunilmut** [comment]
The teredo issue should be fixed in [15007](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes#build-15007)
