### ISSUE TITLE
app that you are trying to run is not supported on this version of Windows

### ISSUE THREAD

**Issue by boskiv** [Microsoft/BashOnWindows#1448]
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Ivan Skiridomov>bash
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

The app that you are trying to run is not supported on this version of Windows.
```
OS Name	Microsoft Windows 10 Enterprise N 2016 LTSB
Version	10.0.14393 Build 14393

Developer Mode is On
![screenshot 2016-12-02 08 51 55](https://cloud.githubusercontent.com/assets/1939783/20825424/a16daf20-b86c-11e6-9fbe-80c2d493c8e3.png)

Feature was installed:
![screenshot 2016-12-02 08 52 58](https://cloud.githubusercontent.com/assets/1939783/20825441/c6e6d344-b86c-11e6-935e-4e68eb11a5c2.png)

**Comment by fpqc** [comment]
The beta was accidentally included in the LTSB release.  It was subsequently disabled because it cannot be updated or even bugfixed without updating the kernel-mode drivers `lxcore.sys` and `lxss.sys`, both of which are strictly bound to specific versions of the Windows kernel (for example, work on networking to support some WSL features was transported into the kernel-mode "Winsock Kernel" core piece of the NT kernel, where [it will also be used to provide more socket functionality to the Win32 usermode Winsock API as well](https://blogs.msdn.microsoft.com/wsl/2016/11/08/225/)).  

The drivers `lxcore.sys` and `lxss.sys` (being beta components) are being maintained directly along the "Fast ring" of the Insider branch of Windows 10.  The "slow ring" provides snapshots of the "fast ring", and the Current Branch will be replaced roughly this April by another fork of the Insider branch.  Until the Windows Subsystem for Linux loses its "beta" tag, it will only be available (updates, bugfixes, etc) in the Current Branch as a snapshot of its state at the date of the fork, without even bugfixes being backported to the current branch from the Insider Branch. 

Given that even the Current Branch is not currently receiving bugfixes, upgrades, or likely even security fixes, it would be impossible to handle bugfixes in LTSB (releases scheduled 2-3 years apart!) of a feature that is highly incomplete and has already hit several bugchecks (many bugchecks are also potential security vulnerabilities, and it is dangerous to use buggy drivers in kernel-mode).  

So a decision was taken by Microsoft to remove this feature from LTSB until it is out of beta, at which point it will at least have bugs and security vulnerabilities fixed and backported.  On the other hand, this also means that LTSB will not be receiving this functionality in stable form until at least 2018 if not 2019.  

If you want to use WSL, it is highly recommended to run Insider builds or at the very least the Current Branch, which receives updates roughly every nine months.

**Comment by benhillis** [comment]
Marking as duplicate of #1281.

**Comment by Flyweightt** [comment]
Very nice explanation and again a terrible choice of MS, so I think I installed Win 10 enterprise for nothing. Please look how FreeBSD handles Linux using a subsystem and a kernel mode module that can be updated.
Why do you allow installing the linux subsystem at all when you cannot run bash on newer W10 builds?
