### ISSUE TITLE
Unable to use ssh for local port forwarding

### ISSUE THREAD

**Issue by metasoarous** [Microsoft/BashOnWindows#1480]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

Unable to do local port forwarding

* Expected results

Ability to do local port forwarding

* Actual results (with terminal output if applicable)

```
> ssh -L 5000:localhost:5000 some.server.com
...
bind: Address already in use
>
```

I successfully did this from a Linux machine I have, and it worked without issue, forwarding the desired port.

* Your Windows build number

14393.447

* Steps / All commands required to reproduce the error from a brand new installation 

Have to have a remote server running with a port to test... not sure of best advice here. After that just run the commands above with specified port.

* Strace of the failing command

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Three ideas:

Easiest to check: Is there anything listening on port 5000 in Windows (check netstat)

Easy to check: Does it work if you try to do it from an elevated bash command prompt (launch bash.exe with administrative privileges)?

Annoying to check: Does it work in the latest insider built?

**Comment by metasoarous** [comment]
I did try several ports, to no avail.

However, it magically started working after I verified that I was able to connect with my Linux machine. So this may be an intermittent thing. Or maybe I was doing something stupid... If the problem comes up again, I'll report back with more information.

**Comment by sunilmut** [comment]
@metasoarous Thanks for trying out WSL and the post! Since the problem seems to be have been resolved, I will go ahead and close this issue out. If it shows up again, do let us know and we can reopen it. Without looking at the traces, the problem you are seeing seems related to the `IPV6_V6ONLY` socket option, which the Anniversary build has (but that issue should not be intermittent). Since then, the issue has been resolved in the [Insider builds](https://blogs.windows.com/blog/tag/windows-insider-program/#EE7zeiQfstFXw7eq.97), which is where the feature updates are being pushed out right now. If the issue reappears, please gather a strace `strace -o <trace_file> -ff <failing_command>` and share out the trace so that we have a better chance at identifying the issue.
