### ISSUE TITLE
Running wsl automatically in every CMD bootstrapping instead of typing "bash" each time?

### ISSUE THREAD

**Issue by Benosika** [Microsoft/BashOnWindows#1513]
Hi, is there a way to Run wsl automatically in every CMD bootstrapping instead of typing "bash" each time?

I don't know that Windows command line as well as I know Bash... In Bash I would go to, say, /etc/bash.bashrc and add this, but is there a similar file I could edit in windows to save typing "bash" each time, so that whenever I open CMD (and/or Powershell) I'll automatically move to WSL Bash?

Thx,

**Comment by fpqc** [comment]
Just open bash.exe directly?

**Comment by zadjii-msft** [comment]
I personally added the Bash on Ubuntu on Windows shortcut to my taskbar, and slid it to the first position, so that `Win+1` automatically opens it. If there's already an instance open, `Win+1` takes you straight to it, while `Win+Shift+1` opens a new instance. That's the best way I've found. And it's actually quicker than `Win+X, C` to open cmd.exe.

Unfortunately I don't think we can get it as an option on the Win+x menu, that's going to stay a Powershell/cmd shortcut.

Otherwise, Win+"bash" (to open the start menu and launch the shortcut) isn't terrible.

**Comment by Benosika** [comment]
Indeed. Locating bash.exe (which I didn't know before) under c/windows/system32 and creating a direct **taskbar shortcut** to it is the solution I needed by all means.

Thanks for that tip.

**Comment by Benosika** [comment]
I now checked this and saw that when I open bash.exe under system32, the Bash prompt is being located in System32 while I would want it to go to my work-user home folder (cd ~) or to the root (/).

This brings me back to the original question of how to batch process (from a .bashrc-like file) a navigation to either cd ~ or /.

**Comment by fpqc** [comment]
`bash.exe ~ [-c "whatever you wanted to do"] ` to do what you are asking..

**Comment by Benosika** [comment]
I published the above comment by mistake. I deleted it.
