### ISSUE TITLE
Cannot bind twice on the same port with different addresses

### ISSUE THREAD

**Issue by marksteward** [Microsoft/BashOnWindows#1549]
On Bash on Ubuntu on Windows 10.0.14393, it's not possible to bind twice on a particular port. This breaks ssh forwarding of multiple services on the same port.

The correct behaviour can be shown by running python in Windows (this also matches cygwin and Linux):

```
C:\Python27>python
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from socket import *
>>> s = socket(AF_INET, SOCK_STREAM)
>>> s.bind(('127.1.1.1', 7821))
>>> s.listen(1)
>>> s2 = socket(AF_INET, SOCK_STREAM)
>>> s2.bind(('127.1.1.2', 7821))
>>> s2.listen(1)
>>> s3 = socket(AF_INET6, SOCK_STREAM)
>>> s3.bind(('fe80::748e:3de5:9073:6ef1', 7821))
>>> s3.listen(1)
>>> s4 = socket(AF_INET, SOCK_STREAM)
>>> s4.bind(('', 7821))
>>> s4.listen(1)
>>> 
```
In another console:
```
C:\>netstat -ano|find "7821"
  TCP    0.0.0.0:7821           0.0.0.0:0              LISTENING       12628
  TCP    127.1.1.1:7821         0.0.0.0:0              LISTENING       12628
  TCP    127.1.1.2:7821         0.0.0.0:0              LISTENING       12628
  TCP    [fe80::748e:3de5:9073:6ef1%8]:7821  [::]:0                 LISTENING       12628
```

However, in WSL:

```
$ python
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from socket import *
>>> s = socket(AF_INET, SOCK_STREAM)
>>> s.bind(('127.1.1.1', 7821))
>>> s.listen(1)
>>> s2 = socket(AF_INET, SOCK_STREAM)
>>> s2.bind(('127.1.1.2', 7821))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
>>> s3 = socket(AF_INET6, SOCK_STREAM)
>>> s3.bind(('fe80::748e:3de5:9073:6ef1', 7821))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
>>> s4 = socket(AF_INET, SOCK_STREAM)
>>> s4.bind(('', 7821))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```
In cmd:
```
C:\>netstat -ano|find "7821"
  TCP    127.1.1.1:7821         0.0.0.0:0              LISTENING       12056
```

The same behaviour happens when using IPv6 with IPV6_V6ONLY.

Could the fix for #395 be ignoring the bind address?

Strace of the failing call (bind, with EADDRINUSE) [here](https://gist.github.com/marksteward/4daf8a49f381212963c6e5cd9d34e9e9#L928).

**Comment by sunilmut** [comment]
@marksteward - Thanks for the post. Are you trying to use the same address (including port) within Windows and WSL? If so, that will not work because of collision. WSL is not a VM based solution and IP addresses are shared between WSL and Windows. For more details around networking in WSL, you can also see [this blog post](https://blogs.msdn.microsoft.com/wsl/2016/11/08/225/).

**Comment by marksteward** [comment]
No, I'm using loopback addresses (and link-local for the IPb6 example for simplicity). Please try the examples given.

**Comment by sunilmut** [comment]
@marksteward - Thanks for the details. Sorry, I didn't pay much attention to the detailed repro steps. Yes, this is a known issue in the Anniversary Update build (14393) and has been long fixed in the Insider build (see screenshot below from the latest Insider build 14986). There has been a lot of enhancement to the WSL networking stack since the Anniversary build, but, these fixes are currently only available in the Insider build. They will also be available in the next general release of Windows (a.k.a `Creator Update`). But, I would recommend trying out the latest Insider build. If you cannot move your main machine to Insider build, you can try it out in a VM.

![image](https://cloud.githubusercontent.com/assets/16765049/21533357/8393a8fe-cd0e-11e6-9646-572b70f92c48.png)

**Comment by marksteward** [comment]
Awesome, thanks! I'll try the VM approach.

**Comment by sunilmut** [comment]
Thanks for trying out WSL and the feedback. Closing it out. If the issue persists, please post and we can reopen.
