### ISSUE TITLE
'bash' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by Skyferia** [Microsoft/BashOnWindows#1598]
***A brief description:**
Failed to compile a simple C code (https://goo.gl/XE5QC6) through the Script package using Atom. 
What I have tried after facing the error:
1. Installing Cygwin
2. Installing bash through Windows Command Prompt after enabling Developer access (type bash -> Enter); Followed this as guide: https://goo.gl/H2N10K

> Error still persist.

***Expected results:**
For the code to compile. 

***Actual results (with terminal output if applicable):**
_'bash' is not recognized as an internal or external command, operable program or batch file._
(See here: https://goo.gl/b3szOj)

***Your Windows build number:**
Windows 10 ver. 1607 Build 14393.576

***Steps / All commands required to reproduce the error from a brand new installation:**
1. Install Atom
2. Install the [atom-beautify 0.29.16] & [script 3.14.0] packages
3. Obtain simple C code (https://goo.gl/cGRV80) and insert text in file in Atom
4. Save file as *.c file
5. Run Script
_(If required: Install Cygwin, then this: https://goo.gl/H2N10K)_

Thanks in advance.

**Comment by benhillis** [comment]
Have you enabled the Windows optional feature?

**Comment by Skyferia** [comment]
Yes @ _Windows Subsystem for Linux (Beta)_
Is/are there anything else that I need to enable?

**Comment by benhillis** [comment]
and running bash.exe from cmd gives you the `'bash' is not recognized as an internal or external command, operable program or batch file.` error?  Is there a bash.exe in C:\Windows\System32?

**Comment by Skyferia** [comment]
Uh no, I can run bash @ cmd. 

That error happens when I tried to compile a C code using Atom; kindly note here: http://i.imgur.com/794yJBA.png

And yes there is a bash.exe @ C:\Windows\System32

**Comment by benhillis** [comment]
Could you please give me some more complete reproduction instructions?  How you're installing Atom, what build script you're using, etc?

**Comment by Skyferia** [comment]
***How you're installing Atom**
1. Downloaded the Windows installer here: https://atom.io/
2. Installed

***what build script you're using**
_script 3.14.0_ 

***etc**
Sorry, could you be specific?

**Comment by benhillis** [comment]
The actual command you are using to compile?

**Comment by Skyferia** [comment]
***The actual command you are using to compile?**
https://goo.gl/cGRV80
or
```
#include <stdio.h>

int main()
{
  int a;

  printf("Enter an integer\n");
  scanf("%d", &a);

  printf("Integer that you have entered is %d\n", a);

  return 0;
}
```

**Comment by fpqc** [comment]
Homie. It's at `C:\Windows\Sysnative\bash.exe`.

It's because bash is not in SysWOW64.

@benhillis you should just symlink bash.exe in SysWOW64.  This is the 8th time I've seen this Q on either here or StackOverflow.

**Comment by Skyferia** [comment]
@fpqc Mine is at C:\Windows\System32\bash.exe though. See for yourself: https://goo.gl/P12SuP
But yes, you're right, it isn't @ SysWOW64. 

I'm still unsure on how symlink works. So did you mean this?
1. Run Command Prompt
2. mklink /J "C:\Windows\System32\bash.exe" C:\Windows\SysWOW64\bash.exe

**Comment by fpqc** [comment]
@skyferia You are calling the script from a 32bit program, so bash.exe lives in C:\Windows\Sysnative. Open a 32bit command prompt and try it.

**Comment by Skyferia** [comment]
@fpqc I don't have Sysnative folder in my C:\Windows\ (see here: https://goo.gl/0h4nN9)
What exactly should I try? If you meant opening Atom and running the code: I tried with the same error as the outcome.

**Comment by fpqc** [comment]
It is a virtual folder. It exists only from the perspective of 32 bit programs.

**Comment by CherryDT** [comment]
@Skyferia:

Since your 64-bit OS needs to be able to run 32-bit programs without confusing them with new paths, some paths are redirected to different folders depending on whether a 32-bit or 64-bit application looks at them. The same applies to some registry keys. Check out the articles about "Registry Redirector" and "File System Redirector" [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa384249(v=vs.85).aspx) to learn more.

Basically, if you open explorer (a 64-bit program), you will see these folders:

`C:\Windows\System32` << your *64-bit* system folder
`C:\Windows\SysWOW64` << your *32-bit* system folder
(Yes, the numbers appear to be exactly the other way round, for reasons too complicated to explain right now.)

*However:* When a 32-bit program, such as Atom, looks at your Windows folder, it will see these folders instead:

`C:\Windows\System32` << your *32-bit* system folder (*!!!*)
`C:\Windows\Sysnative` << your *64-bit* system folder

This ensures that under the path `C:\Windows\System32`, all applications, be it 32 or 64 bit, will find the system files with the correct bitness which fits to the applications themselves - 64-bit applications will find 64-bit files there, file 32-bit applications will find 32-bit files there.

The way to access files with the "other" bitness (32-bit from 64-bit applications and 64-bit from 32-bit applications) is to access the `C:\Windows\SysWOW64` and `C:\Windows\Sysnative` paths, respectively.

Because `bash.exe` exists *only as 64-bit file*, it is located in the `C:\Windows\System32` folder from a 64-bit application's perspective (such as from Explorer), *but in `C:\Windows\Sysnative` from a 32-bit appliaction's perspective (such as from Atom).

Since `C:\Windows\Sysnative` is not in the path by default, you need to tell Atom to specifically look in that folder, by specifying the full path `C:\Windows\Sysnative\bash.exe`.

By the way, you can easily check the different perspectives by trying to explore your Windows folder from 64-bit `cmd.exe` (which you normally get) and also 32-bit `cmd.exe` which you will find in Explorer in `C:\Windows\SysWOW64\cmd.exe`.

**Comment by fpqc** [comment]
Lol @CherryDT Annoying you had to write that magisterial essay.  I saw no benefit to me or him in spelling it out, but I admire your willingness to actually do fhis dirty and unforgiving work.

**Comment by CherryDT** [comment]
@fpqc: Oh, you are right, I was in a Stack Overflow mindset I guess. Sorry if this was considered spam...

**Comment by fpqc** [comment]
@CherryDT I wasn't being sarcastic lol.

**Comment by Skyferia** [comment]
@CherryDT I don't think it's spam since you're answering the question accordingly. Thanks for that and thanks for helping me understand better. I'm not really well-versed in computing, like [tell Atom to specifically look in that folder], I do not know how to do that. 

But seeing as how certain parts of my questions were ignored (such as: Plus you said this is the 8th time, then were the past 7 times with solution? If so, could you kindly link me to any one as **I could not find any**?), I probably have to find out how to do that on my own plus testing through trial and error.

Thanks though to you and @fpqc and @benhillis.

**Comment by fpqc** [comment]
@Skyferia I gave you the answer I gave on SO. Change the path to bash.exe to that sysnative path.  This is because you are calling bash.exe from a 32-bit application (whatever is processing the script you're running, namely the Atom editor or one of its extensions). 

Change the script to call from the sysnative path.  It will definitely work.  Please and stop demanding a further explanation.  @CherryDT has already gone to a lot of trouble to explain it, and it is also well-documented on MSDN (WOW64).

**Comment by CherryDT** [comment]
@Skyferia: About the symlink issue: You are almost right, you just need to omit `/J` because that's for junction points (which is for directories only), and you need to swap the order of the two paths in your command (it's `linkPath targetPath`, unlike Linux' `ln`), i.e. `mklink C:\Windows\SysWOW64\bash.exe C:\Windows\System32\bash.exe` - however I normally prefer not to mess with the system files because this kind of stuff can easily break during an update (or can even break the update), but maybe I'm overcautious there.

**Comment by fpqc** [comment]
@CherryDT Yep that's why I asked the devs to add the symlink maybe.

**Comment by Skyferia** [comment]
[you evidently still have not tried it]
Yes, I have not, as I still am finding out how to direct _Script_'s path. By your tone, I seem to have offended you. I'm so sorry for that.

@CherryDT You're really nice, thanks! Your explanations really help add more to my knowledge. About this: _Wherever it is you are configuring the bash command inside Atom_
Thing is, I do not know the exact 'where'. What I got so far is this (Script's configure): https://goo.gl/AqUf3A
They all are alien to me so I'm finding out based on both cross searching around the net and info you both provided. It's taking time, that was why I didn't respond sooner.

**Comment by fpqc** [comment]
@Skyferia This isn't really a WSL question then.

**Comment by Skyferia** [comment]
Sorry for the late response. 

Thanks for replying @fpqc and guiding me accordingly. Will continue with asking there then.

**Comment by parnekov** [comment]
Write one line - fix it:

**npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"**

source: https://medium.com/@dSebastien/fixing-bash-is-not-recognized-as-an-internal-or-external-command-when-used-within-npm-scripts-on-61614391e417
