### ISSUE TITLE
can not start a .lnk file using interop

### ISSUE THREAD

**Issue by gdh1995** [Microsoft/BashOnWindows#1603]
I've put some .lnk shortcut files into a folder and add it into my system environment variable `PATH`, so that I can use `p.lnk` to open `D:\...\putty.exe` in Win+R diaglog / cmd.exe.

But on newest bash (win 10 insider build 15007), it can not start a .lnk file successfully, and just reports:
> bash: /mnt/d/Git/bin/p.lnk: cannot execute binary file: Exec format error

It seems that an advanced user can use `binfmt_misc` to register magic bytes for .lnk files and write a tool to start it, but I just expect the WSL itself to add such a function.

**Comment by CherryDT** [comment]
`.lnk` is [interpreted by the Windows Shell](http://forensicswiki.org/wiki/LNK#File_Format) (not the Win32 Subsystem itself) - but at the end of the day it's just another file type opened by the corresponding application which knows how to handle it, albeit with some magic applied on top of it which makes the redirectional properties somewhat transparent in the shell.

Would you expect bash to open `.txt` files in Notepad when you "run" them? I guess not.

Since `.lnk` is not an executable file format which can be translated into the action of starting a process directly (it may even be associated with a protocol handled through other means than just plainly running a process, for example, and it wouldn't know how to handle console redirections, etc.), you have to make Windows pass it into `ShellExecute` like any other document you want to open with its associated application. `cmd.exe` will kindly do this for you, though, so you can use `cmd.exe /c` to open your shortcut file.

**Comment by gdh1995** [comment]
Thanks a lot.

What I often use are some gui tools, so I'll try binding a small .exe file to just call ShellEexcute for those .lnk files. cmd.exe is also okay.

**Comment by CherryDT** [comment]
If you just need a way to quickly open your applications from bash, you could just use [bash aliases](https://wiki.ubuntuusers.de/alias/) to the actual EXE files of the applications in question (e.g. `alias notepad='/mnt/c/Windows/System32/notepad.exe' &` - the `&` at the end prevents the shell from blocking while the application is open).
