### ISSUE TITLE
tmux output "stuck" in Build 15007

### ISSUE THREAD

**Issue by laktak** [Microsoft/BashOnWindows#1612]
After upgrading to 15007, the window content inside tmux no longer scrolls upwards when you reach the bottom of the screen. This happens when using the tmux option `set-option -g status-position top`:

- press enter until you reach the bottom
- type ls
- the output of ls is not shown

This issue does not happen with the default status position (bottom) although there are other issues (like the status bar is drawn twice after staring tmux).

**Comment by zadjii-msft** [comment]
@laktak Is this a dupe of #1589?

**Comment by laktak** [comment]
@zadjii-msft well it sounds related but I really can't say if it's the same bug.

As you mentioned in the other issue that it is already fixed - could you provide an update so I can verify that it works with tmux as well?

**Comment by zadjii-msft** [comment]
Note to self: Make sure this is fixed in main when you resolve the other one.

I'm not seeing this repro anymore, and my gut says that it's the same as #1589 just based on the description. Unfortunately I don't have a build from before the fix for #1589 went in that's easily accessible to verify that this issue repros in that old build.

I'll mark this as a dupe, but I'll wait to close it till I know that this no longer repros in Insiders.

**Comment by laktak** [comment]
@zadjii-msft I also noticed that after I open Ranger and Vim (from Ranger) my cursor is gone (==invisible) - is that also the same issue?

**Comment by zadjii-msft** [comment]
@laktak I doubt it. Could you file a new issue for that? I'm not familiar with Ranger so I'll have to investigate more.

**Comment by laktak** [comment]
OK, added #1620

**Comment by laktak** [comment]
This is works in 15019, thanks!
