### ISSUE TITLE
Create process notification about WSL process does not contain valid command line

### ISSUE THREAD

**Issue by bass751** [Microsoft/BashOnWindows#1632]
Description:
According to https://blogs.msdn.microsoft.com/wsl/2016/11/01/wsl-antivirus-and-firewall-compatibility/ it's possible to register a callback for a WSL process creation notification. But there is no valid command line parameter in this callback.

Steps to repro:
1. Register a callback via PsSetCreateProcessNotifyRoutineEx2;
2. Run a WSL process with some argument (f.e. 'sudo bash');
3. Receive a process creation callback about new WSL process
4. Read CreateInfo::CommandLine;

Expected results:
There is full command line in CreateInfo::CommandLine (f.e. 'sudo bash');

Actual results:
There is only image name in CreateInfo::CommandLine (f.e. 'sudo');

Windows build number:
15014

Additional information:
There is no documented way to read command line for existing WSL processes.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  The command line for WSL processes is the standard Linux NULL separated command line.  This MSDN page has more details - https://msdn.microsoft.com/en-us/library/windows/hardware/mt805892(v=vs.85).aspx.

Please let us know if you hit any other issues.

**Comment by therealkenc** [comment]
Good a place as any here to ask if the team might reach out to the sysinternals people and see if support for WSL processes could be added (maybe that's already happened). #373 got opened and closed a long time ago but I haven't seen anyone mention it since. Currently (as of the November release) `procexp64.exe` does not populate process information like the command line arguments.

![procexp-sleep](https://cloud.githubusercontent.com/assets/7049700/22269453/438f1972-e240-11e6-9756-c2cb7e9d32e2.png)

**Comment by sunilmut** [comment]
Good suggestion. Is definitely nice to have @therealkenc. Adding @jackchammons to see if he can help with the reach out.

**Comment by sunilmut** [comment]
Good suggestion, @therealkenc. Is definitely nice to have. Adding @jackchammons to see if he can help with the reach out.

**Comment by bass751** [comment]
Thank you! Yes, It's the valid 'standard Linux NULL separated command line' during EXECVE. But it's not valid during CLONE.
Also I asked how to read command line for existing WSL processes.

**Comment by stehufntdev** [comment]
@bass751, thanks for the follow-up!  I tried the fork\clone case and it looks like the UNICODE_STRING Length member is getting unexpectedly truncated but the full command line is contained by MaximumLength.  I filed a bug a will report back once it is fixed.   Please note that the command line produced during fork\clone is the same as /proc/<pid>/cmdline which can be changed during runtime and the command line during execve is the one being used for the new executable.

Currently there is not a supported method for reading the command line for existing WSL processes.  We are tracking this work, but do not have an ETA.  If you are an AV vendor, please contact Microsoft through your companies representative otherwise please give us feedback on user voice so we can prioritize.

Please let us know if you hit any other issues.

**Comment by stehufntdev** [comment]
Following up on the below a fix for this should be out for insider builds soon.

**Comment by Trass3r** [comment]
I still don't see any WSL process commandlines in ProcessExplorer. Is this supposed to work?
