### ISSUE TITLE
Is it safe to upgrade to ubuntu 16.10

### ISSUE THREAD

**Issue by paladox** [Microsoft/BashOnWindows#1660]
Hi, I'm wondering is it safe to upgrade to 16.10 please or will that cause problems. I am asking since another LTS release won't happen for another year.

**Comment by benhillis** [comment]
We have not been testing 16.10 internally so you will likely run into some issues.

**Comment by paladox** [comment]
Oh, thanks for replying.

**Comment by therealkenc** [comment]
16.10 primarily suffers from #1005 as of this writing.

**Comment by fpqc** [comment]
You will also probably run into #555 if you go to 17.04 because of the strace update.  But yeah, #1005 is the big blocker on a lot of stuff, since they seem to have switched to using it in a _ton_ of GNU devtools.

**Comment by stehufntdev** [comment]
@therealkenc, is the failure on 16.10 the same clone call with CLONE_VM|CLONE_VFORK|SIGCHLD?  If so do you have a strace of an example failure on 16.10 that we can review?

**Comment by therealkenc** [comment]
Correct that's the pattern, not the namespace stuff (which got subsumed in there). 

I believe, but haven't proved conclusively, it's a glibc thing. For example `clang` also gets the same error on 16.10 ([message](https://github.com/Microsoft/BashOnWindows/issues/482#issuecomment-243030842)) but not on 16.04.

I've updated the test case in #1005 so it actually compiles clean with recent `gcc` and included the `strace`. I didn't include the `strace` at the time because it is just:
```
[...blah blah blah]
clone(child_stack=0xacef60, flags=CLONE_VM|CLONE_VFORK|SIGCHLD) = -1 EINVAL (Invalid argument)
[...blah blah, not working]
```
You don't need to install 16.10 to run the test case because I'm deliberately calling `clone` directly.

**Comment by stehufntdev** [comment]
Thanks for the follow-up!  I was able to get a repro of this on 16.10 and updated the code to handle clone vfork (i.e. CLONE_VM|CLONE_VFORK|SIGCHLD) the same as vfork.  As part of this change we realized we have some differences in vfork and those will be patched up later.

**Comment by paladox** [comment]
@stehufntdev thank you :)

**Comment by therealkenc** [comment]
I tried Yakkety (16.10) today and all appears well so far on 15046. The `apt-get dist-upgrade` with an updated `sources.list` was utterly painless and didn't spew so much as a warning (that I noticed anyway). I thought `strace` might break because of #555 (also reported in #1578), but the `strace` version shipped with Yakkety is 4.12, and `strace` won't fail on #555 until version 4.15. I'll post again if I come across anything glaring, but I think you can put a fork in this issue because it looks done.

**Comment by stehufntdev** [comment]
@therealkenc thanks for the update!  Closing this out as fixed for insider builds.

**Comment by therealkenc** [comment]
I suppose I should follow up on this one since it was marked as fixedininsiderbuilds at my behest; which, it technically was at the time due to #1005 being addressed. Unfortunately as of 16176, upgrading to Ubuntu 16.10 is "not safe" per issue title, due to #1878 and friends. I don't think it is necessary worth re-opening this issue (we have plenty), but it bears clarification in case anyone lands here in a tracker search.
