### ISSUE TITLE
Restrict infinity scroll

### ISSUE THREAD

**Issue by vinodMS** [Microsoft/BashOnWindows#1669]
* Scroll down on bash windows using a mouse or trackpad

* Expect the scroll to stop when it hits the last line

* Scrolls all the way to the bottom and shows a blank screen.

* 15025.1000

* Open bash -> scroll down

**Comment by aseering** [comment]
For what it's worth, this has been true for as long as I can remember (well prior to Windows 10).

+1 anyway, though :-)

**Comment by zadjii-msft** [comment]
So this is actually by design - the Windows console doesn't operate with a "scrollback" like in linux terminals, instead we have a "screen buffer". When you open a new console, the output starts at the top on the buffer and moves down through it. So the window is only something like 80x32, but the buffer will be something like 80x9001. You can see these sizes by going to Properties... Layout. 

I'd doubt that we'd ever add a "scrollback mode" to the console, purely because the existing console API would have no idea what to do with that. It would require a lot of special casing, I'm sure. That being said, I'm pretty sure it's already on the backlog :P.

**Comment by aseering** [comment]
Perhaps you could have Linux output appear starting at the bottom of the buffer, rather than the top?  Minus one windowful of lines.  That's to first order the same user experience as what, for example, gnome-terminal does...
