### ISSUE TITLE
Bash Tab Completion issues

### ISSUE THREAD

**Issue by bitcrazed** [Microsoft/BashOnWindows#1670]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
Tab completion appears to be favoring returning searches from the full path but not the local directory.

* Steps / All commands required to reproduce the error from a brand new installation 
Enter the following Bash commands:

```
$ mkdir temp
$ cd temp
$ echo hello > hello.txt
$ echo world > world.txt
$ ls
1.txt  hello.txt  world.txt
$ h <hit tab twice>
```

* Expected results

```
hello.txt
```

* Actual results (with terminal output if applicable)
List of all the Windows files on the path (which includes the Windows path) that begin with 'h'

```
h2ph            hcproviders.dll    help.exe        hhsetup.dll     hnetcfg.mof     hotplug.dll  ...
```

* Strace of the failing command
N/A

* Your Windows build number
15027

* Required packages and commands to install
N/A

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hey @bitcrazed -- isn't this behavior exactly as expected?  Twofold:  (1) bash is expecting a command; assuming this is VolFS, "hello.txt" is not executable (nor is it a directory that might contain an executable command).  And (2) Linux, unlike DOS / cmd.exe, doesn't let you invoke executables without specifying a path.  You must at least specify a relative path, such as `./hello.sh`.  This is (I'm told) a security / defensive coding thing, to make it slightly harder to hack processes to cause them to execute a script that they just wrote to a temp file.

You can make bash's behavior more Windows-ey by adding `.` to `$PATH`.  That fixes (2), but not (1) (unless you're on DrvFS because DrvFS still flags all files as executable).

Anyway, the following works for me, as I would expect as a Linux user:

```
$ mkdir temp
$ cd temp
$ echo hello > hello.txt
$ echo world > world.txt
$ ls
1.txt  hello.txt  world.txt
$ cat h <hit tab once -- autocompletes to "cat hello.txt">
```

**Comment by aseering** [comment]
Note that bash's autocompletion is actually relatively powerful -- it's very context-aware; it can be configured to be aware of the command signatures of particular commands and to autocomplete for valid inputs for specific arguments (if those arguments are particular file types or even not files at all).

Documentation is here:
https://www.gnu.org/software/bash/manual/html_node/Programmable-Completion-Builtins.html

Relevant configuration files on Ubuntu:
```
/etc/bash_completion
/etc/bash_completion.d/*
```

**Comment by therealkenc** [comment]
Yep; same behavior on Ubuntu or any *nix. Used to be common back in the day to have '.' at the front of your path. Simple `export PATH=.:$PATH` will put $PWD at the front of the line for tab completion.
