### ISSUE TITLE
No persistence of redis is working in windows but not in linux.I have disabled all save options and appendfsync to 'no' ?

### ISSUE THREAD

**Issue by lpatil44** [Microsoft/BashOnWindows#1672]

**Comment by aseering** [comment]
Hi @lpatil44 , thanks for posting!  Could you please fill out the issue template?  Specifically, for starters, please include a step-by-step sequence of the exact commands you are using to start Redis, load data, and stop Redis.  (This is what people call a "reproducer".)

**Comment by skjadhav282** [comment]
I have installed Redis in linux. I want to use it with no persistance at all. I have disabled all Save and have set appendonly & appendfsync to NO. This configuration helps in windows. but in linux still it is persisting the values.Please help me with this issue.

**Comment by aseering** [comment]
@lpatil44 @skjadhav282 -- it sounds like you have a basic usage question about WSL.  You may want to ask your question on a forum like [StackOverflow](http://stackoverflow.com/questions/tagged/wsl), rather than here.

This bug-tracker is for users who know that they have found a specific bug in WSL's kernel emulation, and who understand and are able to fill out the questions on the issue template.  It sounds like your concern is not syscall compatibility or missing virtual files (which is the type of thing that people here are going to be the most skilled at helping with); you just want Redis to work :-)

Two observations for you, though:

* Redis for WSL is not supposed to behave like Redis for Windows.  It is supposed to behave (mostly) like Redis for Linux.
* WSL applications don't need a WSL version of Redis.  They can use the Windows version of Redis.  Just configure them to connect to `localhost`.  So, if Windows Redis works for you, just use it :-)
