### ISSUE TITLE
Bash locks up, requires reboot

### ISSUE THREAD

**Issue by markohb** [Microsoft/BashOnWindows#1680]
I'm running Version 1607 and I seem to hit this issue multiple times a day, where one of my Bash terminals will lock up, it usually happens when trying to do something network related (SSH etc.)

This causes the terminal I am currently in and every other terminal to lock up, I just get the blanking underscore and that's it.

Closing terminals, or killing off the Bash process doesn't fix the issue, the only way I have found to get back into a Bash terminal is to do a full restart.

**Comment by markohb** [comment]
I am now getting Error: 0x80080005, but I can see this has been covered in various other issues, so I will close this one to avoid duplicates.

**Comment by aseering** [comment]
Hi @markohb -- could you let us know the "Build Number" that you're running?  It's a 5-digit number starting with either `14` or `15`.

**Comment by markohb** [comment]
Hi @aseering The build number is 14393, do you think is a new issue? Should I reopen the issue? I had closed it because I noticed a lot of previous issues with Error: 0x80080005 so didn't want to clog up the issues log with a duplicate issue.

**Comment by aseering** [comment]
Yeah, a *lot* of things have been fixed since build 14393.  (That's the latest official stable build, but it's 6 months old, and WSL has been undergoing very rapid development on the [Insider](http://insider.windows.com) Fast and Slow tracks.)  If you're willing to try out an Insider build (either directly on your machine or in a [VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)), it'd be interesting to know if that fixes the issue for you.

I ask because there's a similar (but not identical) hang that was introduced recently, in build 15025 (I think?), tracked by #1661 .
