### ISSUE TITLE
Git check status file different between Window and Linux

### ISSUE THREAD

**Issue by at-kietva** [Microsoft/BashOnWindows#173]
So, I'm using git terminal of Window also git bash on Ubuntu.
I have problem when modify file in Android Studio. 
Android Studio : using git on Window at File/Settings/  -> search terminal and change to `bash` like bellow : 
![1](https://cloud.githubusercontent.com/assets/16131706/14487882/547dd6ca-018f-11e6-9110-e61ab6f20da4.png)

Also window path for git on Window : 
![2](https://cloud.githubusercontent.com/assets/16131706/14487900/76bd92ca-018f-11e6-84fc-2c2a91d0926c.png)

So when i change my code, and push to Github by git in Windows, git in Linux not update pushed status. 

My question is : what different checking status file bettween file in Linux and file in Windows ?

**Comment by sv3tli0** [comment]
If you are talking about 1 project (say it Folder where you have .git) .

The git local branches, the current branch, all the history and etc.. are inside the project/.git folder so it doesn't matter what git client windows/ubuntu is trying to access it.

Its important that your GIT Windows ssh-key and Ubuntu ssh-key are added to your github account. So that they have absolutely the same permissions on your project.

**Comment by benhillis** [comment]
Closing this out as there has not been activity on this thread for some time.  Please reopen if you continue to have issues.  Thanks!
