### ISSUE TITLE
WSL doesn't generate core dumps on abort()

### ISSUE THREAD

**Issue by aseering** [Microsoft/BashOnWindows#1754]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description

I feel like this ticket must already exist somewhere, but I'm failing to find it...  I discovered this while writing up another ticket, which I'll post shortly.

Programs that should dump core, don't dump core.

Consider the following trivial example program (as `tmp.c`):

```
#include <stdlib.h>

int main()
{
  abort();
}
```

* Expected results

```
$ gcc tmp.c
$ ulimit -c unlimited
$ ./a.out
Aborted (core dumped)
$ ls core*
(Nothing found)
```

* Actual results (with terminal output if applicable)

```
$ gcc tmp.c
$ ulimit -c unlimited
$ ./a.out
Aborted (core dumped)
$ ls core*
core     # <- Core file produced
```

* Your Windows build number

15046

* Steps / All commands required to reproduce the error from a brand new installation 

See above.

* Strace of the failing command

```
$ strace ./a.out
(...)
tgkill(5522, 5522, SIGABRT)             = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=5522, si_uid=1000} ---
+++ killed by SIGABRT (core dumped) +++
Aborted (core dumped)
```

* Required packages and commands to install

```
sudo apt install build-essential
```

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
I don't have a specific use case for core dumps right at the moment.  I'm sure y'all are aware of their utility in general, though -- they're extremely useful for debugging issues where, for any of a variety of reasons, I as a dev can't contrive to be sitting there watching in gdb when/where some crash happens in a binary compiled from my code.

**Comment by therealkenc** [comment]
#1262, #1468

**Comment by aseering** [comment]
Yep.  Dupe.  Thanks @therealkenc !

**Comment by danielbaker99** [comment]
**to get a core dump on wsl2 ubuntu 20.04.**
I installed the desktop via this link 
https://medium.com/geekculture/how-to-install-the-ubuntu-desktop-with-the-graphical-user-interface-in-wsl2-71f4b78431a4

booted into the desktop and started the terminal
ran these commands
ulimit -c unlimited
sudo service apport stop
./tutorial
the file 'core' appears in the current directory; the reason why it works from the desktop is that the system is booted with systemd instead of the wsl2 init which allows stopping the service apport.  I could not figure out a way to stop the apport service from a normal wsl2 Ubuntu terminal.
