### ISSUE TITLE
can't ssh from WSL to ubuntu VM running on Azure

### ISSUE THREAD

**Issue by jahongirman** [Microsoft/BashOnWindows#1781]
For some reason I could not ssh from WSL to Ubuntu server running on Azure. At the same time, I can ssh to the the same Ubuntu server from the same computer using PuTTY. 

So, does ssh work on WSL?
If yes, what could be wrong with my settings?

**Comment by marshuang** [comment]
1. sudo nano /etc/ssh/sshd_config
2. 
UsePrivilegeSeparation no
PermitRootLogin no
AllowUsers yourusername 
PasswordAuthentication  yes
3. sudo service ssh –full-restart
4. disable Windows 10 SSH Server Broker Services

**Comment by aseering** [comment]
For what it's worth, I use the ssh client from within WSL almost on a daily basis -- it definitely works in most cases.

When you say that you could not ssh, could you be more precise about what's not working?  Could yountry running ssh with the `-vvv` flag (enables verbose debugging output)?  Also, did you set up your Azure ssh keys in WSL, with correct file permissions?  It won't automatically use keys that you set up for putty.

**Comment by sunilmut** [comment]
Thanks @aseering for chiming in with useful troubleshooting tips. 

@jahongirman - something else also that you can try is SSH'ing into your Ubuntu server on Azure through a Ubuntu machine. If that works, and the *same* (as @aseering mentions about keys) setup does not work on WSL, we would like to know. Otherwise, it's most likely a setup issue.

**Comment by jahongirman** [comment]
@aseering and @sunilmut  thanks for your troubleshooting tips.

I've already deleted that VM from Azure, and now I tried to ssh to another VM and it works. 
I think @sunilmut is right, it was a setup issue.
