### ISSUE TITLE
nofile for root 

### ISSUE THREAD

**Issue by lscgzwd** [Microsoft/BashOnWindows#1810]
I have set nofile in /etc/security/limit.conf.

```
* soft nofile 262140
* hard nofile 262140
```

but for root user.
ulimit -a also show me 2048.

**Comment by aseering** [comment]
Hi @lscgzwd , thanks for posting!  Unfortunately, WSL does not yet respect `/etc/security/limits.conf`.  This is, I think, not obvious from this bugtracker; but I believe it is one of the many things that don't work because WSL doesn't yet invoke `/bin/login` to start a shell.  A bunch of other tickets in the bugtracker reference this limitation.

You can manually raise some limits using the `ulimit` command.  Other limits are not supported yet.  Which limits are supported depends on which build of Windows you are using (stable or a more-recent [Insider build](https://insider.windows.com)).

**Comment by lscgzwd** [comment]
Ok, thanks for your response. Maybe I can change it by add to bashrc

**Comment by benhillis** [comment]
Marking as a duplicate of #1576.
