### ISSUE TITLE
Creating files with utf8-encoded Unicode names results in files that can't be deleted from Windows

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/BashOnWindows#1820]
Creating files with names outside the ANSI range of the Unicode character set with UTF-8 encoding causes the file to be correctly created (and shown), but the resulting file cannot be deleted from within Windows Explorer.

Here is a sample program that, when compiled and run under WSL, creates one such file:

````
#include <string>
#include <ostream>

int main()
{
        uint8_t rawBytes[] = { 0xD8, 0xA3, 0xD9, 0x86, 0xD8, 0xA7, 0x20, 0xD9, 0x82, 0xD8, 0xA7, 0xD8, 0xAF, 0xD8, 0xB1, 0x20, 0xD8, 0xB9, 0xD9, 0x84, 0xD9, 0x89, 0x20, 0xD8, 0xA3, 0xD9, 0x83, 0xD9, 0x84, 0x20, 0xD8, 0xA7, 0xD9, 0x84, 0xD8, 0xB2, 0xD8, 0xAC, 0xD8, 0xA7, 0xD8, 0xAC, 0x20, 0xD9, 0x88, 0x20, 0xD9, 0x87, 0xD8, 0xB0, 0xD8, 0xA7, 0x20, 0xD9, 0x84, 0xD8, 0xA7, 0x20, 0xD9, 0x8A, 0xD8, 0xA4, 0xD9, 0x84, 0xD9, 0x85, 0xD9, 0x86, 0xD9, 0x8A, 0x2E, 0x00 };
        std::string testData = (const char *)(rawBytes);
        std::fopen(testData.c_str(), "w");

    return 0;
}
````

This results in a file named "أنا قادر على أكل الزجاج و هذا لا يؤلمني." to appear in the current directory. This file's name is correctly displayed in Explorer (so there is correct codepage conversion taking place), but cannot be deleted as the following error message is displayed:

![image](https://cloud.githubusercontent.com/assets/606923/24328324/1c1c24b6-11ac-11e7-8e03-f8141f2dc840.png)

**Comment by benhillis** [comment]
This is a generic issue in the Win32 path API's and not specific to WSL.  You don't even need to use a Unicode character, you can do this by just creating a file that ends in a '.' character.

**Comment by therealkenc** [comment]
Great pro-tip. From [MSDN](https://support.microsoft.com/en-us/help/320081/you-cannot-delete-a-file-or-a-folder-on-an-ntfs-file-system-volume):

You may not be able to delete a file if the file name includes an invalid name (for example, the file name has a trailing space or a trailing period or the file name is made up of a space only). To resolve this issue, use a tool that uses the appropriate internal syntax to delete the file. You can use the "\\?\" syntax with some tools to operate on these files, for example:

&nbsp;&nbsp;&nbsp;&nbsp;del "\\?\c:\path_to_file_that contains a trailing space.txt "

The cause of this issue is similar to Cause 4. However, if you use typical Win32 syntax to open a file that has trailing spaces or trailing periods in its name, the trailing spaces or periods are stripped before the actual file is opened. Therefore, if you have two files in the same folder named "AFile.txt" and "AFile.txt " (note the space after the file name), if you try to open the second file by using standard Win32 calls, you open the first file instead. Similarly, if you have a file whose name is just " " (a space character) and you try to open it by using standard Win32 calls, you open the file's parent folder instead. In this situation, if you try to change security settings on these files, you either may not be able to do this or you may unexpectedly change the settings on different files. If this behavior occurs, you may think that you have permission to a file that actually has a restrictive ACL.

**Comment by benhillis** [comment]
"by design" meaning this is underlying NT behavior.  I still feel this is a bug and I have a thread ongoing with the Win32 folks about path canonicalization.  As you can probably imagine there's about 20 years of legacy design decisions so it's a touchy subject.

**Comment by mqudsi** [comment]
Creating a file in explorer.exe ending in `!` does not cause a problem in deleting it.. it's only when the file is created via the Linux API that an issue occurs. The odd thing is that it's an ASCII character (!), properly "normalized" as `0x2E` that is causing the problem. Any ideas why?

**Comment by benhillis** [comment]
@mqudsi - I'm not seeing the behavior you are describing.  If I create a file from WSL that ends with '!' I am able to delete it from explorer without issue.

**Comment by mqudsi** [comment]
@benhillis with the code sample I posted in the original file, if I remove 0x2E from the UTF-8 encoded filename buffer and run the code, the resulting file can be deleted without a problem. But with the 0x2E at the end, the resulting file cannot be deleted from within explorer.exe

**Comment by mqudsi** [comment]
@benhillis nevermind, my apologies! I got my ASCII confused and thought 0x2E was an exclamation mark, not a period.
