### ISSUE TITLE
Deleting/Moving Big Directorys end in endless Running.

### ISSUE THREAD

**Issue by Huskynarr** [Microsoft/BashOnWindows#1843]
If I move, delete or rename a Directory with a lot of files and subdirectories the WSL commandline is stucking and the command is endless running. I need to restart the full host machine to work with WSL again.

I use latest Windows 10 release Version (not Insider).

**Comment by fpqc** [comment]
no point filing this. The new release comes out next week. Please retest on 1703 and let us know.

**Comment by aseering** [comment]
@fpqc -- there will be people running the Anniversary release for a long time to come.  (I mean, there are people still running Windows XP ;-) )  Even if something is fixed in Creators, I see value in having a ticket that says it's fixed in Creators.

@Huskynarr -- thanks for posting!  @fpqc does make a good point, though, that the Windows 10 Creators update is about to be released, and that update contains a *huge* number of bugfixes and improvements for WSL.  I don't remember seeing this exact issue, but a number of hangs and infinite loops (for example, #650 ) have been fixed.  So it would be really helpful if you could upgrade (when the update comes out) and post whether that fixes your issue.

**Comment by mateusmedeiros** [comment]
@Huskynarr Are you sure it's stuck? When I move or delete the `node_modules` directory of my node projects, it usually takes quite some time, but it eventually finishes the operation.

**Comment by Huskynarr** [comment]
@mateusmedeiros  If i did it with Windows it need Seconds or.. if i must really wait minutes. SDD's. ;) Under WSL il be waiting for 10 Minutes and more. Tested with different Systems.

@fpqc Il be waiting for the Update. :)

**Comment by benhillis** [comment]
@Huskynarr - Could please retry after upgrading to Creators Update and reopen if the issue still occurs?

**Comment by mateusmedeiros** [comment]
@Huskynarr Sorry, I was not trying to say that you're not experiencing an issue, nor trying to undermine a specific kind of issue, just trying to identify it.

Disk IO on WSL is still a little slow, much better than in build 14393, but far from perfect. If that is the problem, it is, of course, a real issue, but one that the WSL team is already aware. Truly endless running when trying to delete a big directory though would be a new issue.
