### ISSUE TITLE
Ampersand doesn't correctly run command in background

### ISSUE THREAD

**Issue by mufunyo** [Microsoft/BashOnWindows#1849]
Run a command in the background like so:
xeyes &
Then close the terminal that launched the background process.

Expected result: process should keep running in the background.

Actual result: process is killed along with the terminal.

**Comment by therealkenc** [comment]
#1511 #1263 #1007 #834.

**Comment by poizan42** [comment]
Well, I don't think you should expect it not to close without nohup, setsid or disown. Of course neither works at the moment because everything is shut down when you close the terminal.

But I would suggest you vote on [this UserVoice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13653522-consider-enabling-cron-jobs-daemons-and-backgroun) to let the team know that you want them to prioritize supporting background processes.

**Comment by benhillis** [comment]
Agreed with @therealkenc, already many issues on this subject so closing this as a duplicate.
