### ISSUE TITLE
Bad Pool Caller - BSOD

### ISSUE THREAD

**Issue by SageEx** [Microsoft/BashOnWindows#1872]
Whenever I do a disk intensive operation like installing some packages or use ``git`` to clone a repository, this error comes up. The BSOD shows up and the machine reboots.

This happens in both the WSL with ``bash on windows`` and ``archlinux subsystem for windows``.

*  Windows build number - Version 1703 (OS Build 15063.14)

* Any memory intensive operation like git cloning a dotfiles repository or downloading packages throws this error. 

Anyway to handle this ?

**Comment by SageEx** [comment]
I tried installing vim-plugins with ``vim-plug``, the crash appeared when cloning multiple git repositories.

Any clue how to debug this ?

**Comment by aseering** [comment]
BSOD's can be security issues, so, as this repo's README says, please don't report them here.  Instead, please find the minidump associated with the BSOD in `C:\Windows\minidump` and e-mail it to "secure@microsoft.com" attn: @benhillis , or anyone else on the WSL team.

If you do want to debug further yourself, the minidump would be a good place to start.  There are lots of tools online for working with minidumps.  I once had a repeatable BSOD (but not specific to WSL; just specific to high disk activity); the minidump fingered the driver for my disk subsystem, and upgrading to the latest driver direct from the manufacturer (the Windows Update version was out-of-date) fixed the issue.  Of course, it's only that simple if the bug is in a driver and has been fixed :-)

**Comment by benhillis** [comment]
@SageEx - Please send any memory dumps if you have them.

**Comment by SageEx** [comment]
Hi @benhillis, I'm currently away from my laptop for 2 weeks. I'll cause the BSOD and get you the dump in 2 weeks.
I'll be closing this issue for now. I'll open it again once I get the dump.

**Comment by kittel** [comment]
Hello,
I have a similar issue with Debian Buster in WSL. I can provide minidump if needed.
Could you reopen this issue or should I create a new one.

Note, that I also run a Debian stretch within Legacy WSL on the same host without any problems.

**Comment by benhillis** [comment]
@kittel please send the dump to secure@microsoft.com and reference this issue.
