### ISSUE TITLE
Xlib: missing extension "XFree86-VidModeExtension" after upgdate to 16.04

### ISSUE THREAD

**Issue by asRIA** [Microsoft/BashOnWindows#1885]
Please use the following bug reporting template to help produce actionable and reproducible issues. Please try to ensure that the reproduction is minimal so that the team can go through more bugs!

* A brief description
After installing an update to Windows 10 Creators Update I've started to have a problems with running one project due: 
`Xlib:  extension "XFree86-VidModeExtension" missing on display ":0.0".`. This project was running nicely on previous WSL based on 14.04. 
Before installing an update I removed my Linux files by command `lxrun /uninstall /full`. 
Then after reinstall WSL I installed required packages for my project: `libx11-dev libglu1-mesa-dev libxxf86vm-dev` and recompiled my project.
As a sanity check, I verified if gvim and firefox work with WSL, and they do. 

In order to fix this problem I've tried as follow: 
```
piotr@DZIK:/$ cat /etc/X11/xorg.conf
Section "Module"
        Load "extmod"
EndSection
```
But it didn't help. 

My project uses: `XF86VidModeQueryVersion`, `XF86VidModeGetAllModeLines`

* Expected results
Application what uses `VidModeExtension` should work like with 14.04

* Actual results (with terminal output if applicable)

* Your Windows build number
1703

* Steps / All commands required to reproduce the error from a brand new installation 
- unfortunately I haven't seen any publicly available application what uses it. 

* Strace of the failing command
[strace.txt](https://github.com/Microsoft/BashOnWindows/files/915063/strace.txt)

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by aseering** [comment]
Hi @asRIA -- so, WSL by itself is text-mode only.  While it's true that the functions that you listed above aren't implemented in stock WSL, that's because WSL itself doesn't implement any X functions :-)

My guess is that you installed a third-party X server such as VcXsrv or Xming a while ago, and configured WSL to use it to handle X Windows calls.  That third-party server is what needs to support these features.  Note that these third-party X servers are Windows applications; you'll have to find and edit their config files on the Windows side.

**Comment by asRIA** [comment]
Thank you @aseering for a good answer for it. You were right :)
