### ISSUE TITLE
Quick and Dirty Multi Platform Testing | GUI

### ISSUE THREAD

**Issue by sirinath** [Microsoft/BashOnWindows#19]
This can be a basis of quick multi platform testing if you support many platforms (https://github.com/Microsoft/BashOnWindows/issues/1) when developing on Windows. Since many of the current system are GUI based it would be great if you can support windowing also.

**Comment by russalex** [comment]
Running GUI based apps is something we get quite a bit.  We have a very similar user voice [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13250499-support-for-x-server-running-in-windows-on-the-sam).

Closing this out since there has not been any traffic for 22 days.
