### ISSUE TITLE
Licensing Issues

### ISSUE THREAD

**Issue by MajickTek** [Microsoft/BashOnWindows#1931]
* A brief description
The Linux kernel is under the GPL. All of the GNU tools are under the GPL/similar licenses. Ubuntu, of which this is based, is also open source. And this is not. I am disappointed in you. You have not followed ANY of the licenses.
* Expected results
Microsoft follows rules
* Actual results (with terminal output if applicable)
Microsoft doesn't follow rules
* Your Windows build number
I am on Android 7.0, but I have Windows 10 Anniversary Update.
* Steps / All commands required to reproduce the error from a brand new installation 
Follow the licenses and add code to the repository. GitHub is a code repository, not a place to submit issues. Use your bug reporting services instead.
* trace of the failing command
Error: License issues
* Required packages and commands to install
sudo apt-get upgrade

**Comment by MajickTek** [comment]
Oh yeah, and I use an iMac with no Microsoft products as my main PC now. At least apple releases the necessary source code for macOS's kernel.

https://opensource.apple.com/release/macos-10124.html - macOS 10.12.4 open source programs/kernel

https://opensource.apple.com/release/developer-tools-821.html - Xcode developer tools 8.2.1 source code

https://opensource.apple.com/release/ios-1021.html - iOS 10.2.1 open source tools/libraries

**Comment by MikeGitb** [comment]
The maintainers can give you a definitive answer on that, but the afaik the WSL doesn't use any part of the linux kernel - it is an independent implementation of the API/ABI provided by it. 

Ubuntu and all the tools running on it come directly from canonical / the ubuntu repositories and I'm pretty sure you can get the soure code for all of them.
So there is no copyright / license violation going on.

That aside - wasn't there talk about eventually open sourcing the WSL code at least partially?

**Comment by aseering** [comment]
+1 -- the WSL *kernel* is a reimplementation from scratch.  It is not using any Linux source code; therefore it does not need to license Linux; therefore it is not constrained by that license.  (Fair warning: I am not a lawyer.)

There's a long history, both in enterprise and within the open-source community itself, of reimplementing software from scratch in order to avoid some clause in the old implementation's license.  Clang, the compiler used by Xcode, and its companion libc and libc++, are classic examples:  gcc, the most-commonly-used compiler on Linux, is licensed under the GPL, and its standard libraries are licensed under the LGPL.  It would be in violation of those licenses to use those libraries in closed-source applications.  (Dynamic linking under the LGPL is probably ok but is a grey area; the consensus seems to be that static linking simply isn't allowed; debugging tools built based on gcc would have to be fully open-source.)  Much of Apple's own software is closed-source, and Apple works extensively with companies that develop closed-source software, so this was unacceptable.  Early versions of Xcode did use gcc.  As a result, Apple arguably should have (but never did) released all of Xcode's source code.  Instead, they poured a pile of resources into developing clang into a viable alternative compiler, and releasing it under a much-more permissive license.  As a result, as you can see, they don't actually release most of Xcode's source code.  (Look more carefully at the link above; far from open-sourcing all of Xcode, Apple is only releasing a few tools that are themselves already open-sourced.)

It's true that clang itself is open-source.  But it uses a license (BSD) that is mutually incompatible with the GPL -- it would be in violation of gcc's license for clang to use gcc's source code precisely because clang's license allows building clang and its standard libraries into closed-source tools and gcc's does not.  Basically, clang isn't itself closed-source but it supports closed-source in a way that gcc very specifically disallows.  Regardless, the law doesn't care about intent, nor about the new license:  It's a reimplementation; Apple can do whatever they want.  Similarly, WSL is a reimplementation; Microsoft can do whatever it wants.

(Also, don't get me started about Apple's kernel sources.  Mac OS X's kernel is not based on Linux at all; it's a hybrid of NeXT and I think FreeBSD?  So it's not bound by the GPL, and It's not immediately clear to me whether they need to release its source at all.  And sometimes they don't bother, at least [not promptly](https://bugs.kde.org/show_bug.cgi?id=365327).)

The WSL *userspace*, on the other hand, is absolutely covered by a multitude of different open-source licenses.  But the whole point of WSL is that these programs are not only the same source code but the exact same binaries and binary packages as are used by Ubuntu Linux.  (If I recall correctly, they are simply using Ubuntu's public [cloud image](https://cloud-images.ubuntu.com/)?)  As such, you can download the source code here:  http://archive.ubuntu.com/ubuntu/

Regarding submitting issues:  Because many of WSL's userspace applications are, as you say, open-source, it's convenient for developers of those apps to be able to cross-reference tickets in the application's repository and tickets in the WSL team's repository.  In that sense, I for one really appreciate that the WSL team has put their bugtracker on github; it makes this much easier.

@MajickTek -- while your request is not clearly based in common US licensing law, it seems to me that what you're saying is that you want WSL to be open-source, and that it feels wrong to you that it's closed-source.  That, I would agree with.  And so do other people -- that part of your request is a dupe; it's literally ticket #1 in this bugtracker.

**Comment by fpqc** [comment]
@MikeGitb If  the lxss kernel-mode driver API is ever made public, it will probably be added to the WKMDF and therefore have some of its code open sourced.  As for the main pico driver code, I don't think so.  

I mean, given MS's ownership and the closed source nature of most of the Windows libraries, I do wonder if it would ever make sense for MS to opensource the entire NT Kernel including WSL (Alex Ionescu maintains that the best documentation for the NT Kernel around today is still the ReactOS project, despite being based on a much older version of the kernel).

**Comment by MajickTek** [comment]
@MikeGitb you said most of Apple's programs are closed source. This is most definitely not true. 

opensource.apple.com

**Comment by MikeGitb** [comment]
@MajickTek: You seem to confuse me with someone else.

**Comment by MajickTek** [comment]
@MikeGitb I meant to say @aseering. Sorry ;)

**Comment by aseering** [comment]
Ah, hi -- @MajickTek -- One example:  If XCode is open-source, then I can download all of those files, run some series of commands, and get my own XCode.app.  You seem very confident that it is open-source.  So:  What are the commands that I run to get my own XCode.app?

**Comment by MajickTek** [comment]
@aseering I didn't mean Xcode.app, I meant it's tools. That is:

cctools

clang

the developer commands (developer_cmds)

gnumake/gcc_select/gperf/gm4

ld

subversion

etc

**Comment by aseering** [comment]
@MajickTek -- so you're agreeing that Apple does keep a lot of its own software (for example, XCode) as closed-source?  Apple makes a lot of software (iTunes, Pages, Final Cut Pro, Safari, iOS, and so on; it's a long list) and most of it is in fact closed-source.

As for the list above, some of those are Apple's code, and I applaud them for releasing that code.  There are some really substantial open-source releases under the OS (kernel) section, which is great.  Though, Apple has been rather slow to publish updates to some of that code lately, which has been frustrating to me personally.  Also, most of the apps listed above aren't even Apple's apps at all.  Subversion is managed by the Apache foundation.  gnumake et al are GNU projects.  clang did receive a lot of support from Apple a while back, but it's owned and hosted by UIUC.  In those cases, Apple isn't really releasing their own code; they're just re-releasing someone else's code :-)

So Apple does release a few things.  So does Microsoft:  https://opensource.microsoft.com/  There's some legit software there:  For example, you can get the source code for their [.NET runtime](https://github.com/dotnet/coreclr) and [core libraries](https://github.com/dotnet/corefx), which opens the door to turning a lot of Windows applications into cross-platform applications.  Or you can get Microsoft Edge's [JavaScript engine](https://github.com/Microsoft/ChakraCore).  Visual Studio, alas, remains firmly closed-source; though [Visual Studio Code](https://github.com/Microsoft/vscode)'s source and bugtracker are both available.  They do publish code for a handful of third-party apps as well; for example, [git](https://github.com/Microsoft/git) and [OpenSSH](https://github.com/PowerShell/Win32-OpenSSH).

Of course, like Apple, Microsoft develops a large body of closed-source software as well.  Bot have their strengths and their weaknesses.

**Comment by MajickTek** [comment]
This is becoming a flame-war now. It was an interesting one, but now I will close the discussion. Problem solved ;)
