### ISSUE TITLE
Can't install PHP and PHPmyadmin preliminaries

### ISSUE THREAD

**Issue by Benosika** [Microsoft/BashOnWindows#1943]
`apt-get install php-zip php-curl php-xml php-gd php7.0-mcrypt php7.0-mbstring -y`

Each one brings "Unable to locate package".

---

As far as I know, these packages (along with systemctl) are basically the only things I need to raise up a dedicated server on WSL.

**Comment by mksm** [comment]
Have you tried running `apt-get update` before that?

**Comment by Benosika** [comment]
Yes. This is after `apt-get update && apt-get upgrade`.

**Comment by therealkenc** [comment]
Works here, 14 packages in total installed. Check your `/etc/apt/sources.list`, for lack of a better guess. Though I am pressed to think of a scenario where your `sources.list` would be borked.

**Comment by Benosika** [comment]
Here are the contents:

```
deb http://archive.ubuntu.com/ubuntu trusty main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu trusty-updates main restricted universe multiverse
deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu trusty-security main restricted universe multiverse
```

I never customized the file (or something in the system)... Maybe you custmoized something in it?

**Comment by therealkenc** [comment]
Nah that list looks fine. But since you are still on Trusty, probably the most practical move forward for you here is to just `lxrun /uninstall`, `lxrun install` from the Windows CMD prompt and get up to Xenial. I'm assuming you are on Creators Update here (15063). Not that those packages don't exist on Trusty, mind you. But you have as good an excuse as any to upgrade and get your package manager straightened.

Alternately you can google "Ubuntu Unable to locate package" and go down that rabbit hole. But in your circumstance I wouldn't recommend it.

**Comment by Benosika** [comment]
My Win10 home build is 14393.1066)... I just went to CMD and ran `lxrun /uninstall /full`, and then reinstalled WSL with `bash`, but when I do `lsb_release -a` I see my Ubuntu is 14.04.5 and the codename is still `trusty`. I wonder what you think... @therealkenc ...

**Comment by therealkenc** [comment]
You should have got the Creator's Update (which is 15063) by now. You are still on Anniversary Update (14393). So check your update settings (whatever that means) and try to upgrade if you can. You won't get the Xenial Ubuntu userspace without Creator's Update.

[googles...] It looks like the crux of your problem is php7, which was not available on Trusty (14.04). It looks like there is a [PPA](https://launchpad.net/~ondrej/+archive/ubuntu/php) if you can't (or won't) upgrade to Creator's. None of this is actually WSL related, of course. But hope that helps.

**Comment by Benosika** [comment]
Deep thanks! @therealkenc.

**Comment by Benosika** [comment]
BTW @therealkenc , is there no way to have this update manually? I tried to manually check for updates several times (even after `lxrun /uninstall /full` but there was nothing. I also did `lxrun /update` but I'm still on trusty.

**Comment by therealkenc** [comment]
"You are still on Anniversary Update (14393). So check your update settings (whatever that means) and try to upgrade if you can. You won't get the Xenial Ubuntu userspace without Creator's Update."

**Comment by Benqzq** [comment]
Well, I don't know what to do, as my Win10 has the default update settings and nothing is found manually in regards to a build upgrade.

**Comment by therealkenc** [comment]
Grab the .iso from [here](https://www.microsoft.com/en-ca/software-download/windows10) if you are having trouble upgrading. But before you do that, run winver from the cmd prompt just to be sure you aren't already there. But, as I said above, it would be unusual (in extremis) if you weren't.

**Comment by Benqzq** [comment]
[I downloaded the update from here](https://blogs.windows.com/windowsexperience/2017/04/11/how-to-get-the-windows-10-creators-update/#k4Ff0ou8sDAoXsAK.97).

**Comment by therealkenc** [comment]
What you did is fascinating of course. But what you want is to use the Create Windows 10 installation media Download Tool to get the .iso from the site I already linked. If you installed that .iso and it didn't get you on 15063 (which you can confirm by running winver), you'll probably want to seek help from some local computer enthusiasts.

**Comment by Benqzq** [comment]
I need not to seek help from anyone. There seem to be a misunderstanding here. I meant this is a shorter way and that the link I pasted above did upgraded my system to 15063 now. Your comment is sarcastic and I think you should delete it including me deleting this very comment.
