### ISSUE TITLE
BSOD on lxcore.sys

### ISSUE THREAD

**Issue by ayanamist** [Microsoft/BashOnWindows#1987]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)
Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)
Running a python script([you-get](https://github.com/soimort/you-get)) to download something, then suddenly BSOD which tells me lxcore.sys is the cause.

* What's wrong / what should be happening instead:
No BSOD

Here is the related item found in Event Viewer
[events.zip](https://github.com/Microsoft/BashOnWindows/files/949805/events.zip)

**Comment by fpqc** [comment]
please send this as an email to:

secure@microsoft.com

with

attn: Ben Hillis

Also it would be really helpful if you described what you did.

**Comment by ayanamist** [comment]
I can reproduce it stable, it BSODs again
![photo_2017-04-23_23-58-27](https://cloud.githubusercontent.com/assets/406779/25315027/e8bdd60a-2880-11e7-99d8-845ca0e7cea2.jpg)
Install the script above(using pip3 method), and run `you-get http://bangumi.bilibili.com/anime/5995/play` in WSL, after a while BSOD comes.
Here is the second MEMORY.dmp: https://www.dropbox.com/s/5jgv0gf38iqsnrv/lxcore_MEMORY_2.7z?dl=0
And i email this issue link to the address you provided with "attn: Ben Hillis" in the email subject.

**Comment by aseering** [comment]
@moderators -- should this post be deleted?  It's a potential security concern, and the poster did not follow the instructions on the [issue template](https://github.com/Microsoft/BashOnWindows/blob/master/ISSUE_TEMPLATE.md).

**Comment by ayanamist** [comment]
@aseering If you think deleting will prevent these to be spread, you are wrong. Both the script and the related websites are popular in china, it is quite easy to reproduce this stability problem rather than security problem.

**Comment by therealkenc** [comment]
Yep. Because North Korean hackers are monitoring this group for BSOD reports (presumably being unable to produce blue screens without our help), and are going to use your dump file to hack America and steal your credit card information. Or at least, that's how is how it was explained to me...

**Comment by GeeLaw** [comment]
@ayanamist No, by "security issue", he meant that your memory dump could contain information that might make you vulnerable (e.g. contain private/sensitive information of you), **not to** secure their fame.

**Comment by fpqc** [comment]
All BSODs are treated as potential security issues. Microsoft only shares crashdumps from their telemetry with selected partners for privacy reasons and also to avoid people collecting them and trying to find 0-days with a readily available source of crashes.

**Comment by aseering** [comment]
@ayanamist -- what is your objective in posting this BSOD + memory dump here?  Are you just trying to get this issue fixed?

If you've contacted Microsoft, and they haven't immediately responded with a fix, and you have a repro that's already public and a memory dump that you know is clean, then, yeah, absolutely post here.  And, because you're a responsible security person, include as relevant additional information that (a) this problem is already public so it's not sensitive and it probably is already actively being exploited if it's exploitable, and (b) your memory dump is clean / doesn't potentially contain any of your credentials or personal information so it's safe to re-share.

I'm not overly worried about you at this point; based on your response above, you sound like you have some security knowledge.  I'm worried about the next guy :-)  This bug-tracker is widely read, and not everyone has a deep understanding of how to handle a security issue without hurting themselves or others unnecessarily.  So if you're gonna post something that's potentially sensitive, do the rest of us a favor and do a proper and careful job of it, so the young'uns don't misunderstand and learn bad security habits from you :-)

**Comment by GeeLaw** [comment]
@fpqc Just learnt another lesson... Didn't realise memory dumps could give away hints on exploits.

@aseering I believe he believes this is an effective way of posting issues and raising awareness. **He's correct about the discoverability of this issue** since the thing he's doing is actually caching video from a popular video site. However, I suspect the frequency that one wants to use WSL for that, given the tool is quite available on Win32. And fixing this particular tool on WSL might be out of interest, once again because it's available on Win32. I do suggest he remove the dump before it is confirmed to be clean, or just indefinitely. If Microsoft could reproduce the issue, Microsoft could just use their own crash dumps.

**Comment by sunilmut** [comment]
@ayanamist - Thanks for taking the time to report to us the issue. I have downloaded the first dump and taking a look now. In future, we would appreciate if you could follow the issue template to report issues.

**Comment by ayanamist** [comment]
@GeeLaw
> However, I suspect the frequency that one wants to use WSL for that, given the tool is quite available on Win32.
I think it is quite easy to be reduced to a small bsod utility without using a full video caching script if concerning about security reason.
@sunilmut What do you mean by "follow the issue template to report issues." I only miss strace part because it seems tobe unrelevant with bsod reports. What other parts i missed?

**Comment by fpqc** [comment]
@ayanamist It says bugchecks or BSODs shouldn't be filed here at the top of the template haha.

**Comment by ayanamist** [comment]
Oh sorry, i miss read that....

**Comment by benhillis** [comment]
We've received the dump, thanks for that.  I'm scrubbing this thread.
