### ISSUE TITLE
Kernel isn't configured for semaphores

### ISSUE THREAD

**Issue by moosejackson** [Microsoft/BashOnWindows#2013]
Semaphores are still not working in build 15063.11.
Running ipcs in bash:

```
------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status

Kernel not configured for semaphores

Kernel not configured for message queues
```
According to [https://wpdev.uservoice.com](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13412589-add-support-for-semaphores-and-shared-memory#{toggle_previous_statuses}) semaphores should be working.

**Comment by moosejackson** [comment]
The problem was, that I had to update Ubuntu to 16.04 using 
```
do-release-upgrade
```
Now it seems, that semaphors could work

**Comment by fpqc** [comment]
Semaphores, I think, still don't work in the fakeroot program, which still needs to be recompiled with the tcp flag on an arch userspace.  I'd run an strace, but that's broken in the arch userspace because of the unimplemented options for PTRACE

**Comment by therealkenc** [comment]
#1016

**Comment by fpqc** [comment]
@therealkenc support is now there partially, that's why postgres works I thought

**Comment by stehufntdev** [comment]
The Creator's update has support for SysV semaphores and shared memory.  Closing this out as fixed in the creator's update, but please let us know if you hit any issues.

**Comment by fpqc** [comment]
@stehufntdev my strace is from CU.  The problem should happen in all versions of fakeroot compiled with the default sysvipc mechanism rather than tcp.

**Comment by therealkenc** [comment]
@fpqc - If you post a `strace -ff faked [however you do it] 2> faked.strace` I'll take a look. The one you posted doesn't have any fails to explain the `write(2, "fakeroot, while creating message"..., 68` fail. Actually it doesn't even contain a `clone()` or `exec()`, which could be an `ptrace()` thing if you already ran it with `-ff`. I have seen this before, see for example #1306 ([message](https://github.com/Microsoft/BashOnWindows/issues/1306#issuecomment-294307124)); although the guy never followed up on Adam's question regarding `strace -ff`.

So you likely have a mulimode failure here. It is not clear where that `"Function not implemented...This may be due to a lack of SYSV IPC support"` error is coming from. It could be SysV IPC. It could be a bad guess on `faked`'s part. If you are still splashing around in Arch-land, best thing to do is sit tight until #555 and #1878 ([message](https://github.com/Microsoft/BashOnWindows/issues/1878)) to flip to **fixedinsiderbuilds**. #1878 hasn't even made it to **bug** yet.

**Comment by therealkenc** [comment]
FWIW, the problem with `faked` does look like plain old unimplemented surface. The bonus is that the syscall fail does not turn up in `strace`. I have seen this before when I did #1530. For some reason I think we might have lost `ENOSYS` traces along the way. Anyway, test case below. This is on 16184, stock WSL 16.04.2 userspace.
```
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <sys/msg.h>
#include <stdio.h>

int main(int argc, const char * argv[])
{
  int msg_get, msg_key = 42;
  msg_get = msgget(msg_key,IPC_CREAT|0600);
  if (msg_get == -1)
    perror("msgget: ");
  return 0;
}
```
strace:
```
fstat(3, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
write(3, "msgget: : Function not implement"..., 35msgget: : Function not implemented
) = 35
close(3)                                = 0
```

**Comment by fpqc** [comment]
yeah, I tried it on Ubuntu too, that's why I didn't mention Arch

**Comment by stehufntdev** [comment]
@fpqc, can you please share out your repro?  Locally when I run `ipcs`, I get different output from what you posted above:

root@stehuf-test:/# ipcs

------ Message Queues --------
key        msqid      owner      perms      used-bytes   messages

------ Shared Memory Segments --------
key        shmid      owner      perms      bytes      nattch     status

------ Semaphore Arrays --------
key        semid      owner      perms      nsems

**Comment by fpqc** [comment]
@stehufntdev I didn't run ipcs, I ran fakeroot/faked.

**Comment by stehufntdev** [comment]
Sorry for the mix-up there, when I run fakeroot locally I get the failure below which is due to missing msgqueue support not semaphones (i.e. MSGGET, MSGCTL, ...).  Are you seeing a different failure?

root@stehuf-test:/# fakeroot
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

**Comment by benhillis** [comment]
System V semaphores and shared memory were implemented during Creators Update but message queues were not.

**Comment by fpqc** [comment]
Ah, there we go. Mystery solved.

**Comment by therealkenc** [comment]
@benhillis - Question is why moose is trippin' under 15063 (in the long forgotten OP above) but you were able to run `ipcs` (apparently) on in #162 on [Jan 6](https://github.com/Microsoft/BashOnWindows/issues/162#issuecomment-270941403). `ipcs` uses message queues ([here](http://code.metager.de/source/xref/busybox/util-linux/ipcs.c#375)) and you should have faceplanted.

**Comment by moosejackson** [comment]
When I've tried to run fakeroot, I got the same message as @stehufntdev mentioned. I had some problems with using semaphores in WSL(not sure where was exactly the problem), so I've installed Fedora to virtual machine and did all I needed there.
I had to use semaphores and shared memory for my school project (synchronization of processes) and it is already done :)
