### ISSUE TITLE
ls *.pdf returns error

### ISSUE THREAD

**Issue by bearyjd** [Microsoft/BashOnWindows#2035]
I believe there is a parsing error with the command:

ls *.pdf

it returns, 

xx@yyyy:/mnt/c/Users/xx/Downloads$ ls *.pdf
ls: invalid option -- '7'
Try 'ls --help' for more information.

Other queries return appropriate responses

For instance, 
$ ls *.p
ls: cannot access '*.p': No such file or directory

$ ls *.exe

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

Microsoft Windows [Version 10.0.15063]

**Comment by aseering** [comment]
Hi @bearyjd -- would you be willing to post the output of `ls -- *.pdf` in this directory?  In particular, does it print out a file whose name starts with "-7"?  If so, then this is a known general Linux issue; WSL is correctly emulating it.

**Comment by therealkenc** [comment]
https://ubuntuforums.org/showthread.php?t=1510996

**Comment by aseering** [comment]
(For reference, and thanks for bringing this up, the problem is that "*.pdf" is not evaluated by "ls".  The bash shell evaluates the wildcard and expands it into a list of arguments.  You can see this if you run `echo *.pdf`:  "echo" just prints its arguments, but this command gives you a list of files, so something else must be evaluating the wildcard.  So if you have a file named `-7`, then "ls" is called as `ls -7`.  "ls" doesn't know what the "-7" flag means, so it errors out.  The workaround is, by convention, if you pass `--` as a command-line argument, all subsequent arguments are to be treated as files (or whatever other appropriate data argument) and not flags, even if they start with "-".)

**Comment by bearyjd** [comment]
Thanks for the clarification and helpful explanation.

I tried in a separate directory, however realized after reading the responses that there where offending files in both locations  "-7009832.pdf"
