### ISSUE TITLE
Ifconfig 

### ISSUE THREAD

**Issue by nlogozzo** [Microsoft/BashOnWindows#2038]
- ubuntu version 14.04 running in anniversary update 

- When I type in ifconfug it says command not found so I go to cd /sbin and type in ifconfig and it still doesn't work

**Comment by aseering** [comment]
Hi @nlogozzo -- could you please fill out the [issue template](https://github.com/Microsoft/BashOnWindows/blob/master/ISSUE_TEMPLATE.md)?  Specifically, could you please copy and paste the exact commands that you are running and the exact error message that you are getting back?

There are a few possible problems here.  I think you are hitting at least one of them; possibly two; maybe more.  I would need to see exactly what WSL is telling you in order to know more.

Here are a few observations, though:

* In Windows, if you "cd" to the directory of a program, Windows will find it.  This is not true in Linux.  (Not with Ubuntu's default configuration, anyway.)  Therefore, it's not true in WSL.  It doesn't matter what directory you are in; even if you "cd" to the same directory as a program, that won't help to find it.  Instead, you have to refer to the program by its absolute path; for example, `/sbin/ifconfig`.
* `ifconfig` does not work properly in the Anniversary release.  Support was added in the recent Creators update.

**Comment by nlogozzo** [comment]
My problem was the anniversary update after updating to the creators update it works perfectly! Thank you
