### ISSUE TITLE
[Discussion] Best practices for data storage location/home directory

### ISSUE THREAD

**Issue by SRGOM** [Microsoft/BashOnWindows#2040]
Keeping in mind that https://github.com/Microsoft/BashOnWindows/issues/1475 (*1) and (*2) what is the consensus on the best place for storing your projects?

*1) Windows and Linux symlinks are incompatible

*2) You are not supposed to edit files inside WSL (both system and user directory) from Windows applications.

I was leaning towards having my Linux $HOME directory same as my Windows %PROFILEDIR% in /etc/passwd, however the dotfiles in both cases would have incompatible link format. So that's out. 

However, I'm thinking it would still be better if everything was stored on the "windows side" so that I can edit files from both sides, modulo the link related problems.? My primary environment for development would be WSL so I would do the filesystem manipulations on the WSL side only.

My question is what do you guys think about it? Does anybody have any cons to this approach.

**Comment by SRGOM** [comment]
Calling all WSL devs and non-dev experts that I know of (@fpqc, @aseering, @therealkernc). What best practices do you guys follow?

**Comment by CherryDT** [comment]
I have my projects at `%userprofile%\proj` with a symlink from `~/proj` to this directory. I also have a symlink form `~\z` to my Windows user profile. Additionally, some directories or files are directly linked from WSL to their Windows equivalent (e.g. `~/.aws`), and for SSH keys/config I have scripts I call to copy the data back and forth when something was changed because symlinking doesn't work due to the requirement of 600 permissions (while DrvFs will always show 777).

I develop with VSCode under Windows, but I run the projects only under WSL. I use a special script in my projects which makes sure that npm tasks are always run under WSL even if they are called through a git commit hook which is triggered by Windows Git from VSCode, for example.

This setup has a few inconveniences (one of them is that `npm link` is incompatible, so I don't see linked packages under Windows directly, and another is that FS performance is not so fast because of DrvFs) but mostly works OK.

If I needed better support of symlinks or better FS performance, I would switch to using a WebDAV or SSH server in WSL and map my home folder (or even root) to a drive letter in Windows.

**Comment by aseering** [comment]
My setup is actually very similar to @CherryDT 's.  I exclusively use ssh et al from within WSL so I don't need the key-management scripts.

**Comment by ajaykagrawal** [comment]
_if I needed better support of symlinks or better FS performance, I would switch to using a WebDAV or SSH server in WSL and map my home folder (or even root) to a drive letter in Windows_

@CherryDT how would you map your Linux FS to Windows with a SSH server running?

**Comment by CherryDT** [comment]
@aseering On my end it's basically just Git inside VSCode which is using the Windows-side SSH.
@ajaykagrawal With a third party tool like SshFs.

**Comment by SRGOM** [comment]
Thanks. I'll keep these tips in mind.
