### ISSUE TITLE
Separate WSL updates from Windows updates

### ISSUE THREAD

**Issue by SRGOM** [Microsoft/BashOnWindows#2041]
Re: https://www.neowin.net/news/microsoft-will-unbundle-its-edge-browser-from-the-windows-10-os-with-redstone-3

4265 people worldwide have starred this repository. Assuming half of them use WSL, it would be 2132.
53* people worldwide use Edge. WSL is used by 40 times more people than Edge. 

Given that. I think @bitcrazed should launch an internal lobbying effort to separate WSL updates from Windows. You guys lost quite a few people who were initially enthused and downloaded the Anniversary update only to find that there are some very minor issues which were dealbreakers. Should such a situation arise again, I wouldn't want the community to get smaller because a larger community means more help for everyone. 

\* Sorry for the exaggeration it's probably in single digits...

**Comment by MikeGitb** [comment]
I guess the main question is, if it is technically feasible to separate the two as some new features probably depend on changes in the windows kernel.

If on the other hand most of the work is done in the driver and the console nowadays, I'd also very much like to see a decupling of the two.

Btw.: I'm not sure if an even faster release cycle (with probably more bugs) would improve the image of the WSL. AFAIK MS us taking a lot of heat for releasing VS2017 early and a buggy state and now iterating very quickly on it. While I look with envy on the new Features that are available for insiders, I guess stability and consistency across multiple computers are much more important for most serious users.

**Comment by jcotton42** [comment]
@SRGOM dumping on someone's product then asking for a feature in the same sentence is generally in poor taste.

That aside, updating WSL and updating Edge are very different. WSL is implemented in the kernel, Edge is not.

**Comment by SRGOM** [comment]
@MikeGitb I agree with you re the update system. I remember even 8 months back, the majority of work was in drive and console. And I'd (and others) would love to have those working without using the insider builds. 

I have hope for WSL. It's a ridiculously amazing piece of magic. At the same time, people are very impatient with MS for some of the earlier software they churned out so when you don't see any fixes for 6 months, you're not likely to trust them again. I think regular updates would send a message that, yes, we're listening. I don't think it's fair to expect devs to run alpha/beta quality Windows builds just for this feature.

**Comment by MikeGitb** [comment]
@SRGOM: I'm also someone who will certainly not switch to an unstable OS-version just to get the latest updates for a developer tool, so I'm "hurt" by this policy too.

To be fair however, MS is already shipping updates for the WSL once or twice per year, which isn't too bad if you compare it to other developer tools. I'm mostly familiar with c++ tools and e.g. gcc is shipping a major update once per year, clang roughly twice, VS needs one or two years to release a new version (although they have started to ship more feature updates recently). So one update every 6-12 month is imho not really slow. What they are missing however are the intermediate bugfix/improvement releases you get from most other tools (issue https://github.com/Microsoft/BashOnWindows/issues/1911 tangles that topic).

Again, I don't know what their internal dev process looks like and what dependencies they have, but having those intermediate releases usually doesn't come for free and for now I'm content with them focusing on shipping new features with the next Win10 release instead of spending time on back porting features/fixes to the current release.
Regarding changes to the console, you should also not forget that the consol is used by a lot more people than the WSL, so shipping beta quality console updates to a production environment would probably not be appreciated by most users.

Finally, regarding your initial statement: I know this was meant as a joke, but you can bet that Edge is used by many more people (I'd guess orders of magnitude more) than the WSL so I'm pretty sure it is not easy for the team to argue that they should get the same treatment as Edge just based on this.

**Comment by SRGOM** [comment]
@MikeGitb I guess I was wrong about Console, yeah. Powershell users use it. And while it absolutely sucked, Rich has turned it completely around. 
Although I still stand by non-Console improvements to be shipped continuously, given that its a:

1) Beta product, as claimed by MS
2) Work will never "finish" on such a thing. There will always be something that will be missing and investing in WSL when you know that you'll have to wait at least 6 months for it to show up would be a non-starter for most. I setup Windows after 4 years in Aug 2016 only to be bitten by SBT issue. I decided to come back (have most things I need now) but I know people in similar situation didn't. That's just distrust of MS... 

I know Edge is used a lot (apparently 5% of entire internet browsing) and is actually a decent browser although Microsoft talked it up before it was ready. It was mean of me, sorry. But I hate it when if you disable msn on your computer then Ctrl-t requires an additional alt-d to start typing address. Hard for me to take such a browser seriously... :) 

`iwr cin.st | iex   ; choco install firefox` (Don't use cin.st, use https://chocolatey.org/install.ps1)

**Comment by bitcrazed** [comment]
LOL :) Love the idea but WSL is not an app or a bolt-on feature: 

WSL is built into the Windows kernel and is highly dependent upon, and coupled to, many other kernel features (e.g. networking, filesystem, PicoProcess). Many of these kernel features are also evolving to provide additional features to support new requirements from WSL.

If we shipped WSL separately to the rest of the kernel, we'd have to also ship an accompanying network infrastructure, filesystem, process management infrastructure, etc. WSL would end up being WSL + a boatload of the kernel anyhow, defeating the entire point.

The Console, on the other hand operates in a client-server manner with any command-line application you attach it to. Thus, there's a far higher likelihood that we'll be able to ship some version of the Console on a separate schedule & via a separate vehicle than the OS. No firm plans in place for this yet - but we are keen to explore some of these possibilities in the future.

Note that the fast-ring Insiders builds are essentially weekly snapshots of the next version of Windows as its being built. If you don't like that rate of change, slow ring is an ~monthly snapshot. Still to fast for you? Wait for the new releases every 6 months or so!

> To put this in perspective - we've gone from delivering major Windows releases once every 3+ years to once a week if you can tolerate the pace of change and potential issues that escape our testing!

So, appreciate the thought, but I think, as you can see above, this ain't gonna happen any time soon! ;) Closing.

**Comment by SRGOM** [comment]
Rich, thank you for answering.  I get your point. +1 to the separate  console..
