### ISSUE TITLE
[closed] Does not appear Bash on Features

### ISSUE THREAD

**Issue by foxovsky** [Microsoft/BashOnWindows#2046]
Hey, I try to establish bash on my tablet.
Apologize in advance if answer has already been given in another issue.

**System:** Windows 10 Pro
**Version:** 10.0.14393
![](https://raw.githubusercontent.com/foxovsky/foxovsky.github.io/master/imgs/Capture2.PNG)

# My steps:

First — enable developer mode in settings app
![](https://raw.githubusercontent.com/foxovsky/foxovsky.github.io/master/imgs/Capture.PNG)

Second — check updates
![](https://raw.githubusercontent.com/foxovsky/foxovsky.github.io/master/imgs/Capture1.PNG)

Further i'm restart my tablet and check features:
![](https://raw.githubusercontent.com/foxovsky/foxovsky.github.io/master/imgs/Capture3.PNG)

Thanks for help.

**Comment by sunjoong** [comment]
@foxovsky - I noticed you're using Windows 10 __pro__.  I was not sure it's possible to use WSL not in Windows 10 __home__, but found [Exploring Bash for Windows 10 Pro](https://rsdoiel.github.io/blog/2016/08/15/Setting-up-Go-under-Bash-for-Windows-10.html) so it looked possible. At the same time, I found #189 and #492. Those are all for Windows 10 __pro__. I'm still confused whether it's possible or not because, I thought, I had heard it's not possible once, but not sure.

**Comment by foxovsky** [comment]
@sunjoong thanks for answer, i use bash in windows 10 pro on my personal pc, therefore I wrote this post

![](https://raw.githubusercontent.com/foxovsky/foxovsky.github.io/master/imgs/Capture5.PNG)

**Comment by nlogozzo** [comment]
You said a tablet, 32-bit or 64-bit?

**Comment by aseering** [comment]
WSL is supported with Windows 10 Pro.  @sunjoong , you might be thinking of Windows 10 LTSB, which does not support WSL because the LTSB line only supports stable features.

@foxovsky -- do you have 32-bit or 64-bit Windows?  WSL requires 64-bit Windows because, so far, it exclusively supports 64-bit Linux.  (This is displayed in the "System type" field of "About your PC".)

**Comment by benhillis** [comment]
99% sure since it's a tablet it's x86.

**Comment by foxovsky** [comment]
ooh, sure

I completely forgot that my tablet on x86

Too bad, but thanks for answers

**Comment by sunjoong** [comment]
@foxovsky - Hmm... sorry. And, you can close issue to use `Close issue` button, left to `Comment` button when you write a new comment.
@aseering - Thans to correct me; I misunderstood then surely.

**Comment by phsantiago** [comment]
Same issue here, to solved I opened powershell as admin and executed this command: 
```Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux```
After that I did a reboot and installed Ubuntu by windows store.
Now if I try to open bash by win+r everything works well.
