### ISSUE TITLE
Enable filenames with colon (:) on drvfs (Copy of #1514)

### ISSUE THREAD

**Issue by SRGOM** [Microsoft/BashOnWindows#2070]
* Your Windows build number:  15063

* What you're doing and what's happening: Copied a file with : in name from ext4 system on a native Linux install to an NTFS partition. Copying worked fine. Reading from it from ext4 works fine. `ls` in both powershell & wsl fails.

* What's wrong / what should be happening instead: Stuff is happening as it should I guess. 

However, looking at #1514, @bitcrazed says that you guys are allowing filenames with colon to be accessed from Unix. And the fix is already in (in one of the insider builds before creator's update). I don't see it though. Is there a flag I should enable or something?

**Comment by redbaron** [comment]
same here, running 15063:

```
$ mkdir /mnt/d/abc:123
mkdir: cannot create directory ‘/mnt/d/abc:123’: Invalid argument
```

**Comment by MikeGitb** [comment]
I think you linked the wrong issue.

**Comment by redbaron** [comment]
updated to 16188, error still exists

**Comment by SRGOM** [comment]
@MikeGitb Fixed, thanks.

**Comment by stehufntdev** [comment]
#1752 was overloaded with a few different issues and looks like it was closed out when something was fixed instead of everything.

drvfs does not currently have full fidelity with Linux file system semantics, and if that is needed lxfs should be used instead.  At a high level you can think of drvfs like a cifs mount to your Windows partitions whereas lxfs has Linux file system semantics.  We are looking into improving this going forward, and there's more information on the WSL blogs if you are interested - https://blogs.msdn.microsoft.com/wsl/.

**Comment by SRGOM** [comment]
Thanks for clarifying @stehufntdev 

Maybe I'll sub to insider builds finally (although from the [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes?f=255&MSPPError=-2147217396#build-16176) I think you can only do a `mount -t drvfs` and not `mount -t lxfs` . Closing this.

**Comment by nelak** [comment]
@stehufntdev Do you have this on your roadmap?
I know I've hit this myself using VSCode and nodejs in WSL when trying to npm install a package with a with a `:` in it. IIRC it is recommended to use /mnt/c when sharing files between windows programs and WSL since you can't directly write to lxfs without messing things up really bad. Considering that WSL is becoming an interesting bridge for tooling this is likely to become an issue as more people start moving their workflows to windows and WSL.
Do you have any workarounds for this?

**Comment by stehufntdev** [comment]
Adding @SvenGroot.  We are looking at improving file systems but I don't think there are any workarounds at this time.
