### ISSUE TITLE
Bugcheck on VfsLookupDirectoryEntryInode TRK:0441000864

### ISSUE THREAD

**Issue by billziss-gh** [Microsoft/BashOnWindows#2079]
On March 21, 2017 I sent a report about a bugcheck to secure@microsoft.com. It had complete instructions on how to reproduce and the WinDbg `!analyze -v` output.

The report was assigned the number **TRK:0441000864**, but I have not received any other status update. Not receiving status updates is a disincentive to report such issues.

**Comment by benhillis** [comment]
@billziss-gh - I apologize for the delay. I actually just received a notification from the security folks yesterday about this issue.  They say there was a "CRM issue" and your email got lost when it was forwarded to the feature team.  @JasonLinMS took a look at your dump yesterday and verified that it was fixed in Creators Update.

Thanks for sending the dump, and I apologize for the inconvenience.

**Comment by billziss-gh** [comment]
@benhillis thanks for the quick update. It is much appreciated.
