### ISSUE TITLE
php builtin server doesn't start

### ISSUE THREAD

**Issue by Geeknux** [Microsoft/BashOnWindows#212]
Hi,
when i try to start php-cli builtin web server i got error.
for example i type:
php -S localhost:8000
or php -S 127.0.0.1:8002

i receive: 
```
PHP 5.5.9-1ubuntu4.14 Development Server started at Sat Apr 16 11:54:56 2016
Listening on http://localhost:8000
Document root is /root/test
Press Ctrl-C to quit.
[Sat Apr 16 11:54:56 2016] Bad address
```

**Comment by benhillis** [comment]
Thanks for reporting this!  I dug into this today and this is actually a really interesting implementation detail of the select system call regarding the timeout value.  PHP is passing a readonly buffer for the timeout which we are probing for write because select is supposed to update the buffer with the time remaining.  I investigated the behavior on the real Linux kernel and if the write fails the system call does not report EFAULT, it just silently continues.

I'm working on a fix for this.  Thanks again for reporting this - one of the more interesting issues I've debugged recently.

**Comment by benhillis** [comment]
The fix for this issue is on the way to the fighting branch, keep an eye out in our release notes to know which insider build contains this fix.

**Comment by michha** [comment]
I am also awaiting this fix for getting CakePHP running under Bash on Windows. It also uses the php-cli server (see [api documentation](http://api.cakephp.org/3.2/source-class-Cake.Shell.ServerShell.html#_main))

**Comment by michha** [comment]
CakePHP server is running. Thanks for the fix :)

**Comment by benhillis** [comment]
I've verified this is fixed in build 14352, please reopen if you continue to see this issue. Thanks!
