### ISSUE TITLE
No more release notes?

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/BashOnWindows#2127]
The [release notes](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes) page hasn't been updated for a while.

Does it mean there's no (public) work on WSL, or is it just not up to date?

**Comment by therealkenc** [comment]
Haven't seen Russ around in ages, which I think might be correlated. There is public work going on; for example 1958 seems to have landed. But truth is it has been relatively quiet on the fixinbound ➜ fixedinsiderbuilds label transition front on github for a few weeks, so maybe it just wasn't worth the trouble.

**Comment by benhillis** [comment]
There have not been release notes because our payload has been stuck in a child branch of the prerelease branch for nearly a month.  This is unrelated to our payload, and a side effect of how code changes are propagated in the windows build system. The good news is there will be a lot of changes in an insider build soon.
