### ISSUE TITLE
port opend in subsystem not the same one?

### ISSUE THREAD

**Issue by yunfengsay** [Microsoft/BashOnWindows#2159]
![image](https://cloud.githubusercontent.com/assets/15527378/26482508/6c73a922-421a-11e7-90bb-1073f05d9ace.png)
![image](https://cloud.githubusercontent.com/assets/15527378/26482525/7b66e98a-421a-11e7-9008-8d8b4575b728.png)
![image](https://cloud.githubusercontent.com/assets/15527378/26482537/8b096af2-421a-11e7-93b6-b8feada9722f.png)
![image](https://cloud.githubusercontent.com/assets/15527378/26482604/e43cd500-421a-11e7-8643-bcd0c4106e88.png)

I open a port in subsystem  but can not access it in win10

**Comment by sunjoong** [comment]
@yunfengsay - Check that port is listening using `netstat` command in `cmd.exe` window.
![http](https://cloud.githubusercontent.com/assets/2748000/26484355/877ff628-422c-11e7-90b5-905fc481ed80.png)

**Comment by dexgeh** [comment]
I have the exact same problem, that started when I installed Microsoft Message Analyzer yesterday.

Things that I tried since yesterday that the problem started:

- system restore to a point before the installation of MA
- reset ubuntu via lxrun /uninstall /full
- reset tcpip networking
- reinstall MA

The problem is present even when I select a single interface to listen specifying an ip address to both nginx and netcat. I straced netcat, the relevant part:

    socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
    setsockopt(3, SOL_SOCKET, SO_REUSEADDR, [1], 4) = 0
    bind(3, {sa_family=AF_INET, sin_port=htons(19000), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
    listen(3, 1)                            = 0

**Comment by sunjoong** [comment]
@yunfengsay - And... https://github.com/Microsoft/BashOnWindows/issues/1498#issuecomment-300194700; In my case, Anti-virus blocked port.
