### ISSUE TITLE
cannot create directory: No such file or directory

### ISSUE THREAD

**Issue by nagisa** [Microsoft/BashOnWindows#2218]
* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

No idea. Sorry. I haven’t access to the machine (anymore).

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

All I know that it was something along the lines of:

```
$ pwd
/mnt/c/Projects/.../Directory
$ rm -rf /mnt/c/Projects/.../Directory # from somewhere else maybe?
$ cd ..
$ git checkout Directory # cannot create directory: No such file or directory
$ mkdir Directory # cannot create directory: No such file or directory
```

The only way to create directory again I’ve found is restarting; nothing else I’ve tried helped.

* What's wrong / what should be happening instead:

The error message is nonsensical; Should just create the directory.

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

Sorry. I haven’t access to the machine (anymore). I will try reproducing elsewhere and report if I can hit it again.

**Comment by sunjoong** [comment]
@nagisa - It sounds similar to this scenario but... I'm not sure;
```
sunjoong@SUNJOONG-DESKTOP ~/temp $ pwd
/home/sunjoong/temp
sunjoong@SUNJOONG-DESKTOP ~/temp $ rm -rf ../temp/
sunjoong@SUNJOONG-DESKTOP ~/temp $ mkdir new
mkdir: cannot create directory 'new': No such file or directory
sunjoong@SUNJOONG-DESKTOP ~/temp $
```

**Comment by CherryDT** [comment]
@sunjoong Not sure, because in your case the error makes sense because your current directory doesn't exist anymore so you are trying to create a directory inside a nonexistent one, while in the OPs description he did do `cd ..` before creating the directory.

**Comment by nagisa** [comment]
I could not reproduce it. I will reopen if I ever hit this again.

**Comment by jaron-lundwall** [comment]
For documentation purposes, I was able to reproduce but it wasn't a WSL error. It's a permission issue. For me, it's because I had Windows 10's ransomware protection on which refuses write access to certain protected folders and refused WSL. Disabling it for mkdir specifically fixed the issue.

``
#Initial error
user@computer:/mnt/c/Users/directory/WSL$ mkdir test
mkdir: cannot create directory ‘test’: No such file or directory

#showing that my current directory exists
user@computer:/mnt/c/Users/directory/WSL$ pwd
/mnt/c/Users/directory/WSL

#change to directory not protected by windows 10 ransomware protection (inside WSL home folder)
user@computer:/mnt/c/Users/directory/WSL$ cd /home/user

#mkdir now works
user@computer:~$ mkdir new
user@computer:~$ ls
new

#turned off ransomware protection for WSL and mkdir now works
user@computer:/mnt/c/Users/directory/WSL$ mkdir test
user@computer:/mnt/c/Users/directory/WSL$ ls
test
``
