### ISSUE TITLE
CTRL+C won't interrupt SSH client attempting to connect to a non answering host

### ISSUE THREAD

**Issue by omartin2010** [Microsoft/BashOnWindows#2220]
Simply trying to ssh to a host that doesn't exist and trying CTRL+C to avoid having to wait until timeout happens... which doesn't work as it does on a regular linux Ubuntu.
omartin@DESKTOP-10OCDI0:~$ ssh toto@123.123.123.13
^C^C^C^C^C

I'm running build 15063.413 with 16.04 Ubuntu... I tried to look into the opened issues, it doesn't seem to be there.

**Comment by omartin2010** [comment]
won't interrupt traceroute neither. Maybe something socket related...

**Comment by fpqc** [comment]
what about 

`<enter> ~.`

 in ssh?

**Comment by omartin2010** [comment]
doesn't work more... 

ssh omartin@DESKTOP-10OCDI0:~$ ssh user@1.2.3.4
~.~.^C

omartin@DESKTOP-10OCDI0:~$

**Comment by sunilmut** [comment]
@omartin2010 - Thanks for your post. You were correct with your statement `Maybe something socket related`. The issue was that the `connect` socket syscall was not-interruptable. That was fixed sometime back, but after Creators Update (build 15063). I tried it on the latest Insider build 16215 and it seems to be fixed.

**Comment by omartin2010** [comment]
Ok, thanks!

**Comment by therealkenc** [comment]
> The issue was that the connect socket syscall was not-interruptable

@sunilmut - Are there other syscalls that are known to have this limitation? I am still having trouble breaking `gdb` like [here](https://github.com/Microsoft/BashOnWindows/issues/648#issuecomment-299738868), but I don't know if the problem is debugger related (signals, ptrace, etc) or just a more general problem with the debuggee being stuck in an uninterruptible syscall. Bearing in mind that the code in question (chrome) is almost certainly stuck in network related activity (either AF_INET or inter-process AF_NETLINK) -- because that's mostly what the software does for a living at the kernel interface boundary. The inability to break persists in 16215.

**Comment by sunilmut** [comment]
@therealkenc - We are not aware of any other syscall that has this limitation. Though confirming that would require a full pass over the code. In your scenario:
1. Are these reproducible?
2. Are these *hung* operations ever timing out? If so, then an strace with a search for some timeout related error might provide some insight.

**Comment by therealkenc** [comment]
> Are these reproducible?

Completely reproducible, but not under a supported WSL use-case, which is why I haven't opened a new github issue. It's a `recvmsg()` that `EAGAIN`s forever ultimately causing a `futex` to timeout and a thread to die, and everything goes south from there. You can `SIGINT` the code when run from the command line but not under `gdb`. I'd post the 70k line strace but it probably isn't worth your time until #1006, #1910, and the `ENOSYS` #2053 issues to flip. Known issues before unknown issues, I say. But if you are feeling masochistic say the word and I'll open a separate issue with pretty straightforward (if unsupported) steps.

**Comment by sunilmut** [comment]
If `You can SIGINT the code when run from the command line but not under gdb.` is true, then it feels to me more of a `ptrace` issue than a `non-interruptable syscall`. We definitely have some known issues on the ptrace side of things #2216, #555, #204. But, not sure if they are related.

**Comment by therealkenc** [comment]
Yeah almost certainly a "`gdb` thing". My question was mostly grasping out of desperation for an explanation, on the chance you might name some other syscalls that can't be interrupted. Just hoping for an ah-ha. It probably isn't #555/#2216 proper; if `gdb` was hitting _unimplemented_ `ptrace` surface, the `EINVAL` would be glaring. Could be #204; that issue is kind of dangling. But it isn't spinning on a busy loop like Adam's test case, which anyway has probably been addressed. There are plenty of syscalls being made that should notice the `SIGINT`. After the fact, the process under `gdb` can only be put to rest with `SIGKILL` from another term. Anyway, I was just stopping by because of the "^C^C^C^C^C" report. Thanks for the follow-up thoughts.

**Comment by therealkenc** [comment]
> Yeah almost certainly a "gdb thing"...

...but I bet 50 cents it is related to this somehow:
```
ken@DESKTOP-9BDQA3V:~/Devel/vscode/vscode/strace$ grep restarted *
vscode.29:ppoll([{fd=3, events=POLLIN}], 1, NULL, [], 8) = ? ERESTARTNOHAND (To                                               be restarted if no handler)
vscode.37:select(5, [4], NULL, [4], NULL)         = ? ERESTARTNOHAND (To be rest                                              arted if no handler)
```
