### ISSUE TITLE
An input redirection issue.

### ISSUE THREAD

**Issue by Humbertzhang** [Microsoft/BashOnWindows#2233]
Well, i write a shell script on REAL Ubuntu16.04,  It help me to git push something without inputing the Username and Password every time.
The question is, it works on Ubuntu, but it still need I to input Username and Password On Bash On Windows. 

**The structure of  it:** 
.
├── **pushit**
├── README.md
└── **setup.sh**

**setup.sh:**
```shell
#!/bin/bash

read -p "Username:" username
echo $username > username
read -p "Password:" -s password
echo password > password
echo

cd /etc
sudo rm -r pushit_Info

sudo mkdir pushit_Info
cd -
sudo mv username password /etc/pushit_Info

sudo cp pushit /usr/local/bin
echo "You can Use pushit command Now!"
echo "You can modify the Username And Password by run setup.sh again"

```

**pushit**
```shell
#!/bin/bash
git add .
echo "Input the Commit Message:"
read CommitMessage
git commit -m ${CommitMessage}
#echo "Input the branch(default is master):"
git push </etc/pushit_Info/username </etc/pushit_Info/password

```

And I think the problem happens in the process of redirection(I am not sure,I am a novice..but the problem is indeed exist).

**Comment by therealkenc** [comment]
> git push </etc/pushit_Info/username </etc/pushit_Info/password

I am thinking you must have something unintentionally different on your Real Linux™ box that is causing it too "succeed". That construct isn't going to pass the username and password into `stdin` AFAICT. Simplifying what you are doing above:
```
ken@zesty-vm:~$ echo hello > hello
ken@zesty-vm:~$ echo world > world
ken@zesty-vm:~$ cat < ./hello < ./world
world
```
Note only 'world' is echoed. This behaves the same on WSL and Real Linux. Or maybe I am missing something obv and someone else will jump in.

I can't run your test as is because I've got my git passwords set up (and I'm not going to undo that). You probably should get them set up too. You can check out the git password cache documentation [here](https://git-scm.com/docs/git-credential-cache). Better still, use `ssh` instead of `https` as your protocol, and set up ssh public keys per [here](https://help.github.com/articles/connecting-to-github-with-ssh/). That link is geared toward github but it's a friendly explanation to start. More detailed info about git protocols [here](https://git-scm.com/book/id/v2/Git-on-the-Server-The-Protocols).

Bonne chance.

**Comment by CherryDT** [comment]
@Humbertzhang: Check the output of `git remote -v` on your linux box, my gut tells me that you have a `username@` part in there, probably from an earlier attempt to solve this issue another way...
