### ISSUE TITLE
After prerequisites, running 'bash' from Command Prompt does not install WSL distributions in Insider Preview Build 16226. You are directed to https://aka.ms/wslstore where distro is not yet available

### ISSUE THREAD

**Issue by 2nleyrtonc** [Microsoft/BashOnWindows#2250]
This bug-tracker is monitored by developers and other technical types.  We like detail!  So please use this form and tell us, concisely but precisely, what's up.  Please fill out ALL THE FIELDS!

If you have a feature request, please post to [the UserVoice](https://wpdev.uservoice.com/forums/266908).  If you're reporting a BSOD, don't post here!  Instead, e-mail "secure@microsoft.com", and if possible attach the minidump from "C:\Windows\minidump\".

* Your Windows build number:  (Type `ver` at a Windows Command Prompt)

* What you're doing and what's happening:  (Copy&paste specific commands and their output, or include screen shots)

* What's wrong / what should be happening instead:

* Strace of the failing command, if applicable:  (If `<cmd>` is failing, then run `strace -o strace.txt -ff <cmd>`, and post the strace.txt output here)

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by fpqc** [comment]
Yeah. Opensuse is actually up right now.

If you want to install Ubuntu to the legacy location, type `lxrun /install`.  The other distros will be coming up to the store shortly

**Comment by therealkenc** [comment]
```
Warning: lxrun.exe is only used to configure the legacy Windows System for Linux distribution.
```
That message gave me a good chuckle this morning. +1 for comedic value.

**Comment by fpqc** [comment]
@therealkenc Yeah the new manager is called wslconfig.

**Comment by onomatopellan** [comment]
should we post here what we find out about the new distro apps?

Right now there are 2 distros on the Store: SUSE Linux Enterprise Server 12 and OpenSUSE Leap 42.
The URL https://aka.ms/wslstore won't find anything because they didn't use the word WSL on the distro description.
Both installed correctly but only on the system drive C:. "Move" feature from Apps Settings don't work yet.
Now each distro is on the Local/Packages folder and has a rootfs folder with everything inside, home folder included.
They can be running simultaneously but right now they lack the distro Icon on taskbar.

**Comment by benhillis** [comment]
This feature is still in development.  Pease be patient everything will be sorted out soon.

**Comment by sunjoong** [comment]
@onomatopellan - Title of this issue is constituted with two sentences, "After prerequisites, running 'bash' from Command Prompt does not install WSL distributions in Insider Preview Build 16226" and "You are directed to https://aka.ms/wslstore where distro is not yet available."

For "You are directed to https://aka.ms/wslstore where distro is not yet available", #2212 is still opened.

**Comment by onomatopellan** [comment]
@sunjoong I totally missed that. Thanks.

**Comment by sunilmut** [comment]
Canonical is available in the [Windows store ](https://blogs.msdn.microsoft.com/commandline/2017/07/10/ubuntu-now-available-from-the-windows-store/). Closing this issue out.
