### ISSUE TITLE
Arch Linux Support

### ISSUE THREAD

**Issue by shibumi** [Microsoft/BashOnWindows#2253]
Hello,
I would like to work on Arch Linux Support for Microsoft WSL. Is this possible?  Is there any email that I can try to contact? Would be nice to get Arch Linux on Windows.

**Comment by sunjoong** [comment]
@shibumi - Well... those might be helpful, I think;
* https://github.com/alwsl/alwsl
* https://itsfoss.com/arch-linux-windows-subsystem/
* https://wiki.archlinux.org/index.php/Install_on_WSL

**Comment by shibumi** [comment]
@sunjoong  Hey thanks for the links. Note that `alwsl` is not an official arch linux project. But hopefully we have one soon.

**Comment by sunjoong** [comment]
@shibumi - Oops!! I misunderstanding your post. I think... @sunilmut could help you.

**Comment by shibumi** [comment]
Cool! I mean I have heard of official Ubuntu, Opensuse and CentOS support. Would be cool to have Arch Linux there too.

**Comment by sunjoong** [comment]
@shibumi - Also @bitcrazed need to know that, I guess. And... it could be cool to have Arch Linux in Microsoft Store :)

**Comment by therealkenc** [comment]
Note Arch suffers a bit from #1878 and #555 (as of 16226) because pacman tends to bleed more than other distros' LTM tracks.

**Comment by shibumi** [comment]
@therealkenc Maybe we are able to patch the issues out of pacman. I can talk with allan (the main pacman developer) about this issues.

**Comment by therealkenc** [comment]
I didn't mean `pacman` proper. I meant Arch (not unlike Gentoo portage) tends to pull down bleeding edge releases of various OSS software. I think #1878 is in the bones (`glibc`). You can "patch anything" of course, and I say _tends_ because you can roll packages back in Arch or Gentoo if you are determined enough. Basically you have the (rough) Ubuntu equivalent of everyone trying to install Artful Aarvark on WSL, and then posting the commensurate bugs posted here when stuff doesn't work. This situation will resolve itself as more Linux kernel surface is spackled over in WSL. So, time.

**Comment by sunjoong** [comment]
@therealkenc - @shibumi is a "Member of Arch Linux Security Team and Arch Linux Trusted User" and was just looking for contact of MS "to work on Arch Linux Support for Microsoft WSL". You look like to imply this starting official arch linux project might be more burdened than the current unofficial arch linux support :(. And... as a gentoo linux user, I envy of them at this trial of arch linux, I'd like to say :).

**Comment by fpqc** [comment]
Neat! I'd use this @shibumi =)

**Comment by sunilmut** [comment]
@shibumi - Thanks for reaching out. Yes, we also think that it would be great to have `Arch Linux` on the Windows store. One of us will reach out to you.

**Comment by shibumi** [comment]
@sunilmut feel free to contact me via email: Chris.Rebischke@archlinux.org
I will close this issue.

**Comment by bobvanderlinden** [comment]
@sunilmut Thanks a lot for stepping up to attempt to solve this issue. Is there any progress or is there any place to get notified about progress? If there isn't yet, I'd suggest continuing the conversation in #1878.

**Comment by sunilmut** [comment]
@bobvanderlinden - There is no progress to report at the moment. @bitcrazed will be driving this effort. So, feel free to ping him here or at his twitter handle @richturn_ms

**Comment by leonardder** [comment]
Is there any chance that Arch support in WSL will be added to the windows tore?

**Comment by shibumi** [comment]
@leonardder Sorry, bad news. Most Arch Linux Developers decided they won't support Arch in WSL. :( I am very sorry.

**Comment by nesl247** [comment]
@shibumi Is there a link to where this decision was made?

**Comment by shibumi** [comment]
@nesl247 Yes: https://lists.archlinux.org/pipermail/arch-dev-public/2018-January/029135.html

**Comment by DarthSpock** [comment]
@shibumi A major concern I'm seeing is that they don't want Microsoft advertising their name for the sake of profit. I think they should forget about the politics of the situation and think about the users who are directly impacted by not having it available. They complain that alwsl doesn't work great and that's partly because it's not being installed in an official manner. 

> Good luck with debugging all possible heisenbugs that can be encountered due to sloppy implementation of Linux syscalls on Windows." 

Microsoft is responsible for providing Linux syscalls that work and I have to say that to say it's sloppy shows this developer has paid no attention at all to WSL and doesn't have a clue what he's talking about. Most syscalls work just fine and if there were any issues, they would be reported here, not there. If the random user reports it there, you can then do the "EWONTFIX" with a link to the WSL github page. As far as packages go, support is the same as it is running native Arch. As far as that `glibc` issue was, it was a bug with `glibc` NOT WSL just so that clarity is out there. See the issue for it for that confirmation.

> I don't think the pre-configured, ready-to-to setup is where Arch is in the marketplace

Personal opinion that is. I honestly think that's the direction every distro should have, it would actually have potential impact to bring people from Windows (who does do that pre-configured, ready-to-setup) to Linux distros including Arch. This is obviously a bigger policy issue than just WSL but that's my opinion on the matter. 

To reiterate: Don't let judgement of Microsoft cloud decision to support the people that matter: your community, which you pointed out, would most likely grow as a result and that isn't a bad thing and your counterparts need to understand that.

I believe I've addressed all publicly known issues with supporting WSL. If there's anything else not being told, well nobody here can address that.

**Comment by nesl247** [comment]
Thanks for the link @shibumi. After reading that, I have no intention to look at Arch Linux again. It was a distro I loved for a long time, but their ridiculous hatred for a company because it's "cool", and basing all decisions decisions off of that is a complete turnoff.

There is nothing political with adding Arch to the Microsoft Store, however, they certainly made it one. Blaming a company for past practices, or because it's "cool" is a horrible stance to take.

Had they decided that they didn't want to do it simply on the stance that they don't want the extra work (though how much extra work would it really be), that would have made complete sense.

What I don't get and never will from the Linux community is why things can't be easy. I ran Gentoo for many years, it was great. It was a lot of work, but even then I don't recall the community opposing easier installations and setups. Arch a lot of times has felt as if they want to be a small little distro, and yet, from a developers point of view at least, it's the one I mostly see people want to use. They should embrace the popularity.

I also completely agree with you @DarthSpock. Shame things turned out the way they did.

**Comment by DarthSpock** [comment]
@nesl247 What's funny is Kali Linux is in the Store and if you look at their history, they've done far more work than the Arch Linux devs ever did starting before even BackTrack was around. Kali's new guide "Kali Linux Revealed" gives a great historical summary of the work they've done. Even funnier is that Ubuntu, Debian, and Open Suse (including their Enterprise you pay for) do the pre-configured, ready-to-to setup for WSL. Kali actually takes it even further with their Live CD/USB so you don't even need to install it to run it (and thus preventing forensics from being tampered). I believe Ubuntu somewhat has this option as well but not to the degree Kali does. I think Arch Linux is in need of new leadership if the current devs want to continue living in the past. Too much has changed in the last few decades for that type of attitude to continue. The KDE community unfortunately has a similar attitude which is rather surprisingly due to their nature of being devvy type community if not a dev. There's too many people still licking old wounds that they are blind to the new reality and choose to be blind. It's really mind-boggling to me considering "forward-thinking" is supposed to be what every developer is.

**Comment by Scimmia22** [comment]
> > I don't think the pre-configured, ready-to-to setup is where Arch is in the marketplace
> 
> Personal opinion that is. I honestly think that's the direction every distro should have, it would actually have potential impact to bring people from Windows (who does do that pre-configured, ready-to-setup) to Linux distros including Arch. This is obviously a bigger policy issue than just WSL but that's my opinion on the matter.

Then you don't understand Arch at all. There are plenty of distros that fill that need; if that's what you want, use them.

**Comment by DarthSpock** [comment]
> There are plenty of distros that fill that need; if that's what you want, use them.

So you're telling me that if someone wants to learn and grow more familiar with various distros using WSL, thus potentially expanding the amount of platforms a developer can contribute to (corporate projects or open-source) that they will get the "sorry we don't want you".  This just emphasizes what I said about needing new leadership.  Nobody is trying to take away from what Arch wants to do, we just want to share in that. Is that really too much to ask for? 

From Arch's own principles:

> Pragmatism

Arch is a pragmatic distribution rather than an ideological one. The principles here are only useful guidelines. Ultimately, design decisions are made on a case-by-case basis through developer consensus. Evidence-based technical analysis and debate are what matter, not politics or popular opinion. 

They're going against that principle in regards to WSL because it's Microsoft.


> User centrality
The distribution is intended to fill the needs of those contributing to it, rather than trying to appeal to as many users as possible.

WSL is stated by Microsoft to be for developer's, not regular users. Sure anybody can install and run it but it's focus has always been on development. So using WSL can actually help that contribution as developers can use interop with Windows to use Windows specific tools that could make a developer's life easier.

> Versatility
Arch Linux is a general-purpose distribution. Upon installation, only a command-line environment is provided

This is exactly what WSL is out of the box, any GUI manipulation is purposely done by the user as it isn't officially supported by Microsoft. So not seeing where WSL can't fit the needs of Arch Linux when they provide the same exact thing.

Considering I just showed "the Arch Way" is actually enhanced by supporting on WSL, and is being ignored (on purpose or not), I don't see any technical reason Arch Linux shouldn't become available on WSL. If it's for personal opinion, fine state that but keep in mind you're not adhering to Arch's own principles. Just some food for thought.

**Comment by eli-schwartz** [comment]
> Had they decided that they didn't want to do it simply on the stance that they don't want the extra work (though how much extra work would it really be), that would have made complete sense.

Yeah, um, this is more or less what happened I think?

Of the seven people who participated in that dev discussion:

- 2 (including myself) expressed hesitation at our ability to properly offer support, and the resulting substandard experience when offering a product we don't actually control and which has been known in the past to not really work (cf. early comments in this issue)
- 1 is the glibc package maintainer, and made a combined political argument and technical argument (as the glibc maintainer)
- 2 offered trademark questions
- 2 want to see it 

The point was made that Arch Linux can be installed in WSL the same way it can be installed from any other system, by running our bootstrap image from a preexisting Ubuntu chroot.

What, exactly, does offering Arch Linux in the Windows Store get us beyond that? I know what it gets Microsoft -- another distro that they can say is available on Windows.
As for us, our knowledgeable users can still install Arch Linux with no real inconvenience. Our unknowledgeable users will simply burden us with uninteresting support questions better answered in the manpages, wikis, official documentation, and stackexchange sites.

We do not have a fundamental objective of being available from WSL and being able to advertise this on our download site. We don't even advertise this for docker or vagrant, both of which we provide images for -- because it is easy to register them, and they work well natively, and they're useful.
Do we get an improved ability to discuss WSL integration bugs that stop Arch Linux from working, above and beyond the existing ability to submit bugreports here? 

> They complain that alwsl doesn't work great and that's partly because it's not being installed in an official manner.

How would installing alwsl "in an official manner" fix substandard experiences like the glibc issues or whatever may be the next similar issue?

> Personal opinion that is. I honestly think that's the direction every distro should have, it would actually have potential impact to bring people from Windows (who does do that pre-configured, ready-to-setup) to Linux distros including Arch. This is obviously a bigger policy issue than just WSL but that's my opinion on the matter.

If people come to Arch Linux expecting preconfigured, ready to setup systems, they are in for a godawful disaster. We don't target that userbase, our community expects people to have a basic understanding of what their system is doing as a basic prerequisite to asking for support, we don't provide an official GUI for our package manager nor install "recommended" packages, we have a highly explicit policy forbidding service autoconfiguration on the grounds that users should opt in to what they want (because they've read the software documentation and our Wiki and know that the service exists and why they might want to use it), etc. etc.

> Kali Linux is in the Store and if you look at their history, they've done far more work than the Arch Linux devs ever did

Far more work what? This is a super vague statement, what goals are you referring to that they have accomplished which we have failed to accomplish?

> Even funnier is that Ubuntu, Debian, and Open Suse (including their Enterprise you pay for) do the pre-configured, ready-to-setup for WSL. Kali actually takes it even further with their Live CD/USB so you don't even need to install it to run it (and thus preventing forensics from being tampered).

I'm completely and utterly shocked that companies with a financial incentive for being available in WSL made sure to be there. /s

> I think Arch Linux is in need of new leadership if the current devs want to continue living in the past.

Is this entirely based on our lack of support for Windows, or is there anything you feel we are actually living in the past about? I think it is pretty dishonest of you to imply that Microsoft Windows support is the single determining factor that qualifies one as living in the present rather than the past. It is, in fact, a pretty blatantly political decision of your own.

Because this clearly isn't about our disinterest in providing a preconfigured system. I think the fact that Arch Linux has remained a popular and relevant distribution for a long time indicates that people who whose physical presence manifests in the current datetime, are pretty happy with "outdated" concepts like our whole image as a DIY distribution. Pretty sure most of those people also accomplish real work in the modern world.
On top of which, if you thought a DIY system was an outdated concept, why would you want it in the Windows Store anyways?

**Comment by DarthSpock** [comment]
I don't wish to address this issue. I've said more than I intended to and don't plan on going down what appears to be a dirty path.

**Comment by fpqc** [comment]
No point in having an argument here. Scimmia is an arch dev with commit access, and their community has spoken.  There are plenty of other options.

**Comment by Scimmia22** [comment]
To clarify, I am not an Arch dev, I just take care of the bug tracker.

**Comment by leonardder** [comment]
Now [there is an open sourced WSL sample](https://www.phoronix.com/scan.php?page=news_item&px=Microsoft-Opens-WSL-Sample), I wonder this could have a positive impact on having Arch in the Microsoft Store. Having said that, it turned out to be quite easy to get Arch running using LxRunOffline.

**Comment by DarthSpock** [comment]
@leonardder I would rather side-load Arch or any other distro sooner than use LXRunOffline or any other offline mechanism. I'm pretty sure we're going to see support for those projects change with this open-source launcher now available. I'm half tempted to side-load this distro myself but hoping someone with more time available will simply publish an .appx somewhere on Github until official releases from distro maintainers such as Arch appear in the Store.

**Comment by fpqc** [comment]
@darthspock they just released the official sideloader code.

**Comment by fpqc** [comment]
https://blogs.msdn.microsoft.com/commandline/2018/03/26/wsl-distro-launcher/

**Comment by DarthSpock** [comment]
I'm aware. I posted the link in the appropriate issue regarding appx earlier.

**Comment by shibumi** [comment]
Sorry Guys, at the moment I can't see any chance that there will be an official Arch Linux WSL image in the next months. The discussion on our mailing list was pretty clear. Some devs don' want it and wouldn't support it.

**Comment by shibumi** [comment]
@shinji257 Nice project of @yuk7 he even uses microsofts new WSL Distro Launcher

**Comment by yuk7** [comment]
@shinji257 @shibumi 
ArchWSL is not based on Microsoft's official launcher.
based on my alternative launcher written in C.
I think it would be better to base to the official code of Microsoft...

**Comment by Biswa96** [comment]
@yuk7 Please take this as a suggestion. You've used the Arch Linux bootstrap tar.gz file. But I've tried Arch in WSL from the airootfs.sfs (SquashFS file). With the later one I've not to add/edit any configuration file like you did in ArchWSL and the prompt color shows correctly.

**Comment by Biswa96** [comment]
@yuk7 The ArchWSL can be packaged as a Windows Store package.

**Comment by yuk7** [comment]
I just found ArchLinux based on Windows Store package(AppX).
I don't tested yet,but I think it is good.

https://github.com/bilguun0203/WSL-ArchLinux
