### ISSUE TITLE
[discussion]Possible change in permissions of files under BOW when edited by Windows Apps ?

### ISSUE THREAD

**Issue by singam-sanjay** [Microsoft/BashOnWindows#2307]
I've setup a project and its build system inside BOW and would prefer to edit the files through a windows app like MSVC or Atom. I might also use git plugins in these apps.

Since the Windows and Linux set different file permissions (Linux seems to be more restrictive, but I'm not sure), can editing the projects through windows apps render the files inaccessible to Linux commands ?

**Comment by therealkenc** [comment]
You can't access files in WSL LxFs (`/home/you`) from Windows MSVC or Atom, and there is an oft cited blog post on that [here](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/).

Thus in your scenario you'll be doing all your work in DrvFs (`/mnt/c/Users/you`) on the WSL side and all the perms will be 0777. [This ruffles a lot of Linux and Mac people's feathers because it makes their `ls --color=auto` look wrong on the WSL side, but it otherwise matters a lot less than they think.] Nothing on the WSL side will change the umask, and nothing on the Windows side cares. Git will be fine too; you want `git config core.fileMode false`. Symbolic links are a lost cause at the moment but if you just don't use them you'll be fine.

**Comment by jakegt1** [comment]
If you have files inside of WSL/BOW do not edit these through windows apps as they will likely damage the file and possibly put it into an unusable state.

If you want to edit things using windows apps but build them using WSL, i'd recommend that you place them inside part of the windows file system, such as your windows user directory (which you can then access through _/mnt/c/Users/(user)/.._ in WSL.

**Comment by singam-sanjay** [comment]
Thank You @therealkenc and @jakegt1 !!

@therealkenc Please repost your answer if you can, it was useful, especially in directing me to this [post](https://blogs.msdn.microsoft.com/commandline/2016/11/17/do-not-change-linux-files-using-windows-apps-and-tools/).

**Comment by therealkenc** [comment]
Sorry, hit the wrong button. Mostly I had just said 0777 perms on DrvFs won't be a problem. Nothing on the WSL side will change them and nothing on the Windows side cares. Git will be fine; use `git config core.fileMode false`. Symbolic links are currently a lost cause, but that isn't a problem if you don't use them. Good luck and have fun with your project.

**Comment by singam-sanjay** [comment]
Thank You ! :)
