### ISSUE TITLE
Repo sync timeout error

### ISSUE THREAD

**Issue by Uldiniad** [Microsoft/BashOnWindows#2334]
I've recently installed WSL and bash and am trying to download AOSP source code but I keep getting timeout errors on different repos (sometimes the same ones, sometimes different). forcing repo sync to have only 1 active thread at a time with parameter -j 1 helps a little (still happens but less frequently) but it slows down the whole process by a lot obviously. Would like it to disappear completely though :)
Any help/suggestions appreciated

https://vomitb.in/l7d9tKBT5Q

* Your Windows build number:  Microsoft Windows [Version 10.0.15063]

* What you're doing and what's happening:  follow all the steps described here up to and including repo sync https://wiki.lineageos.org/devices/klte/build

* What's wrong / what should be happening instead: should keep fetching projects and complete the sync without any errors

* Strace of the failing command, if applicable:  way too much output

**Comment by sunilmut** [comment]
@Aelfwin1996 - Thanks for your post. Can you please share your repro steps? The wiki link you have shared is giving me "Page not found" error.

**Comment by Aelfwin1996** [comment]
@sunilmut voila, updated the url. I had used the insert link button instead of pasting the url and it somehow managed to mess it up. sorry for that. should be easy to follow the step to reproduce now

**Comment by sunilmut** [comment]
Thanks. How big is the repository? It has been downloading/syncing for the past 2 hours on my WiFi connection, 15GB downloaded and going. But, so, far I didn't run into any problems with download. How is your internet speed? Are you able to try this on a connection with higher speed and see if it makes any difference?

**Comment by Aelfwin1996** [comment]
The webpage says it is about 20GB of download total according to their website. My download speed is of 2MB/s (15mbps download / 10mbps upload) when downloading the repo. I could try a faster connection but would have to take my desktop to another house which would be somewhat bothersome. And I'd be a little surprised that that would be the issue since I've had a linux distro installed on this computer before and have not had any issues downloading the source code before on it (my internet speed is average for Canada)

I thank you for taking the time to help and try to reproduce the issue :)

**Comment by Aelfwin1996** [comment]
So, I've found a partial solution to this problem. Using the -f flag. I force the sync to not abort upon failure to fetch. Running repo sync a couple times with the flag helps to get the packages that were not able to be fetched on previous attempts. I will close this issue, but I must note that it would probably be worth investigating further if others have this issue of curl (28) timeouts

**Comment by Aelfwin1996** [comment]
![capture](https://user-images.githubusercontent.com/17321823/28500266-0ad3d600-6f93-11e7-8511-5a103d81f258.PNG)
This snip is from my windows task manager.
Could it be that the timeout errors happen due to the amount of connections repo sync creates and does not terminate when done? Because if that is the case then I can understand why there are timeouts. My internet connection speed would be slowing down way too much and then it would fail to connect to servers and the timeouts terminate the connections with fatal errors which cause the sync to fail in the end anyway.
If this is the case, what could be done to improve git on wsl? Because it is not acceptable to have so many processes/connections open without terminating successfully when done.

Let me know your thoughts on this possibility.

**Comment by Aelfwin1996** [comment]
For future reference (if this issue is not solved officially), here is my partial solution:
1. Use parameters -j1 for one active thread at a time and the -f flag to force sync to keep syncing other projects instead of stopping if it encounters errors (timeouts).
2. If there were errors but you know all repos have been fetched after many retries, the -l flag will checkout the files without having to go through the whole sync (that may fail).

Still waiting to hear from Microsoft on what is causing the issue and how it can be fixed

**Comment by Uldiniad** [comment]
I no longer have the issue now that I have updated my computer to the Fall Creator's update.
I can't say if it has officially been fixed or not, but I do know that I have not heard anyone else having the issue apart from me.
Therefore, it should be safe to move on and assume that it is either very rare or fixed.
