### ISSUE TITLE
GPU Support in WSL Survey

### ISSUE THREAD

**Issue by cwilhit** [Microsoft/BashOnWindows#2422]
WSL community,

We are currently looking into supporting GPU in WSL. We're working on gathering the scope of the request and understanding what work you're trying to accomplish. So we've created a survey to capture this feedback. It would be _super_ helpful to us if you fill out this quick form found here:

https://www.surveybuilder.com/s/ykXHp

The survey will be open through August 27th

**Comment by therealkenc** [comment]
Two cents because saying it will make me feel better:

- The User Voice stats are skewed by the big thumb put on the scale.
- Known bugs don't get User Voice hits.

So sure, do CUDA. It has the most votes. But please don't burn all your cycles on the effort. There is a _lot_ of kernel surface to work on that would enable far more scenarios for numerically more developers at a lower engineering effort cost.

**Comment by parthradia** [comment]
Hmm @therealkenc I think implementing CUDA should be a top priority - it will bring a solid number of ML researchers and devs to the platform, thereby increasing the community's ability to find more of those surface level bugs.

**Comment by cwilhit** [comment]
Closing the issue as the survey is now closed.

**Comment by AbhimanyuAryan** [comment]
Any updates? It's 2019

**Comment by NicTanghe** [comment]
anny updates ? it's 2020
