### ISSUE TITLE
Can not install/activate WSL feature

### ISSUE THREAD

**Issue by bluesbrothers123** [Microsoft/BashOnWindows#2571]
Microsoft Windows [Version 10.0.16299.19]

![powershell_2017-10-18_03-13-18](https://user-images.githubusercontent.com/32886785/31695271-587ba316-b3b2-11e7-9313-7f288bea3ea0.png)

* What's wrong / what should be happening instead: It should install/activate WSL feature.

**Comment by jakegt1** [comment]
Can you enable it via the windows features GUI (
![image](https://user-images.githubusercontent.com/6144562/31713103-15aec476-b3f5-11e7-8385-5551da947bc9.png))

**Comment by bluesbrothers123** [comment]
@jakegt1 No I can't. I also clicked that "Tell me how to solve" thing and followed the steps up until it said do clean install which I don't want to do.
![optionalfeatures_2017-10-18_13-14-25](https://user-images.githubusercontent.com/32886785/31713248-5ce1f0c8-b406-11e7-9e98-f61ff531672e.png)

**Comment by bluesbrothers123** [comment]
Okay I fixed it. I think there was a problem with leftover files from other installation of WSL. Because, I had it enabled before FCU but I disabled it for some reason. However, there were some leftover files in the Windows folder. I searched it with Everything search tool "lxss" and "wsl" then deleted all the files that the tool found. 

After that I ran `DISM.exe /Online /Cleanup-image /Restorehealth` and `sfc /scannow` on CMD and it worked.

**Comment by dsanders1234** [comment]
I'm having this same issue, and I have been unable to resolve it.  Perhaps bluesbrothers123 somehow deleted just the right "leftover" file, but I'm not sure which ones those were.

**Comment by dsanders1234** [comment]
@bluesbrothers123 Thank you for your help.  I was able to get it working by following these steps:

1. I used regular windows 10 search of windows folder for lxss and wsl.  I had to change owner/permissions in order to delete the various folders/files (they are set to TrustedInstaller).
2. I then ran "DISM.exe /Online /Cleanup-image /Restorehealth" and "sfc /scannow" as you suggested from CMD (as administrator)
3. Then when enabling the WSL windows feature, I got a different error code:  0x80073712
4. I ran the windows update troubleshooter:  https://aka.ms/wudiag  which then told me that I had updates (which I did not have prior to doing these steps)
5. After installing the updates, I was then able to turn on/get WSL feature
