### ISSUE TITLE
If install fails, bash will be unusable

### ISSUE THREAD

**Issue by dbrattli** [Microsoft/BashOnWindows#29]
TCP/IP v4 got disabled when upgrading, so I tried to install Bash without networking. The install timed out, and opening bash (installer) again just sent me to c:/windows/system32. In order to get a usable image and shortcut, I had to reinstall using:

1) lxrun /uninstall
2) lxrun /install /y

**Comment by benhillis** [comment]
I haven't been able to repro this, are you still experiencing this issue?

**Comment by dbrattli** [comment]
The scenario is a bit special since I could still download over IPv6, while some other stuff fails since IPv4 is disabled. This is not a problem if it wasn't for many of the insider builds disabling IPv4. The way I could repo this is by simply disable WIFI after downloading but before filesystem extraction:

1) lxrun /uninstall
2) Run bash.exe (NOTE: disable WIFI right after download, while extracting the filesystem).
```bash
C:\Users\dbrattli>bash
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Type "y" to continue: y
Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Installation successful!
Restoring Default UNIX user: dbrattli
Enter new UNIX password:
Retype new UNIX password:
passwd: password updated successfully
Failed to create shortcut to bash.exe
The environment will start momentarily...
```
3) Run bash.exe
```bash
dbrattli@WIN10-VMWARE:/mnt/c/WINDOWS/system32$
```
Bash shell is now unusable and will take us to `C:\Windows\system32`.

**Comment by benhillis** [comment]
@dbrattli Can you clarify what you mean by bash is unusable? In your above repro it looks like bash is working and the current working directory is set to c:\windows\system32.

The error you're seeing about not being able to create the start menu shortcut is expected given your repro disabling wifi during install.  If for some reason downloading the bash icon fails we print that error instead of unwinding the entire install process.  FYI all that shortcut is is a link to c:\windows\system32\bash.exe (it also passes the ~ argument which means "start in my user's home directory).

I'm going to go ahead and close this as by-design.
