### ISSUE TITLE
Updating RubyGems

### ISSUE THREAD

**Issue by TheAggressive** [Microsoft/BashOnWindows#293]
When I go to update RubyGems using this command `gem update --system` I receive this error message.

```
Updating rubygems-update
Fetching: rubygems-update-2.6.4.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /var/lib/gems
aggressive@AGGRESSIVE-PC:~$ gem update --system
Updating rubygems-update
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /var/lib/gems
aggressive@AGGRESSIVE-PC:~$ gem install rubygems-update
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /var/lib/gems
```

**Comment by hut8** [comment]
I noticed in the most recent build that you now get a "regular" non-root account, which is what you're using. So this seems expected, since /var/lib is probably not writable by your user (right)? Doesn't seem like a bug. You could use `sudo`, or try rvm, but RVM gave me a couple issues pertaining to a known unimplemented /dev/pty (or something)

**Comment by TheAggressive** [comment]
Correct, using `sudo` was the solution. Brain fart moment.

Thank you @hut8
