### ISSUE TITLE
What is the best flow of working with git - is it safe to use linux git on a "windows repository"

### ISSUE THREAD

**Issue by ophiry** [Microsoft/BashOnWindows#309]
related to the issues of using the different file systems:
1. editing linux files from windows isn't supported
2. the windows file system doesn't support all the linux file system features

So a typical setup for a development environment (assuming you want a visual IDE) will be:
1. use a windows folder for source files
2. use a windows based IDE
3. run and compile from bash

What about git?
working with windows git should probably work, but has some limitations if you want to work in a "scriptable" environment

Is working with the linux git binary on a windows file system repository safe?

**Comment by MadcowD** [comment]
My preferred environment thus far has been to use symlinmks to a development folder on my C: drive. That way I open up bash and `cd` straight into my `workspace`. For whatever it's worth, yes windows IDE, but there have been some clever ways to get my IDEs to compile using bash. I made the following batch script in my `workspace`:
	bash.exe -c "%*"
This lets me invoke `LaTeX` by just calling `bash.bat latexmk ....` instead of using custom syntax shifting with the `-c-.

Git is totally fine! It works like a charm and it's even faster. The makers of Git decided to go line ending agnostic, regardless of platform. So `sudo apt-get install git`, and `cp /mnt/c/Users/<You>/.ssh ~/ -r`.
Good luck!

**Comment by ophiry** [comment]
for future reference - [issue 184](https://github.com/Microsoft/BashOnWindows/issues/184) covers the problems (and solutions) I had with using a windows git repository from linux
