### ISSUE TITLE
Installation fails when creating a user

### ISSUE THREAD

**Issue by LKS90** [Microsoft/BashOnWindows#319]
Hey there!

I just installed the Windows 10 Insider Preview Build 14332.rs1_release.160422-1940 and tried using the Windows Bash shell. Problem is, the user creation fails and the Bash on Ubuntu for Windows application simple doesn't open anything. I have also tried to use the /setdefaultuser option of LxRun.exe but this fails as well, this time it at least provides an error code:

    Error: 0x80040306

![image](https://cloud.githubusercontent.com/assets/11182340/15001648/abfdeef2-1199-11e6-98a4-3e24a53e89f4.png)

Any help would be appreciated :).

Greetings
Lukas

**Comment by benhillis** [comment]
@LKS90 by chance are you running a non-English version of windows?  There normally would be an error print for that error code.

`Unsupported console settings. In order to use this feature the legacy console must be disabled.`

1. Open cmd.exe
2. Right click title bar -> Properties -> Uncheck Use legacy console
3. Click OK

**Comment by LKS90** [comment]
@benhillis my system is in english, I might have switched it from german at some point though.

Unticking the "legacy" option solved the problem, thanks!
Quick question: Where did you find the information for the Error Code? I googled 0x80040406 but came up with (I think) unrelated results

**Comment by benhillis** [comment]
@LKS90 Great I'm glad it solved your problem!

The error code is actually just defined locally in our project so we can print actionable error codes to the user.  Once our error message are localized you should see the correct string error message.  We basically have a big switch statement that maps error codes to strings.  The actual error code of the API that fails due to legacy console is very generic (E_INVALIDARG I think) so we had to define our own error code.  Hope that makes sense :)
