### ISSUE TITLE
Installing gevent via pip results in a segmentation fault of gcc

### ISSUE THREAD

**Issue by lypanov** [Microsoft/BashOnWindows#332]
pip install gevent just stops for me (maybe it's just extremely slow?) during install.

**Comment by benhillis** [comment]
I tried this but I'm getting a strange error about not being able to find "Python.h".  I may be doing the wrong thing, can you provide me with the apt packages you installed and exact command you're using?

**Comment by lypanov** [comment]
sudo apt-get install python-pip python2.7-dev
Then 
pip install gevent
Does the trick for me. However the error message has now changed! I actually see the reason why, and it's a SEGV. I'm seeing quite random SEGVs with the latest build, some come and go, but this one is reproducible for me.

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  I tried the repro steps on a recent internal build and it seemed to install fine since the command ended with "Successfully installed gevent greenlet\nCleaning up..." and gevent showed up in `pip list`.  We recently fixed a few syscalls that could corrupt user mode state, and the fixes should be out in the insider builds soon.

**Comment by benhillis** [comment]
The fix is now available in the most recent Windows Insider build (14376).
