### ISSUE TITLE
reset command resizes window

### ISSUE THREAD

**Issue by mths0x5f** [Microsoft/BashOnWindows#361]
Annoying but not critical: `reset` command resizes window (when _maximized_) just how old cmd would maximize, probably due how the "terminal emulator" interprets escape codes. I'm used to resetting the screen every time, so I found out this a little annoying. `clear` works just fine.

**Comment by onrx** [comment]
Not sure if its related but, with terminal window is maximized, when I open vim (local or remotely) the window gets resized (window remains on "maximed" status tho). 

At first I though I could change some vim setting to prevent this but it wouldn't help much because when I close vim it gets resized again to the default terminal size like 20 rows X 80 cols, something like that...

**Comment by arcanis** [comment]
It also causes issue when leaving emacs (since it reset the screen too).

**Comment by benhillis** [comment]
I am no longer able to reproduce this on the most recent Insider build.

**Comment by mths0x5f** [comment]
This was indeed fixed. Ty.
