### ISSUE TITLE
is it possible to use msys2 console replace bash own console?

### ISSUE THREAD

**Issue by callmelanmao** [Microsoft/BashOnWindows#465]
before windows provide bash, i use msys2 console as my work env,  it very easy to copy and pase use 'ctrl + ins' and 'shift + ins', and i can make it fullscreen without scrollbar, it's  really cool, if cannot use other console replace windows bash, is there any way to config bash console in advance to get what i want, thanks!

**Comment by fpqc** [comment]
Nope, bash is a Windows console application, and right now bash.exe is eating up all of the ANSI control codes that should be going to xterm, and also, since it runs through conhost, there is no way to have it send back the proper xterm ANSI control codes for things like mouse input.  

If you install ConEMU and mess around with it, though, you can set some of the stuff that you want up through keyboard and mouse overrides and the like (for ctrl+ins and shift+ins).

**Comment by callmelanmao** [comment]
@fpqc 

thanks for help, close it now
