### ISSUE TITLE
can't change default shell

### ISSUE THREAD

**Issue by SeayXu** [Microsoft/BashOnWindows#477]
I have installed the Zsh,and run command `sudo chsh -s zsh`,but zsh not work.

```
root@XY:~# echo $SHELL
/bin/bash
```

windows 10  preview 14352

what should i do?

**Comment by benhillis** [comment]
For a workaround you can launch zsh from your .bashrc file. We don't run login which is the component that normally sets those things up.

**Comment by russalex** [comment]
Another option I have seen people do is use the command `bash -c zsh`.

**Comment by SeayXu** [comment]
@russalex @benhillis Thank you all.
I have resolved the problem.
My way is add  command `bash -c zsh` to .bashrc file.

**Comment by fpqc** [comment]
@seayxu Russalex meant bash.exe -c /bin/zsh

**Comment by SeayXu** [comment]
@fpqc I know,but this way is not what i want.
it is not work when opened command windows after closed

**Comment by fpqc** [comment]
Then you should just put /bin/zsh in .bashrc. No need to do bash -c in that case.

**Comment by SeayXu** [comment]
@fpqc yes,i get it.
Thank you!

**Comment by radum** [comment]
```
# Launch Zsh
if [ -t 1 ]; then
exec zsh
fi
```

This might be better ;)

**Comment by KornbergFresnel** [comment]
@radum his method is the best and easiest one to solve this issue

**Comment by KoldFuzion** [comment]
Along with everything above, to get my terminal to open to zsh, I had to go to

Terminal > Preferences > General

Then change the "Shells open with:" option to: Default login shell
<img width="717" alt="screen shot 2018-02-14 at 1 48 56 pm" src="https://user-images.githubusercontent.com/8559810/36230007-e970b3a0-118d-11e8-956f-71ee9bec6dd0.png">

**Comment by therealkenc** [comment]
This one was actually dupe #477 way up top but was never marked as such. Work-around was to `exec zsh` inside `.bashrc`, or launch it by whatever creative means you like. These days just `wsl.exe` will respect the default shell.

**Comment by onwsk8r** [comment]
So these workarounds you guys have look like they were written by Windows guys 😛
The first method - `bash -c zsh` - opens a new bash shell which then executes ZSH. In other words, it runs bash, runs bash, and then runs ZSH. It would be akin to opening a `cmd.exe` session and typing `cmd.exe powershell.exe`.
The `exec` in the second method is unnecessary because it `exec`s the text that comes after it. `exec zsh` and `zsh` do the same thing.

What I have in my `$HOME/.bashrc` is
```
 [[ $- == *i* ]] && $(command -v zsh) || echo "ZSH is not installed"
```
**What this does**:

- `[[ $- == *i* ]] &&` says "if this is an _interactive_ session (ie not started by a script), do what comes next". If not, continue as if nothing happened. This is a safeguard because while Bash scripts are 99% compatible with ZSH, some integral parts such as arrays and strings have some significant differences that might make your script take a dump. 
- `$(command -v zsh)` runs the command `command -v zsh`, which will print the full path to ZSH (eg `/bin/zsh`) if there is a binary with that name on the path. The `$()` executes the output of whatever is between the parens- in this case the full path to ZSH or nothing if it cannot be found. The `$()` will return the exit status of that command if it is nonzero.
- `|| echo "ZSH is not installed"` says "if that last command returned a nonzero exit status" (`||`), "execute whatever follows". In this case, what follows is a friendly message telling you ZSH is not installed. 

HTH!

**Comment by therealkenc** [comment]
> What I have in my $HOME/.bashrc is...

...unnecessary.

[`chsh(1)`](http://man7.org/linux/man-pages/man1/chsh.1.html) has worked since the 2017 Fall Creators Update via `wsl.exe`. HTH.

**Comment by std4453** [comment]
@therealkenc I'm getting `/bin/bash` on 2 different devices running 1803 17134.523, after restarting LxssManager and rebooting. Can anybody verify the problem?

**Comment by therealkenc** [comment]
What does the following return for you:
```
C:\ wsl.exe /bin/dash -c "grep yourusername /etc/passwd"
```

Regardless, concrete suggestion would be to get yourself up to 17763. 17134 is almost a year old and I don't have one handy to look. There have been all kinds of changes to the whole WSL interop infrastructure since then, and what was fixed/improved in what release is pretty nebulous. I do know `chsh` was addressed [way earlier](https://github.com/Microsoft/WSL/issues/846#issuecomment-300836949) but getting onto the current release is a sensible place to start.

**Comment by adaaaaaa** [comment]
@radum 
i'm using you method...but how about this?
➜  data git:(master) ✗ chsh -s /bin/zsh
正在更改 captain 的 shell。
密码：
chsh: shell 未更改。
➜  data git:(master) ✗ chsh -s /bin/bash
正在更改 captain 的 shell。
密码：
shell 已更改。
➜  data git:(master) ✗ echo $SHELL      
/bin/bash
➜  data git:(master) ✗ chsh -s /bin/zsh 
正在更改 captain 的 shell。
密码：
shell 已更改。
➜  data git:(master) ✗ echo $SHELL     
/bin/bash
➜  data git:(master) ✗
