### ISSUE TITLE
No sudoer's password prompted after reboot

### ISSUE THREAD

**Issue by lateau** [Microsoft/BashOnWindows#485]
Reproduce:
```sh
$ sudo su -
# rm /init         # I don't know this related to no sudo password.
```
And reboot and launch first Bash via start menu.
```sh
$ sudo ls   # no password prompt
my files directories here
```
Launch second Bash.
```sh
$ sudo ls
[sudo] password for lateau:
```
Reboot again. Launch Bashes. Only first Bash does not prompt sudo password.

**Comment by benhillis** [comment]
When you run sudo and provide a password there is a configurable timeout before you are prompted to type your password again.  See [this page](https://scottlinux.com/2012/08/04/change-sudo-default-password-timeout/) for more info.  Sudo modifies a file with a change timestamp, and does a stat each time "sudo" is run to detect if the user needs to supply their password.  What's happening in your above repro is you've rebooted your machine and re-launched bash within this timeout window.

I assume boot or login usually clears these timestamps, but we're not running those binaries.  I'm inclined to resolve this as by-design since we don't run login or the Ubuntu init process but I'm open to hear your thoughts.

**Comment by benhillis** [comment]
Closing this out as by-design.
