### ISSUE TITLE
question: to root or not to root; security? best practice?

### ISSUE THREAD

**Issue by jokeyrhyme** [Microsoft/BashOnWindows#53]
At least with the initial WSL + Ubuntu beta, we are given a root prompt. Many things that work with unprivileged users on a real Ubuntu box (e.g. SSH, etc) strictly only work under root in WSL + Ubuntu.

Does the usual "principle of least privilege" that I would normally follow in Linux apply here?

It seems like all the dangers of using root all the time still apply here: e.g. running `npm` as root could execute a malicious install script, capable of doing much more nasty stuff as root.

Should we be adding a new user immediately and switching to that lesser-privileged user?

Should WSL + Ubuntu offer to make such a non-root user for us on first run? Should a non-root user become the default?

**Comment by filipeaguiar** [comment]
Well, I created an user with `adduser` and put him in the *sudo* group using `adduser <user> sudo`.

Since the WSL is aimed to us, developers, and we all know that _root_ isn't ideal to use in a daily basis, I think that this is fine, for now.

Once the WSL is well stablished, maybe this would present itself as a problem.

**Comment by hfaran** [comment]
I also immediately made myself a new user out of habit with:
```
adduser <username>
adduser <username> sudo
```
And as opening bash results on login to root, I created this simple alias to jump into my created user: `alias u='su - hfaran'`

All that being said, I believe the semantics of what root means in WSL are just a little off because the install actually lives isolated in the app data of each specific user. Unless you're an admin on the machine, you can't look at other Windows users' Linux filesystems.

**Comment by jokeyrhyme** [comment]
> the install actually lives isolated in the app data of each specific Windows user

I thought as much. What does `rm -rf /` do from within WSL as root? If it isn't possible to completely hose (or install malicious software within) the host Windows environment, then maybe root-only within WSL isn't so bad. /shrug

**Comment by jolibert** [comment]
You are root on a restricted environment: your user.
The only things you can arm on is WSL and is your own process.
For exploits or other stuff the environment run on another layer.

If you want to hack around, make a guess all typical calls are protected.

Those people bring us bash on windows and even if you think whatever, it is a very smart move.

**Comment by russalex** [comment]
Interesting conversation.  We will be adding some documentation around how users work in the future, but I wanted to call out a few things here.

1) The idea of root is separate from the Windows user.  That is, running as root in a a normal cmd prompt cannot access anything restricted to Windows admin privileges.
2) If you run bash at an admin cmd prompt, or in admin mode, you will have the same permissions in Windows as if you ran an admin cmd prompt.
3) The WSL will honor root & user access within Linux directory structure.

What does this mean for running as root.  Basically, our guidance will be to create a user and run under the context.  That said, we also believe in choice and know that there are times when you'll want to run as root so that should be possible as well.

So the community knows where we are going here: we will be releasing an update soon with better user support.  In short we'll ask people to create a Linux user on first run.  When launched, the WSL will start under that user's context.  If someone does not want to run as a user, they can make their default user 'root' and have the same experience we have today.

I'm going to close this one since it's a discussion and not really an issue.  We have people working on getting a good forum in place for these types of conversations.  Expect to see something from us soon on this specific topic and then we can have the discussion on what people like / don't like about the implementation.

**Comment by jokeyrhyme** [comment]
Yep. Closing makes sense. I wasn't reporting a bug, and we're still free to converse of course (until the other forum exists).

Good to see some feedback. I think we all understand that this is very new, and it's super exciting to see the direction WSL is heading in. Cheers! :D

**Comment by dreyks** [comment]
@jokeyrhyme after a fresh lxrun install I have `1000:1000` owner on `/data` and `root:1000` on `/mnt`. When I create a user via `adduser` it assings uid 1000 to it, so that that folders are owned by it. Is it ok or should I assign another uid for this user manually?

**Comment by benhillis** [comment]
Great question on the uid and gid values. We have some hardcoded uid / gid values that need to be fixed. I'll be going through these today and change the owners so they match real Ubuntu. I think that will mean these will be changed to root in most cases.

**Comment by dreyks** [comment]
Oh, that's nice. Thanks for fast feedback.
