### ISSUE TITLE
int 0x80 doesn't work

### ISSUE THREAD

**Issue by kpengboy** [Microsoft/BashOnWindows#537]
Attempting to use the `int 0x80` system call interface, which is present even in 64-bit mode, results in the program getting killed or similar.

**Comment by dethoma** [comment]
This is a known limitation of WSL in that we don't support 32-bit applications. Given most applications are 64-bit, this has not surfaced to the top of the priority list.

**Comment by pcordes** [comment]
This is like an x86-64 Linux kernel with `CONFIG_IA32_EMULATION` disabled.  Some Linux distros build their standard kernels this way, so even on real Linux you shouldn't depend on being able to use it from 64-bit user-space.  (Or at least it's [not unusual to find Gentoo systems configured that way](https://lists.gt.net/gentoo/user/322973).)

Linux does officially support using `int 0x80` from 64-bit user-space if it's enabled, but it's not recommended and rarely useful for anything.  See [What happens if you use the 32-bit int 0x80 Linux ABI in 64-bit code?](https://stackoverflow.com/questions/46087730/what-happens-if-you-use-the-32-bit-int-0x80-linux-abi-in-64-bit-code).  The biggest limitation is that you can't use 64-bit pointers, for example `push "test"` / `mov rcx, rsp` / ... / `int 0x80` will return `-EFAULT` instead of printing a string from the stack, because `ecx` isn't a valid pointer for 32-bit `sys_write`.

AFAIK, the only real use-case for `int 0x80` in 64-bit user-space is doing weird and crazy things with segment registers, like maybe doing a far-jump to a 32-bit code segment, where the `syscall` return path might set your segment registers back to fixed values instead of restoring the values from the entry point.
