### ISSUE TITLE
Can't find kernel headers for 3.4.0

### ISSUE THREAD

**Issue by mbeijen** [Microsoft/BashOnWindows#549]
I'm not sure if it is even possible to do what I want - I want to run vagrant inside Bash on Ubuntu on Windows. And I'd like to run it with the VirtualBox hypervisor. This means that Ubuntu on Windows needs to do the virtualizing :dancers: 

The problem I ran into is that I need to load `virtualbox-dkms` in the running kernel, but Ubuntu on Windows does not seem to provide these:

~~~~
$ sudo apt-get install linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-headers-3.4.0
E: Couldn't find any package by regex 'linux-headers-3.4.0'

**Comment by aseering** [comment]
Ooh, that's an interesting use case.  Unfortunately, though, it probably won't work:  VirtualBox has (and, I believe, requires) custom kernel modules; WSL only provides a Linux userspace at present, not a Linux kernel-space.

Could you install Windows Vagrant and run that from Linux?  There's a tool out there (mentioned elsewhere in this bug tracker) that lets you call Windows tools from Linux.

**Comment by mbeijen** [comment]
Sure, it needs the kernel module `virtualbox-dkms`, that was the one I wanted to load. 
I understand now I can't load any modules in the Bash for Ubuntu for Windows kernel. Thanks!

**Comment by TheAggressive** [comment]
I'am also facing this issue. I can't vagrant up using windows installed virtualbox. can't install virtualbox on ubuntu side do to this. Is there a working fix for this?

Thanks

**Comment by aseering** [comment]
Vagrant runs nicely on Windows; it doesn't need WSL.  Could you just install the Windows version?

**Comment by TheAggressive** [comment]
I installed the windows version but bash can't see that it looks like.

**Comment by aseering** [comment]
You should be able to use it via "cbwin", as discussed on #333

**Comment by netcreatoreu** [comment]
Not good news.

We use VirtualBox + Vagrant + Ansible... And we see we still need Linux host :(
On Windows we cannot configure our development env (python, pip + depends). Sad.

**Comment by TheAggressive** [comment]
Same here

**Comment by aseering** [comment]
@netcreatoreu -- VirtualBox, Vagrant, Ansible, and most Python things all work directly on Windows.  I'd be curious to know more about exactly what piece of your workflow you're having trouble getting to work there.

**Comment by HeathNaylor** [comment]
It is fine for them to work directly on windows, but the have to have 2 separate terminals open to interact with Windows applications and Linux userspace applications is limiting. My big issue currently is that tmux in Cygwin is very slow when sshing into a vagrant box, I was hoping to use bash to do this but I am unable to use the `vagrant ssh` command as Virtualbox is non-configurable.

**Comment by aseering** [comment]
Ah, ok -- so you do have applications (other than those?) that require Linux.  Makes sense.

**Comment by katharinegillis** [comment]
Ansible doesn't support Windows as the control machine, which is how a Vagrant run on directly on Windows uses it. Cygwin has issues where forking processes don't work consistently from session to session. I've had Vagrant/Virtualbox/Ansible setups work perfectly one day, and fail the next, with no change except the Windows machine being shut down for the night. It would be perfect if we could run Virtualbox on WSL, so our entire development stack could be run from there, but I think a work around in the mean time (intending to test this soon) should be to run Vagrant directly on Windows, but comment out the provisioning, and run the Ansible playbook from WSL as a separate command since it just needs to have network access to the Vagrant box to work, not direct program access. Not as clean as just doing "vagrant up", but miles ahead of the inconsistency that showed up when I tried to use Ansible in Cygwin.

**Comment by AnneTheAgile** [comment]
Cross-ref: Uservoice requesting ansible; https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13741026-ansible

**Comment by MikeTheCanuck** [comment]
As an alternative/workaround, I have made peace with a [hybrid Windows/Bash solution](https://mikethecanuck.wordpress.com/2016/08/16/what-ive-learned-setting-up-bashubuntuwin10-for-ansible-vagrant-virtualbox/) for running vagrant + virtualbox + ansible, relying on TCP/IP connectivity across the subsystems.  Yes, it requires me having CMD and Bash open to interact with the different subsystems' tools, but it works for all usages I've tried so far.

**Comment by screech** [comment]
Wouldn't a solution to add /dev/vboxdrv and ferry this to the windows Virtual box installation be sufficient. The info needed is (I assume) all available in the Windows kernel subsystem.

**Comment by daveespo** [comment]
My use case: I, too, am trying to install vagrant and VirtualBox inside WSL because the shared folders feature of VirtualBox is a toy and any project that tries to expose a large number of files to their vagrant VM via shared folders collapses under its own weight. For example, Ruby on Rails apps monitor all files for changes on each web request so once you have a large number of files, web response times go into many seconds, and even 10s of seconds if the project is large enough.

The documented workaround is to use NFS to expose the filesystem to the vagrant VM ... but since there's no NFS dameon on Windows, there are workarounds there too .. but they have to run elevated and are maintained by some random 3rd party ... My hope was that I could run nfsd in WSL and expose my project files to the VM in that way.

Reference material:

https://www.vagrantup.com/docs/synced-folders/nfs.html

https://hollyit.net/blog/windowsvagrantwinnfsd-without-file-update-problems

https://github.com/winnfsd/vagrant-winnfsd

**Comment by aseering** [comment]
For what it's worth, I've found Linux's CIFS (SMB, samba) support to be pretty solid these days as well.  That's Windows's native file-sharing protocol, so the daemon ships with Windows and is configured through the Explorer UI.

**Comment by daveespo** [comment]
Thanks for the suggestion .. we're actually building an app with a Javascript front end (Rails back end) and the thing that's probably killing us the worst is node_modules since it's a monster directory. Additionally, there are issues with symlinks (npm install likes to create them) on shared folders through Vagrant (unless you kick off your vagrant VM in an elevated command window) 

Ultimately, we got this to work and it's relieved a lot of the unhappiness about the performance of vagrant:

https://medium.com/@dtinth/isolating-node-modules-in-vagrant-9e646067b36#.cdk05pz01

We'd still like to find a way to make WSL work .. but after I wrote yesterday's comment on this ticket I tried installing the nfs-kernel-server package and enabling NFSD inside WSL only to discover that ran afoul of the same kernel mode restriction ...

**Comment by Rukaiya** [comment]
![image](https://cloud.githubusercontent.com/assets/20462626/26034615/bd9c1e38-38d8-11e7-8c47-5baba5ecf0aa.png)
I gotta same problem on wsl
