### ISSUE TITLE
Midnight Commander - mouse wheel is not working

### ISSUE THREAD

**Issue by SerjCh** [Microsoft/BashOnWindows#569]
Subj. I think this is after Windows 14371 update & mb new console updates.
Far Manager also MWheel is not working, but in legacy concole all fine. Can't check MC in legacy cause Bash need new console.

And may be exists any reg key to fix this asap?

**Comment by fpqc** [comment]
Pretty sure bash.exe does not support mouse input yet, even in 14371.  I checked the changelogs.

I wrote up a kinda slick workaround using rxvt-unicode-256color in my answer to this:

https://github.com/Microsoft/BashOnWindows/issues/531

**Comment by WallyCZ** [comment]
Also Shift key does not work for me in mc (f.ex. Shift+F4)...

**Comment by zadjii-msft** [comment]
I believe this should be in insiders by now, @SerjCh can you confirm?

**Comment by fpqc** [comment]
@zadjii-msft I know that you guys at the console team don't have your own little release notes page, but maybe for now you could ask Russ to post your release notes up with the WSL ones? I ask because this happened one other time, when the WSL team posted up that there were no changes one week, and then Rich posted up the 24-bit color info, which was technically true that there was no upgrade to WSL but a huge upgrade to the console.

**Comment by SerjCh** [comment]
@zadjii-msft i'm on win 8.1 and Ubuntu now, sorry =) have no insider build atm

**Comment by lilred** [comment]
As of 14965 this is working beautifully!

**Comment by zadjii-msft** [comment]
Fantastic, I'll close this then.

@fpqc to be honest, there haven't been a whole lot of feature updates recently that would need any release notes posted, mostly bugfixes and work going on behind the scenes. The only reason this feature didn't have a post is due to us losing track of which release it actually came out in
