### ISSUE TITLE
emacs Ctrl-SPC default mark key-binding not working

### ISSUE THREAD

**Issue by MRFaria** [Microsoft/BashOnWindows#583]
Which means I can't highlight things in emacs as shift arrows don't work either. 
I tried setting set-mark-command to Ctrl-x-g which fixes the problem but I would really prefer Ctrl-SPC as I am so used to it.

insider version: 14366

**Comment by fpqc** [comment]
Another console problem.  

If you don't mind running XMing, try my workaround using rxvt-unicode-256color for much better XTerm support: https://github.com/Microsoft/BashOnWindows/issues/531

**Comment by gantlion** [comment]
I can't seem to be able to automatically start the console with bash.exe ~ -c "(DISPLAY=:0 urxvtdc &)",
where exactly do I put it?

**Comment by benhillis** [comment]
I always add the below to the bottom of my ~/.bashrc 

export DISPLAY=:0.0

**Comment by fpqc** [comment]
@gantlion You need to leave at least one bash.exe console window open, or the LXsession host will shutdown the rxvt daemon.  That's why I suggested running an idle copy of bash.exe on a second virtual desktop to keep it out of your face.  Ideally MS or some independent dev with more Windows dev skill than I will give us something like an lxsession manager in the notification tray to allow manual shutdown mode for the lxsession host service (so you can run daemons in the background like rxvtd or sshd, which is iirc supported since they added pty support recently).

**Comment by pnegry** [comment]
This one is a bit embarrasing considering Kevin Gallo used emacs at microsoft build ;) 
I'd also note that Ctrl-@ doesnt work either for me.

Is there a combination of flags that can be enabled on the conhost properties to allow ctrl-space to work, because the 'Quick Edit Mode' and 'Enable Ctrl key shortcuts' options aren't explained.

**Comment by zadjii-msft** [comment]
It looks like there are some recent changes in kernel-land that actually re-enable C-Spc, C-@, C-a, etc, so shout out to bperkins for that fix!
