### ISSUE TITLE
Open Windows Applications from Bash Shell

### ISSUE THREAD

**Issue by danielrasmuson** [Microsoft/BashOnWindows#589]
How can I open "File Explorer" or "Sublime Text" from the bash shell?

Wasn't able to find an answer to this question.

**Comment by aseering** [comment]
Hi @danielrasmuson -- unfortunately, WSL doesn't provide a direct way to do this right now.  That issue is tracked by #333 .

There's a third-party app called [cbwin](https://github.com/xilun/cbwin) that adds this functionality.  You have to find the Windows .exe file that launches File Explorer (I think that's just "explorer.exe"?) or Sublime Text; then you can use cbwin to open that .exe file.

**Comment by danielrasmuson** [comment]
Thanks @aseering. Very helpful.
