### ISSUE TITLE
Be able to launch arbitrary linux binary 

### ISSUE THREAD

**Issue by gegenschall** [Microsoft/BashOnWindows#594]
I think this has already been discussed but it would be nice if we could launch arbitrary linux executables from within windows. That way I could launch my favorite shell (or any other binary) without the need to open a bash window or using the `bash.exe -c /path/to/binary` workaround.
I myself do not use bash but instead use zsh. To be able to launch zsh you can either use `bash.exe -c /bin/zsh` or put `/bin/zsh` into your .bashrc. But either way, this still launches a bash process and is super clunky.

Temporary workaround:
I looked into bash.exe and wrote a small [Python script](https://github.com/gegenschall/wsl-bashexe-patcher) that replaces the call to `/bin/bash` with any binary you like. As far as I can see, the binary name cannot exceed 16 characters but I'm not really sure.

From bash, call it like so:

```
$ wsl-bashexe-patcher.py /mnt/c/Windows/System32/bash.exe /bin/zsh --output zsh.exe
```

Cheers,
gegenschall

**Comment by xilun** [comment]
I agree with you that it is slightly annoying to be forced to go through bash in some cases, but I recently noticed something that mitigates that annoyance a little: it seems that if bash -c "<cmd_line>" is used with a single command for <cmd_line>, bash executes it with an exec (without a prior fork). So at least we don't have an extra bash instance just waiting in the background.

Still, the ability to run any command directly would be interesting for a number of use cases, including of course running other shells where even a transient invocation of bash is not useful, or maybe even setting up a WSL FS with no bash at all in it.

**Comment by fpqc** [comment]
Very cool! @xilun do you think I could convince you to do an outzsh .exe ^.^

**Comment by xilun** [comment]
@fqpc outbash.exe is basically in the same situation as bash.exe is in that regard, because I add an extra bash call (to be performed by the WSL bash). Now I could do an optimization similar in spirit as the one GNU Bash does, and for example when called like `outbash.exe -c "zsh"`, do an invocation of bash.exe -c "OUTBASH=port zsh" instead of what I do now: `bash.exe -c "OUTBASH=port bash -c \"zsh\""`. But to do that, I would need to understand more about the command line (for now I just have to escape properly). So this optimisation is not worth it given the work needed and the relatively low value it provides, because like I said the extra bash is only transient, thanks to the GNU bash optim. So without support from WSL to directly run the executable we want, I see no point in removing just an extra transient bash, given for now, without dirty hacks at least, one (at least transient) bash is already mandatory.

**Comment by fpqc** [comment]
It's fine lol, all good =]

**Comment by Manouchehri** [comment]
Is it possible to set different behaviors based on the file header on Windows? I thought it was all extension based.

**Comment by hut8** [comment]
@gegenschall Just out of curiosity, do you use tmux? When I use `/bin/bash -c /usr/bin/zsh`, `$SHELL` is set to `bash`, and even though I have run `chsh` to set my shell to zsh by default, each new tmux window ends up being zsh!

**Comment by lavacano201014** [comment]
@hut8 `echo "export SHELL=\"/bin/zsh\" > ~/.zshenv"`

then just `bash -c "zsh -i"` and you're effectively in a zsh login shell and everything should come up zsh. (for the record i've used `chsh` too)

**Comment by oblitum** [comment]
@hut8  you may also put in your `.tmux.conf` `set -g default-shell /usr/bin/zsh`.

**Comment by oblitum** [comment]
And I configured a task like: `%windir%\system32\bash.exe ~ -c zsh  -cur_console:p`. Borrowed this tip from https://gist.github.com/MadLittleMods/0e38f03774fb16e8d698175e505f1f3e.

**Comment by benhillis** [comment]
Recent insider builds have added wsl.exe which makes launching an individual Linux binary much easier.  For example:

`wsl ls`

**Comment by lavacano201014** [comment]
I should clarify for anyone coming from Google who needs that command line for some reason: I put that last quote in the wrong spot, it should be before the `>` character. 

Not needed for this bug anymore but you never know what a Google result can help with.
