### ISSUE TITLE
Symlink woes

### ISSUE THREAD

**Issue by kobaltz** [Microsoft/BashOnWindows#6]
While I understand that NTFS does not support Symlinks, it is something that would be extremely helpful. The issue that i've found is that any tarball package that has symlinks will simply be broken in the sense that the link is never created. Granted that packages/installers should be able to work around this, but I've already come across this issue within hours of playing around. I can see this causing several issues down the road.

Think of an installer that installs something to `/opt/software` but creates a symlink to the executable to `/usr/local/bin` so it would be ready for use immediately without explicitly specifying the path.

**Comment by Buck-Rawgers** [comment]
NTFS has supported symlinks since Windows 2000.  [NTFS Junction Point](https://en.wikipedia.org/wiki/NTFS_junction_point)

**Comment by jokeyrhyme** [comment]
Related to #3 and/or #9 ?

**Comment by robertsmieja** [comment]
Look under "Is there any distinction between files in the Linux drive and the mounted Windows drives?" at https://msdn.microsoft.com/en-us/commandline/wsl/faq

**Comment by denisw** [comment]
The inability to have symlinks between the Linux and Windows filesystems is unfortunate. For instance, this means that you cannot create a Python virtual environment on a Windows drive because that requires the venv tool to symlink /usr/bin/python and other stuff into the environment directory. It would be great if this restriction could somehow be relaxed!

More serious, though, is not being able to create symlinks within the Windows mount. Even when running Bash as an administrator, I wasn't able to create, a symlink `/mnt/c/bar.txt` to a file `/mnt/c/foo.txt`. This is absolutely required for installing many Node packages via NPM, for instance.

**Comment by Buck-Rawgers** [comment]
I just created a symlink from ~/home -> /mnt/c/Users/tellm and it worked fine.

![image](https://cloud.githubusercontent.com/assets/6625993/14342877/de03cb84-fc62-11e5-8a62-447aa46dcf0e.png)

**Comment by denisw** [comment]
This direction (symlink from Linux to Windows) indeed works - the other one (symlink from Windows to Linux) doesn't.

**Comment by poizan42** [comment]
There may be a bit of a problem with that since users on Windows by default doesn't have SeCreateSymbolicLinkPrivilege. As I understand this was done because as lots of applications and maybe even device drivers out there may have subtle security issues with symbolic links.

Requiring users to hold a certain privilege to create symlinks doesn't goes well with posix compatibility either.

**Comment by spichardo** [comment]
The issue with symlinks happens when you either try to tar to directory with symlinks   or untar that contains them, look the simple example:

root@localhost:~# mkdir test
root@localhost:~# cd test
root@localhost:~/test# echo "this is a file" > t.xt
root@localhost:~/test# ln -s t.xt link_to_file
root@localhost:~/test# ls -l
total 0
lrwxrwxrwx 1 root root  4 Apr  7 23:43 link_to_file -> t.xt
-rw-rw-rw- 1 root root 15 Apr  7 23:43 t.xt
root@localhost:~/test# cd ..
root@localhost:~# tar cfz test.gz test/
tar: test/link_to_file: Cannot readlink: Invalid argument
tar: Exiting with failure status due to previous errors

**Comment by spichardo** [comment]
and this is also related to #50

**Comment by tinysun212** [comment]
pointed the same thing to #9

**Comment by hacst** [comment]
What @poizan42 mentioned about permissions is exacerbated by the fact that - as far as I understand split tokens in UAC - non-elevated processes of users in admin groups (it's RID based, [msdn](https://msdn.microsoft.com/en-us/library/bb530410.aspx) has the details) can never have that privilege. Even if you edit the group policy to add it for everyone that just gets filtered out with no way to override it. Imho this is a major pita and it has bitten me outside of this specific issue. It makes using symlinks on dev setups (whose accounts tend to have admin rights) nearly impossible. Basically you can make it work for the Guest account but not without elevation for an admin :( Would love to see that resolved.

**Comment by JonHerr** [comment]
I will add to the symlink issue. I tried to install NVM (node version manager) and RVM (ruby version manager) I ran into issues with cannot create symlink to "" Invalid argument. these tools are essential as working with multiple products I need to be able to easily change which verion of node and ruby I am using.

**Comment by MadcowD** [comment]
This issue has been closed #9

**Comment by perlun** [comment]
Related user-voice question: https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13254597-support-for-symlinks-and-long-filenames-in-bash

**Comment by russalex** [comment]
Wanted to update this one since it's one of our oldest threads.

We have much better symlink support checked into our dev branches.  No ETA on when it will hit Insiders, and I expect that the support will roll out slowly (we did not fix all the issues at once).  What I can show is what ran on an internal branch:

```
russ@RUSSALEX-DESK:/mnt/d/temp$ touch file
russ@RUSSALEX-DESK:/mnt/d/temp$ ln -s file filelink
russ@RUSSALEX-DESK:/mnt/d/temp$ ln -s ~ home
russ@RUSSALEX-DESK:/mnt/d/temp$ ll
total 4
drwxrwxrwx 2 root root  0 Apr 19 23:33 ./
drwxrwxrwx 2 root root  0 Apr 19 20:17 ../
-rwxrwxrwx 1 root root  0 Apr 19 23:33 file*
lrwxrwxrwx 1 root root  4 Apr 19 23:33 filelink -> file*
lrwxrwxrwx 1 root root 10 Apr 19 23:33 home -> /home/russ/
russ@RUSSALEX-DESK:/mnt/d/temp$ cd home
russ@RUSSALEX-DESK:/mnt/d/temp/home$ ll
total 24
drwxr-xr-x 2 russ russ    0 Apr 19 19:34 ./
drwxr-xr-x 2 root root    0 Jan  1  1970 ../
-rw------- 1 russ russ 2043 Apr 19 23:03 .bash_history
-rw-r--r-- 1 russ russ  220 Apr 18 18:40 .bash_logout
-rw-r--r-- 1 russ russ 3636 Apr 18 18:41 .bashrc
lrwxrwxrwx 1 russ russ    4 Apr 19 23:32 home -> home
-rw-r--r-- 1 russ russ  675 Apr 18 18:40 .profile
drwxrwxrwx 2 russ russ    0 Apr 19 22:53 tmp/
-rw------- 1 russ russ 1159 Apr 18 18:43 .viminfo
```

**Comment by denisw** [comment]
Awesome! That is pretty much the missing link (pun intended) to make Bash on Windows work for me. Looking forward to seeing these changes in future Insider builds!

**Comment by sunilmut** [comment]
symlink improvements were made in the new Windows build [14328](https://blogs.windows.com/windowsexperience/2016/04/22/announcing-windows-10-insider-preview-build-14328-for-pc-and-mobile/), WSL specific release notes are [here](https://msdn.microsoft.com/en-us/commandline/wsl/release_notes)
If this build resolves the issue, we would like to close this out.

**Comment by hacst** [comment]
Awesome work. Could you talk a bit about how this is implemented technically? Are those symlinks backed by NTFS or something special to WSL? In case of the former I would love to know how the permissions are handled w.r.t SeCreateSymbolicLinkPrivilege and dual/split tokens in admin accounts.

**Comment by russalex** [comment]
@hacst, We have a few more blog posts in the works with one of them being a deep dive into the filesystem.  Stay tuned.

To answer your immediate question, these symlinks are not backed by NTFS.

I'll be closing this issue out soon to keep things clean.

**Comment by drvink** [comment]
This is only barely related, but it has been a thorn in my (and many, many others) side for years, and I don't know where else to bring it up, but: since we're now getting sane symlink behavior in one Windows subsystem, can we please, please, *please* for the love of god, finally correct the behavior in which UAC removes `SeCreateSymbolicLinkPrivilege` from users' tokens if they're in the Administrators group, even if they've explicitly been given the privilege in some other way? Remember, this insane behavior is ONLY applied to members of the Administrators group--if you give a normal user account permission to create symlinks, they can do it just fine, with no need to elevate!

**Comment by russalex** [comment]
@drvink, I feel your pain here and have forwarded this along to the correct team.

Additionally, you should start something over on our [User Voice](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/category/161892-bash).  We have a number of symlink suggestions over there but they are all around WSL.  Getting this as a separate item may be helpful.

**Comment by drvink** [comment]
@russalex, this is wonderful to hear. Thank you so much! I'll add a UV suggestion too.

**Comment by drvink** [comment]
Updating this thread with some good news for anyone who finds it: it is possible to [create symlinks without elevation as of Windows 10 build 14972](https://blogs.windows.com/buildingapps/2016/12/02/symlinks-windows-10/) if "developer mode" is enabled. Thanks again, @russalex!

**Comment by whitecolor** [comment]
I have currently build 15063 on Windows Insiders Preview, I create sysmlink in windows (symlink target is on the same drive) and I can not read it on WSL. When it is going to be working?

**Comment by whitecolor** [comment]
Hm it seems it works but in strange manner: I can not see linked directory when I do `ls -a`, can I can not `readlink /path/to/linked_folder` but I can work with nested folders and files, ls or read them =)

**Comment by nick4fake** [comment]
Hey,

Good work guys, thank you a lot for all your patience bringing this up into windows!

I have just a small follow-up question: what about cross windows/wsl symlinks?

I'd really love the symlink to be created from bash as NTFS symlink on real drive for compatibility.

**Comment by nick4fake** [comment]
Sorry, just saw #353

**Comment by jan4984** [comment]
I have a removable ntfs driver, it worked in a ubuntu, on which symbolic links created. now when I connect the ntfs driver to windows and wsl, the links all not work.

is any way keep my links between ubuntu and wsl?

**Comment by cavaunpeu** [comment]
```
$ cd /mnt/c/foo
$ echo "bar" > baz
$ ln -s baz bazlink

...Open Powershell...

$ PS C:\foo> cat bazlink
bar
```

However, when I:

```
$ cd ~
$ echo "pickles" > skittles
$ cd /mnt/c/foo
$ ln -s ~/skittles skittleslink

...Open Powershell...

$ PS C:\foo> cat .\skittleslink
cat : The file cannot be accessed by the system.
At line:1 char:1
+ cat .\skittleslink
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ReadError: (C:\foo\skittleslink:String) [Get-Content], IOException
    + FullyQualifiedErrorId : GetContentReaderIOError,Microsoft.PowerShell.Commands.GetContentCommand
```
