### ISSUE TITLE
Zero /var/log/lastlog

### ISSUE THREAD

**Issue by fpmurphy** [Microsoft/BashOnWindows#622]
When you install WSL, /var/log/lastlog has a size of 292292 but no actual contents.  Disk space can be saved by simply creating an empty /var/log/lastlog at installation.

**Comment by benhillis** [comment]
Interesting. This file is present in the .tar.gz that Canonical provided us, I'm curious why it's there, since it's all zero'd it essentially takes up no space in the .tar.gz.

We like to run the image they provide us as-is so I'm hesitant to change this, but thank you for the suggestion!

**Comment by bogen** [comment]
Well, /var/log/lastlog is supposed to be a sparse file so deleting it would normally not save space.
See: http://www.noah.org/wiki/Lastlog_is_gigantic

However, this brings up another issue.
If I do this:
```text
dd if=/dev/zero seek=292291 count=1 bs=1 of=foo.txt
```

I expect this:
```text
$ du -h foo.txt
4.0K	foo.txt
```

not this (what I'm seeing in WSL):
```text
$ du -h foo.txt 
288K	foo.txt
```

So the real issue here is that sparse file support is not in place.
