### ISSUE TITLE
nslookup not working

### ISSUE THREAD

**Issue by fishouttah20** [Microsoft/BashOnWindows#66]
```
# nslookup microsoft.com
socket.c:2447: setsockopt(20, SO_TIMESTAMP) failed: Invalid argument
socket.c:1915: internal_send: 158.43.240.4#53: Invalid argument
socket.c:2447: setsockopt(21, SO_TIMESTAMP) failed: Invalid argument
socket.c:1915: internal_send: 158.43.128.72#53: Invalid argument
socket.c:2447: setsockopt(22, SO_TIMESTAMP) failed: Invalid argument
socket.c:1915: internal_send: 194.168.4.100#53: Invalid argument
socket.c:1915: internal_send: 158.43.240.4#53: Invalid argument
socket.c:1915: internal_send: 158.43.128.72#53: Invalid argument
socket.c:1915: internal_send: 194.168.4.100#53: Invalid argument
socket.c:1915: internal_send: 158.43.240.4#53: Invalid argument
socket.c:1915: internal_send: 158.43.128.72#53: Invalid argument
socket.c:1915: internal_send: 194.168.4.100#53: Invalid argument
;; connection timed out; no servers could be reached
```

**Comment by fishouttah20** [comment]
Looks like more than just nslookup affected by socket.c. #69

**Comment by christoh** [comment]
same with dig and host

**Comment by defconoi** [comment]
Same with ping, hopefully these get fixed since I use these daily

**Comment by sunilmut** [comment]
We understand the frustration of not having networking tools enabled in the WSL and are looking to enable them gradually. The problem is the lack of the underlying socket implementation such as NETLINK, INET/SOCK_RAW/ICMP in WSL. We appreciate the feedback and please help us prioritize this by up voting [enabling network interface enumeration](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13383789-enable-network-interface-enumeraration) in the User Voice page.

**Comment by russalex** [comment]
nslookup is working much better in current builds.  As this is an old thread I will close out.
