### ISSUE TITLE
Installer should not refer to "UNIX" username/password, as this is not UNIX

### ISSUE THREAD

**Issue by bskendig** [Microsoft/BashOnWindows#716]
Installing bash on Windows 10 Anniversary Edition (Build 14393.10) by running "bash" from a cmd.exe window will start an installer, which then asks:

```
Please create a default UNIX user account. The username does not need to match your Windows username.
For more information visit: https://aka.ms/wslusers
Enter new UNIX username:
Enter new UNIX password:
Retype new UNIX password:
```

This is not UNIX and should not refer to itself as such. Instead of "UNIX" it should say "Linux", or perhaps better, "Ubuntu".

The page at the provided link https://aka.ms/wslusers refers to creating "a default Linux user".

**Comment by xilun** [comment]
I guess this is from the adduser command, so maybe you should open a bug there? :)

**Comment by russalex** [comment]
Completely understand the confusion.

In this case WSL is simply calling `adduser`.  We do no processing on the text and do not have those strings anywhere within Windows / WSL.  This is one of those situations where we have very little control.

**Comment by bskendig** [comment]
Okay, that makes sense. I'll go find where to open a bug against adduser.

**Comment by xilun** [comment]
@bskendig You can get infos with `apt-cache show adduser` It seems to come from Debian.
I'm a little unsure they will accept to change that because as a Debian user I'm so used to seeing that password prompt that it would disturb me to have it changed, and I guess it would disturb other Debian users. However, Ubuntu can also modify their package compared to Debian, so if that really bother you and Debian don't want to change it you can try Ubuntu.

**Comment by kev009** [comment]
This is because the accounts are created for and authenticated by pam_unix.so.  Find something better to do with your time.

**Comment by benhillis** [comment]
Going to go ahead and close this on out, thanks for the discussion.
