### ISSUE TITLE
Cannot install Virtualbox

### ISSUE THREAD

**Issue by HeathNaylor** [Microsoft/BashOnWindows#733]
# Description
I am able to `sudo apt-get install virtualbox vagrant` but when I attempt a `vagrant up` I am presented with an error. This ends at a Linux headers error, and since WSL is only the userspace and not the kernel am I correct in thinking that there is no current fix for this?

# Expected results
Vagrant box comes up fine

# Actual results
```
VirtualBox is complaining that the installation is incomplete. Please
run `VBoxManage --version` to see the error message which should contain
instructions on how to fix this error.
```
So then I run `VBoxManage --version`
```
WARNING: The character device /dev/vboxdrv does not exist.
         Please install the virtualbox-dkms package and the appropriate
         headers, most likely linux-headers-3.4.0+.

         You will not be able to start VMs until this problem is fixed.
4.3.36_Ubuntur105129
```
And then I run `sudo apt-get install linux-headers-3.4.0+`
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-headers-3.4.0
E: Couldn't find any package by regex 'linux-headers-3.4.0'
```

# Windows build number
Version	10.0.14393 Build 14393

**Comment by stehufntdev** [comment]
Thanks for reporting the issue.  WSL does not currently provide Dynamic Kernel Module Support (DKMS) since it is emulating the Linux kernel interfaces exposed to user mode Linux binaries.  We haven't investigated if WSL can also emulate the Linux kernel interfaces exposed to Linux kernel modules.

Check out the important links section on the main page to see what scenarios are being targeted for the current release.

**Comment by HeathNaylor** [comment]
@fpqc I understand all of that, makes perfect sense. However, how do I run `vagrant up` from my Ubuntu userspace then? I am fine with using Windows binaries but currently am unable to get this working.

**Comment by fpqc** [comment]
@HeathNaylor It says Vagrant supports cloud platforms.  Couldn't you configure your Win32 instance of Virtualbox to appear like a cloud platform and then set Vagrant up to handle it like that?

**Comment by aseering** [comment]
@fpqc -- by "cloud platforms" I think it means "Amazon AWS" (and similar).  Virtualbox isn't designed to work like AWS.

**Comment by aseering** [comment]
@HeathNaylor -- I haven't tried this, but one option (though a little clunky) would be to call the Windows version of Vagrant from Linux using [cbwin](https://github.com/xilun/cbwin).

**Comment by MikeTheCanuck** [comment]
As an alternative/workaround, I have made peace with a [hybrid Windows/Bash solution](https://mikethecanuck.wordpress.com/2016/08/16/what-ive-learned-setting-up-bashubuntuwin10-for-ansible-vagrant-virtualbox/) for running vagrant + virtualbox + ansible, relying on TCP/IP connectivity across the subsystems.

**Comment by fpqc** [comment]
@MikeTheCanuck use @xilun 's cbwin project.  It can call gui and console windows programs with wstart and wcmd (wcmd cmd for example) inside of the terminal emulator.  

I highly suggest running outbash in --outbash-session mode, since this allows you to do things like multiplex cmd with tmux, which is pretty amazing.

**Comment by ricardowong** [comment]
What about running a fake WSL VBoxManage that redirects input/output to the real VBoxManage on the windows installed Virtualbox?

**Comment by ricardowong** [comment]
With the new build you can run Windows executables so I propose the following to run **Vagrant on WSL**.

First, remove any previous VirtualBox from your WSL.
Next Check if you can run windows excecutables by adding the path `export PATH=$PATH:/mnt/c/Windows/System32`, then try opening notepad.exe

If successful go ahead.

1. Install Vagrant and check if you can run the windows native VirtualBox cli tool.
`sudo apt-get install Vagrant
export PATH=$PATH:"/mnt/c/Program Files/Oracle/VirtualBox"
VBoxManage.exe`

2. Since vagrant requires the executable to be called VBoxManage, I've linked it at /usr/bin
`sudo ln -s "/mnt/c/Program Files/Oracle/VirtualBox/VBoxManage.exe" /usr/bin/VBoxManage
VBoxManage`

3. Patch the vagrant drivers to include virtual box 5.0 and 5.1 as per the following instructions
https://github.com/mitchellh/vagrant/issues/5572#issuecomment-93250550
Instructions taken from this comment by @PhilipeLouchtch.

> At /usr/share/vagrant/plugins/providers/virtualbox/driver/
> Copy version_4_3.rb > version_5_0.rb
> Edit the class to be called version_5_0 and the log a few lines under
> Repeat for version_5_1
> 
> Modify /usr/share/vagrant/plugins/providers/virtualbox/driver/meta.rb
> find the hashmap on line 48, add after "4.3" => Version_4_3
>             ,"5.0" => Version_5_0,
>             "5.1" => Version_5_0
> 
> Modify /usr/share/vagrant/plugins/providers/virtualbox/plugin.rb
> find the module Driver and add the following lines
>       autoload :Version_5_0, File.expand_path("../driver/version_5_0", __FILE__)
>       autoload :Version_5_1, File.expand_path("../driver/version_5_0", __FILE__)

4. Enjoy.

**Comment by antmerlino** [comment]
@ricardowong Thanks for your guide, it definitely works well.  I would suggest people to not install vagrant from the package manager but rather from vagrant using wget and dpkg -i
The package manager has a pretty outdated version of vagrant.

I'm having an issue running vagrant up with this setup.  Vagrant invokes the VBoxManage import command.  The problem is that the path is for inside of WSL, not windows.  VBoxManage tries to prepend D:\ (at least for me) which means the command fails because that path does not exist.  Does this mean that we can only use vagrant inside of WSL only after provisioning boxes?

**Comment by odannyc** [comment]
@ricardowong @antmerlino 

Same thing happens for me. This is the exact error when I run `vagrant up`:
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "-n", "/home/odannyc/.vagrant.d/boxes/scotch-VAGRANTSLASH-box/2.5/virtualbox/box.ovf"]

Stderr: 0%...
Progress state: VBOX_E_IPRT_ERROR
VBoxManage.exe: error: Appliance read failed
VBoxManage.exe: error: Failed to open OVF file 'D:\home\odannyc\.vagrant.d\boxes\scotch-VAGRANTSLASH-box\2.5\virtualbox\box.ovf' (VERR_PATH_NOT_FOUND)
VBoxManage.exe: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component ApplianceWrap, interface IAppliance
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleImportAppliance(struct HandlerArg *)" at line 307 of file VBoxManageAppliance.cpp
```

any fixes or workarounds anyone can think of?

**Comment by odannyc** [comment]
Actually, putting my home folder in the D:\ drive and symlinking my home folder in ubuntu to the D mount might just work, testing...

**Comment by MatheusRV** [comment]
@odannyc same error here? did you discover a solution?

as we could see VBoxManager is trying to open the same folder as $PATH instead of Linux.

**Comment by marcvroom** [comment]
@MatheusRV the fix you did doesn't seem to fix mine. Did the `export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"` then `vagrant up` but same error is showing.

**Comment by MatheusRV** [comment]
@marcvroom hello, did you updated your vagrant?
Which version is your WSL version, your vagrant, and VirtualBox?

**Comment by marcvroom** [comment]
Hi @MatheusRV, my vagrant is 1.9.5 and my WSL version is 16.04(this is the ubuntu version, right?) and my VirtualBox is 5.1.22. I think all is updated.

**Comment by vzezzos** [comment]
@odannyc Same issue here

**Comment by hafah** [comment]
@marcvroom  @vzezzos 

Probably vagrant is trying to use ubuntu's virtualbox. Maybe this will fix it.
````
export VAGRANT_WSL_ENABLE_WINDOWS_ACCESS="1"
sudo apt-get purge virtualbox
sudo apt-get remove virtualbox-dkms
```
