### ISSUE TITLE
install vagrant complains /dev/vboxdrv does not exist, install linux-headers-? will not complete

### ISSUE THREAD

**Issue by MikeTheCanuck** [Microsoft/BashOnWindows#768]
Installed vagrant on fresh install of Bash on Ubuntu for Win10.  Then running vagrant commands complain /dev/vboxdrv does not exist, and suggests installing "virtualbox-dkms package" and "appropriate headers, most likely linux-headers-3.4.0+."  Virtualbox-dkms is already installed, and there is no such headers package "linux-headers-3.4.0+".  Took a guess that linux-headers-generic would be close enough, install stalled at "run-parts: executing /etc/kernel/header_postinst.d/dkms 3.13.0-92-generic /boot/vmlinuz-3.13.0-92-generic".  Configuring manually still stalls the next day.

Expected results: vagrant commands would work; Bash would hint an available linux-headers package; linux-headers-generic install would complete.

Actual results:

1. Installed vagrant (sudo apt-get install vagrant)
2. Run vagrant command (vagrant up) in pre-existing vagrantfile directory
Result: "VirtualBox is complaining that the installation is incomplete. Please
run `VBoxManage --version` to see the error message which should contain
instructions on how to fix this error."
3. Run 'VBoxManage --version'
Result: "WARNING: The character device /dev/vboxdrv does not exist.
         Please install the virtualbox-dkms package and the appropriate
         headers, most likely linux-headers-3.4.0+.

         You will not be able to start VMs until this problem is fixed."
4. Install virtualbox-dkms package (sudo apt-get install virtualbox-dkms)
Result: the following output:

![image](https://cloud.githubusercontent.com/assets/6953053/17411555/a36b04b4-5a2d-11e6-9c0f-3cf24b0d9568.png)

5. Tried installing linux-headers-3.4.0+ (sudo apt-get install linux-headers-3.4.0+)
Result: the following output:

![image](https://cloud.githubusercontent.com/assets/6953053/17411610/d076148a-5a2d-11e6-8e91-a3334bd9d20a.png)

6. Install linux-headers-generic (sudo apt-get install linux-headers-generic)
Result: the following output:

![image](https://cloud.githubusercontent.com/assets/6953053/17411624/dfe60f74-5a2d-11e6-9627-fb71d9223d64.png)

(then a few lines of expected installation output that I didn't bother to copy down)

The last two lines of installation output were:

![image](https://cloud.githubusercontent.com/assets/6953053/17411650/f97daa0a-5a2d-11e6-8f93-7c1a0564904d.png)

And this hung for 12+ hours (left it overnight).

7. Tried to Ctrl-C stop this, it wouldn't respond.  Killed the Bash shell. Fired up ProcExp, killed the process tree of all linux processes orphaned.

8. Tried re-running the install (sudo apt-get install linux-headers-generic)
Result: "E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem."

9. Took their advice (sudo dpkg --configure -a)
Result: the following output:

Setting up linux-headers-3.13.0-92-generic (3.13.0-92.139) ...
Examining /etc/kernel/header_postinst.d.
run-parts: executing /etc/kernel/header_postinst.d/dkms 3.13.0-92-generic /boot/vmlinuz-3.13.0-92-generic

Again, this hung for hours.  Stopped here, don't know what to try next.

Windows build: 14393.10

Packages installed since installing Bash for Ubuntu on Windows: npm, rpm, pip, git, ansible, virtualbox, vagrant.  (And I installed ansible 2.1.1.0 by adding its repo.)

**Comment by stehufntdev** [comment]
Thanks for trying out WSL!  #733 is a similar discussion so closing this out as a duplicate.

**Comment by MikeTheCanuck** [comment]
Thanks @stehufntdev - learned something important about Bash on Windows today!  I'll follow up with #733 and pursue their lines of workaround.

Aside: my initial experience has been [blogged here](https://mikethecanuck.wordpress.com/2016/08/03/running-nix-apps-on-win10-anniversary-update-initial-findings/)

**Comment by MikeTheCanuck** [comment]
For future hunters and gatherers: I've tested and am satisfied with a [hybrid Windows/Bash approach to using vagrant + virtualbox + ansible](https://mikethecanuck.wordpress.com/2016/08/16/what-ive-learned-setting-up-bashubuntuwin10-for-ansible-vagrant-virtualbox/).

**Comment by ricardowong** [comment]
With the new build you can run Windows executables so I propose the following to run Vagrant on WSL.

First, remove any previous VirtualBox from your WSL.
Next Check if you can run windows excecutables by adding the path `export PATH=$PATH:/mnt/c/Windows/System32`, then try opening notepad.exe

If successful go ahead.

1. Install Vagrant and check if you can run the windows native VirtualBox cli tool.
`sudo apt-get install Vagrant
export PATH=$PATH:"/mnt/c/Program Files/Oracle/VirtualBox"
VBoxManage.exe`

2. Since vagrant requires the executable to be called VBoxManage, I've linked it at /usr/bin
`sudo ln -s "/mnt/c/Program Files/Oracle/VirtualBox/VBoxManage.exe" /usr/bin/VBoxManage
VBoxManage`

3. Patch the vagrant drivers to include virtual box 5.0 and 5.1 as per the following instructions
[https://github.com/mitchellh/vagrant/issues/5572#issuecomment-93250550](Instructions taken from this comment by @PhilipeLouchtch).

`At /usr/share/vagrant/plugins/providers/virtualbox/driver/
Copy version_4_3.rb > version_5_0.rb
Edit the class to be called version_5_0 and the log a few lines under
Repeat for version_5_1

Modify /usr/share/vagrant/plugins/providers/virtualbox/driver/meta.rb
find the hashmap on line 48, add after "4.3" => Version_4_3
            ,"5.0" => Version_5_0,
            "5.1" => Version_5_0

Modify /usr/share/vagrant/plugins/providers/virtualbox/plugin.rb
find the module Driver and add the following lines
      autoload :Version_5_0, File.expand_path("../driver/version_5_0", __FILE__)
      autoload :Version_5_1, File.expand_path("../driver/version_5_0", __FILE__)`

4. Enjoy.
