### ISSUE TITLE
top always shows 50% cpu utilization for all cpus

### ISSUE THREAD

**Issue by sinverso** [Microsoft/BashOnWindows#823]
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
- Expected results
- Actual results (with terminal output if applicable)
- Your Windows build number
- Steps / commands required to reproduce the error
- Strace of the failing command
- Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by laklek** [comment]
A little more information would've been nice.
But I can confirm, I get the following output:

`top - 03:23:45 up 3 min,  0 users,  load average: 0.52, 0.58, 0.59
Tasks:   3 total,   1 running,   2 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.2 us, 50.1 sy,  0.0 ni, 48.3 id,  0.0 wa,  0.4 hi,  0.0 si,  0.0 st
KiB Mem:  16732908 total,  5477564 used, 11255344 free,    34032 buffers
KiB Swap:  2490368 total,    35236 used,  2455132 free.   188576 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
    1 root      20   0       0      0      0 S   0.0  0.0   0:00.00 init
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.04 bash
   15 root      20   0       0      0      0 R   0.0  0.0   0:00.04 top`

50.1 sy means Percentage of the CPU for system processes
48.3 id means Percentage of the CPU not used (idle)
This while %CPU for all the processes are 0.0 (sometimes 1% if I slam my keyboard while in TOP, so that's working fine)

It's dangling around 50%

**Comment by stehufntdev** [comment]
Thanks for reporting the issue, a fix for this should be out for insider builds soon.
