### ISSUE TITLE
in the vscode'terminal,I can't use the history command

### ISSUE THREAD

**Issue by czmecho** [Microsoft/BashOnWindows#828]
Please use the following bug reporting template to help produce actionable and reproducible issues:

* Your Windows build number win 10 14393.10 && vscode 1.4
when I use the powershell or cmd ,I can use the PgUp or the PgDn keys to roll back to use the history command.
but when I call the bash.exe ,it don't work.
![](http://ww1.sinaimg.cn/large/7df5111fgw1f6n8s035krj2149091ta7.jpg)
btw,can I change the background color ,I don't like the color like this.

**Comment by fpqc** [comment]
Yeah, seems to be related to the same problem we've had to work around since about day 1 with ConEMU.   It's another console glitch.  In ConEmu you could get around it by launching bash with special arguments like -cur_console:p, but I don't know if VS code has similar arguments you can throw in to make its integrated terminal work right.

**Comment by zadjii-msft** [comment]
I would open this as a bug on the VSCode team (https://github.com/Microsoft/vscode) as this is more an issue with their built-in console, rather than an embedded conhost window

**Comment by bitcrazed** [comment]
This issue was moved to Microsoft/vscode#10368
