### ISSUE TITLE
How will WSL be updated in next releases?

### ISSUE THREAD

**Issue by alexanderwhatley** [Microsoft/BashOnWindows#831]
I see that Microsoft is planning two major upgrades to Windows 10 next year. I am wondering how exactly WSL will be upgraded accordingly. Will we only see significant added functionality (i.e. unix sockets, filesystem notifier support, GPU support, etc.) in those major upgrades, or will those be rolled out in weekly/monthly upgrades as well? Do any of the developers here have a rough idea how it will work? Thanks.

**Comment by benhillis** [comment]
Great question.  There will certainly be big updates to WSL in next year's Windows 10 updates.  We will also be flighting bug fixes and new functionality via the [Windows Insider](https://insider.windows.com/) program which should be starting up fairly soon.  Once Insider flighting begins again you can expect updates every week or two in the "fast ring."

**Comment by ajaykagrawal** [comment]
Will folks who are on a "regular" (not insider) Windows and have installed the WSL beta also get periodic updates (bug fixes, enhancements) or will they have to wait for the next year Windows 10 update?

**Comment by benhillis** [comment]
@ajaykagrawal non-Insider users will receive critical bug fixes via Windows Update for example bluescreens or security vulnerabilities.  New features and non-critical bug fixes will be flighted in the Windows Insider program.

**Comment by iz0eyj** [comment]
Hi Ben, exists a road map for WSL?
In six month or a year it will be a near-complete Ubuntu system?
And the version? Microsoft and Canonical are planning to take it to the next version?

**Comment by benhillis** [comment]
Ubuntu 16.04 support is in the works.  Some users are already running Xenial (#482) to varying degrees of success. There are some issues we are working on, including the release-upgrade process itself.

I can't really comment on our internal plans but as far as a roadmap stay tuned to our [WSL blog](https://blogs.msdn.microsoft.com/wsl) for announcements.

**Comment by fpqc** [comment]
@ajaykagrawal I think if you're going to be using WSL over the next year, you really are going to want to be on the fast ring.  I have only had like one or two updates that caused real problems for me (breaking my audio output!!).  Most of the bugs were mainly just stupid things like making chromium and electron applications be slightly wrongly-sized when maximized and whatever, or corrupting Chrome's directwrite font cache (which is no longer a problem since the bug encouraged the Chromium team to remove the dwritefontcache altogether)

**Comment by cosmosb** [comment]
This is a bummer. I can't really use insider builds at work. It is really disappointing to wait for months for update to one of the most useful developer tool on Windows. 

I understand if this hasn't been planned out yet as product is still in beta officially, but why can't this be treated as one of Windows built-in app and updated frequently like other Windows store apps.

At least do monthly updates like Visual Studio Code team is doing.

If major issues like this - https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13383789-enable-network-interface-enumeraration - are fixed, I would like to have update asap.

**Comment by fpqc** [comment]
@cosmosb I mean, I've been running insider builds of Win10 for over a year, and I've had minimal problems in terms of stability.  Maybe you could request permission to run it on your workstation from your site admin?

**Comment by benhillis** [comment]
@cosmos I understand your frustration and believe me when I say the development team shares it.  We would love to be able to get fixes and features out to our users faster (even faster than the Insider builds).  Unfortunately there isn't currently a good way to release inbox components (lxcore.sys / lxss.sys) externally the same way an app like VS Code is able to do.

**Comment by ajaykagrawal** [comment]
@benhillis I have the same issue as cosmosb, I want to move my server side and embedded developers from virtual box (managed by vagrant) to WSL. Unfortunately I don't think getting all the (50+) developers to switch to an insider build is very practical. It isn't obvious to me why a windows update (perhaps available to only those who have the WSL beta) could not deliver updated versions of lxcore.sys and lxss.sys. I am guessing that once WSL leaves beta, future updates of WSL will also be delivered by Windows Update and should not require the use of an insider build.

**Comment by fpqc** [comment]
@ajaykagrawal Not so sure about that. Even though they are drivers, I think there is also work done directly on the NT kernel side (the undocumented so-called Native NT interfaces) getting them to work?

I read a section of a book called Open Sources 2.0 that says that even though the Win32 API generally won't change from version to version, the interface between the native kernel and the driver implementing the Win32 subsystem can change all the time (although MS once licensed out the documentation for the NT 4 native interface, which resulted in a 3rd party company developing the Windows NT POSIX subsystem, which Microsoft later bought in order to keep the expertise in-house).  

This might be the reason why they can't just distribute the lxss and lxcore drivers, since they might require native kernel-side changes as well, though that's just a guess (it's a question I've wondered about for a while).

**Comment by benhillis** [comment]
@fpqc Well said. that's certainly part of it.  Windows Update is primarily for security patches and other things that are deemed high priority.  It's very rare for new features to come in the form of Windows Updates.

**Comment by Zx-EvM** [comment]
@benhillis There are plans to fix the problems and errors like this https://github.com/Microsoft/BashOnWindows/issues/791 and https://github.com/Microsoft/BashOnWindows/issues/796 ?

**Comment by fpqc** [comment]
@Zx-EvM I could have sworn that I read yesterday or today in another thread that there were at least "ideas about plans" (my words) to support parts of systemd through some sort of "Ubuntu service host" (my words again) functioning as a sort of "second OS running on the same kernel" (their words) which would handle the #791 and #796 things.

**Comment by benhillis** [comment]
@fpqc I think you may be referring to my comment from earlier today (https://github.com/Microsoft/BashOnWindows/issues/834#issuecomment-238589089)?  I wasn't committing to anything simply explaining why things are currently they way they are.

**Comment by fpqc** [comment]
@benhillis Whence "ideas about plans"! You can't get more noncommittal than that!

**Comment by benhillis** [comment]
@fpqc lol.  This has been my first experience being the voice of a large company and I don't want anything I say to be interpreted as a commitment or promise.

**Comment by iz0eyj** [comment]
Hey guys... just to tell that my WSL+VcXsrv+XFCE worked a week before to restart for 14393.67.

**Comment by moshes** [comment]
how is the ubuntu part of the WSL is updated? Will it update automatically from the store? If not, should I run lxrun /uninstall /full & lxrun /install? How will I know that new bits are available?

**Comment by rodrymbo** [comment]
The ubuntu binaries are updated by running `sudo apt-get update` and cousins from within Bash. The ubuntu 14.04 is "LTS" which means it has been stable for a while, with only occasional security fixes. There are distribution upgrade options, but they're not working as well yet (in WSL).

I'm not really sure which parts are downloaded from the store. Obviously bash.exe and lxrun.exe are not, because one uses them to do the install. I'd assume that the normal way to upgrade windows store apps would work with WSL, but if it is just the LTS ubuntu 14.04 base package, that's not going to change. 

The normal way to keep ubuntu updated automatically would be to use `cron` (I believe), but that's not completely without problems on WSL.

**Comment by cbyrd01** [comment]
Another alternative currently exists; you can use Windows Task Scheduler to automatically run apt-get upgrade. I wrote [a blog post about it here](http://www.riosec.com/articles/automatingupdatesforbashonubuntuonwindows10).

**Comment by rodrymbo** [comment]
Or you could use Windows Task Scheduler to start cron (using `bash -c "cron -f"`). Oh, but we're not supposed to do that yet.

**Comment by jdevora** [comment]
Any news about a way to update WSL for the ones that need to stay in the "public releases"?

**Comment by fpqc** [comment]
@jdevora The only news is don't hold your breath.  WSL updates are tied to Windows builds for the foreseeable future.  Check back when the feature is out of beta =[.

**Comment by benhillis** [comment]
Closing since this discussion has run its course.
