### ISSUE TITLE
AptPackageIndexUpdate opens a console window in the current session

### ISSUE THREAD

**Issue by xilun** [Microsoft/BashOnWindows#841]
- A brief description

AptPackageIndexUpdate scheduled task opens a console window on the current desktop. This is disturbing: at first I thought of an intrusion. It might be minimized, but even if it is an icon appears on the taskbar temporarily, which is very disturbing if you notice it and don't know what it is, and can't check when it has disappeared.
- Expected results

No window spawning when I don't touch my computer during 10 mins.
- Actual results (with terminal output if applicable)

A Windows appear with with content of "apt-get update"
- Your Windows build number

14393.51
- Steps / commands required to reproduce the error

Wait for the AptPackageIndexUpdate Windows Scheduled Task to run.
- Strace of the failing command

N/A
- Required packages and commands to install

N/A

Suggestion: arrange for the console window to not appear at all, and put the traces in a rotated log in /var/log/

Other remark: I'm not sure if the selected options of that scheduled task "Stop if the computer ceases to be idle" and "Stop if the computer switches to battery power" serve any purpose given the command executed.

**Comment by rodrymbo** [comment]
It sounds like you are reporting that starting bash.exe from Task Scheduler is opening a console window. WSL designed it to work that way. 

See [this forum page](http://wsl-forum.qztc.io/viewtopic.php?f=6&t=10&sid=e0d397e285fa3e92f94bcb6217e1d3bd) for one technique for launching a script or process from Task Scheduler that does not open a console window. Otherwise, every time you start bash.exe directly, it will open then close another console window (by WSL design). It's a bit indirect, but it seems to work. There are other kludges around too.

Unless I'm wrong (entirely likely), since it is more a WSL feature than a bug, and has to do with launching bash.exe from task scheduler for any process, not just for AptPackageIndexUpdate, I'd guess that you'd accomplish more by asking for an alternative in the UserVoice site.

**Comment by xilun** [comment]
The task in question is installed by WSL / Bash On Windows. I know that for now, the behavior is consistent with how the task works. However, I don't believe the current behavior should stay as is in future releases of Windows; I agree this would probably need some changes about how WSL works internally, and all that I'm saying is: it would be better eventually have a system that permit to not have that window, if it is possible.

I think this is an issue, because I certainly was concerned about what was that window, and initially thought about a possible critical security issue (my computer being remotely control without my authorization), and it is possible that other people will think likewise.

**Comment by benhillis** [comment]
I agree, I am not a big fan of this updater task at all.  I started a thread with some relevant folks to see if I can get this pulled.

**Comment by rodrymbo** [comment]
We could let cron do it ... oh wait, that's another issue. 

@xilun - I agree with everything you said. I don't like stray windows popping up at random times. So yes, if Microsoft is installing a cron job ... er, scheduled task ... that opens a console window, that's not good. But I would submit that it's also a bigger issue of how or whether things are going to work in the background. I'd submit that the solution is not to pull the updater completely, or rely on users to set up a workaround that doesn't atartle us, but to fix it so task scheduler (or cron?) runs it the way it is supposed to be run ... along with a variety of other background tasks, daemons, and services that many of us use all the time and think are important. Not all of them to start with, but just the option of running one without a stray console opening is pretty important. Asking the user if she wants auto-updating, or offering some other way to trick the user into thinking she is in control of what runs automatically or in the background, would be good also.

**Comment by wolf99** [comment]
Once I found out what this was I was *relatively* happy to let this run. But when it just popped up a cmd window and started running installer-related stuff without me being explicitly aware of what was going on, my first thought was indeed that some remote malfeasance was afoot and thus promptly disconnected my network! My second thought was that it was trying to indulge in placing further 
"Consumer Features" à la Candy Crush Saga, etc upon my machine again :fearful:.

Maybe some kind of notification is in order when installing WSL to the effect that a task will be added to auto-update WSL via a cmd windows when the machine is detected to be otherwise idle.

**Comment by barry-scott** [comment]
While playing Doom this window pop up and stoped the game. This is not nice behavior.
 Also I want control over if update happens and when it happens.

**Comment by JordanGS** [comment]
This is just terrible design

1) I look at my PC and i see this going on, i'm wondering if i have some sort of maleware on my machine or if someone else managed to remote in. I don't know what's going on except for some random downloads occurring. *sigh*

2) This is should be automatic unless i allow it. There should be some way to do this manually from within the bash.

**Problem**
I panicked since i didn't know what it was and killed the process, now i can't start bash, uninstalling and reinstalling doesn't work. Good job MS, now i'm i have to reinstall windows. Good shit, i knew i gave you guys too much credit when i was happy to have native bash on on my PC. Now i get to format my PC, YAY!

**Comment by leojbgiusti** [comment]
JordanGS: Can you not try deleting the %localappdata%\lxss directory

**Comment by rodrymbo** [comment]
@JordanGS - I'm not sure 'bash not working' is a good reason to reinstall everything. 

You should be able to do the uninstall with the [lxrun commands](https://msdn.microsoft.com/en-us/commandline/wsl/reference?f=255&MSPPError=-2147217396). For completeness one can check to make sure that %localappdata%\lxss has been deleted as @leojbgiusti suggests (it's hidden, so you have to work to make it show up in Explorer). For even more completeness, unselect the Windows Subsystem for Linux (beta) in the "Turn Windows Features on or off" widget (real control panel | Uninstall or change a program | Turn Windows Features on or off). 

Or perhaps you've already gone through those steps?

**Comment by JordanGS** [comment]
@leojbgiusti @rodrymbo i tried both before i went to complain, i usually don't complain, especially on GitHub but this whole thing has been a pain. So far, after attempting, it will still try to auto update as seen on this [image upload](http://imgur.com/a/UJNTb). I assume this is the update and not some elaborate hack (joking). Anyways, after several failed connection attempts to URL's and finishing at 100%. My bash is still inoperable.

**Comment by voltagex** [comment]
This doesn't respect metered network settings either...

**Comment by adeeb1** [comment]
+1 to some sort of solution for this. My initial reaction was similar to that of @wolf99: I was concerned when I first saw the bash window pop up. Fortunately I wasn't in the middle of anything, so I was able to see what was happening and quickly determine that it was safe. However, I can see how this could be unpleasant if I am in the middle of working, playing a game, or on a metered connection. I think it would be solved when background tasks have better support.

**Comment by Novynn** [comment]
I just had this console open and it now seems stuck in a weird state and won't accept user input. It doesn't show up as anything unique in Task Manager so I'm unsure of which process to close.

A solution is highly desired!

**Comment by barry-scott** [comment]
Did you type Ccontrol-Q to stop output?
Try typing Control-S to continue output.

**Comment by Novynn** [comment]
Yes, both had no affect.

**Comment by mobluse** [comment]
I could also not close AptPackageIndexUpdate window using close button or any other way, but when I closed Bash with Ctrl+D it closed.

This just popped up:
![aptpackageindexupdate](https://cloud.githubusercontent.com/assets/5777329/19919063/9ad4c148-a0d0-11e6-989e-9ec9a3678280.png)

It might be good to get a reminder to upgrade, but one should be able to close the window.

**Comment by lygstate** [comment]
There is no way to close the window directly.

**Comment by lygstate** [comment]
Use SysinternalsSuite, find the process conhost without parent, close it.

**Comment by xilun** [comment]
The AptPackageIndexUpdate also did not close properly on my install while other Console windows running WSL processes where open. It did not close automatically at the end of its work. Neither did it close when I subsequently clicked on the X button. It closed when I closed all the other Console windows running WSL processes.

**Comment by jrcharney** [comment]
Ugh! I have two "AptPackageIndexUpdate" windows still open and I just performed a `sudo apt update && sudo apt upgrade -y`.  Honestly, Microsoft, we don't need another window to tell us when to update our packages...unless of course you have a nice cron script that can do this in the weekly, and without being a nuisance. (See https://help.ubuntu.com/community/CronHowto)

**Comment by benhillis** [comment]
@jrcharney - we have some improvements coming in this space. In the meantime if you'd like to disable this task you can remove it via this command line:

`schtasks.exe /Delete /TN "\Microsoft\Windows\Windows Subsystem for Linux\AptPackageIndexUpdate"`

**Comment by conan** [comment]
Is there any way to close the window but keep the console?  This happens to me all the time and I don't want to have to keep closing my console windows that are executing long-running tasks.

**Comment by aseering** [comment]
Officially, no -- in the current implementation, all Linux processes terminate when the last console window goes away.

Unofficially, you can launch bash via run.exe:  `run.exe bash.exe -c "<whatever Linux command>"`.  (run.exe is available here: http://www.straightrunning.com/projectrun/ )  You can also write a small VBS script that launches the command in a hidden console; instructions for running Linux sshd this way (which ought to be easily applied to other commands as well) can be found at https://wsl-forum.qztc.io/viewtopic.php?f=6&t=10 .

**Comment by benhillis** [comment]
There is a big improvement to this experience coming to Windows Insider builds soon. Marking as fixinbound.

**Comment by HelOWeen** [comment]
Is this supposed to be fixed by now?

I ask, because with __no__ outstanding Windows updates, I still have the AptPackageIndexUpdate window pop up. In the middle of a full-screen game, no less.

And TBH, I dare to question this index updating at all. One has to go through quite some steps to activate WSL at all. Steps that I doubt a "normal" end user would be bothered to do at all and I guess are also hard to do by accident.

So assuming only those of us who _know_ what they're doing have activated WSL at all, I'm pretty sure also know how to keep their Linux up to date. I at least do.

**Comment by benhillis** [comment]
Are you on Creators Update? It should be resolved there.

**Comment by HelOWeen** [comment]
I'm pretty sure I am, with no outstanding updates. But I need to double check that when I can get on those machines again.

**Comment by aseering** [comment]
@HelOWeen -- it'd be great if you could check.  Creators is apparently being rolled out slowly (there was a post somewhere about it being rolled out over a month or two) so "no updates are available" and "machine is still running Anniversary" are not mutually exclusive.

**Comment by HelOWeen** [comment]
@aseering : I just checked. I'm still on 1607. I'm sorry to not have that checked upfront.

**Comment by kangarooo** [comment]
Still not fixed? WTH? How long is this, cause Windows 10 is for some time already. This is very slow fix since i have todays latest udate windows and i put Ubuntu bash and got this automatically just now spawned.

**Comment by benhillis** [comment]
@kangarooo - What windows build are you running? This is resolved in Creator's Update.

**Comment by jay-at-avido** [comment]
+1 on windows 10. Scary stuff 😱
