### ISSUE TITLE
Can't resolve hostnames of other machines on local network

### ISSUE THREAD

**Issue by Reedbeta** [Microsoft/BashOnWindows#890]
Using bash on Windows I can't resolve the hostname of another machine on my local network.

Access to the internet at large from bash works (can do `wget google.com` or `apt-get update`, for instance). Bash can talk to the other host by IPv4 address, and pinging it by name works in the Windows command prompt; however, it can't be resolved by name in bash.

A possible complication is that the local network is IPv6-enabled. It's a recent Comcast wireless router between the two machines (both running Win10). I haven't tried disabling IPv6 (not sure how to do it).

I also tried to follow [these steps](http://askubuntu.com/a/516533/581862) to install the winbind service, but this doesn't seem to work on LXSS; afterward, when trying to resolve names I just got the error "Could not determine network interfaces, you must use a interfaces config line".

Are there any steps I can take to enable local name resolution in bash?

**Comment by rodrymbo** [comment]
How does the Windows side do name resolution, and what linux command are you trying to use? 

**An entry in its hosts file?** Check the `/etc/hosts` file in bash to see if the same entries are there as in the Windows hosts file. (It's tricky to read in Windows because of hiding and so forth in Explorer, but it's not hard to read from the bash side: `cat /mnt/c/Windows/System32/drivers/etc/hosts`. You probably only want to see what's in it, not change it.) If not, try deleting `/etc/hosts`. It will be generated again the next time WSL is started from scratch. Theoretically it would be pretty much the same as your Windows hosts file at that point. Alternative two is to edit the `/etc/hosts` file to remove the `#This file was automatically ...` line, to make it static, and add the local hostnames there. (Hosts file entries should override or supplement what the external resolvers provide. If the problem is IPv6, you can experiment with giving just the IPv4 address in `/etc/hosts` on the linux side, or just IPv6 ... or both.)

**Connecting to a DNS resolver that handles LAN DNS entries?** Look at `/etc/resolv.conf` to see what resolver WSL is set to use, and compare it to the DNS Servers designated when you do `ipconfig /all` from a CMD prompt. Use nslookup on both CMD and Bash to look up the name of the machine on your local network. Both should use the same "Server" for resolving names, and give the same result.

**Not using DNS to resolve the name:** In Linux it is easier to add one or two names to `/etc/hosts` than to try to do other things, e.g. WINS, as long as the program you are using can use IP addresses.

This is mostly the normal configuration one does in Linux, but you may find some WSL gotchas that are making it harder, e.g. not having a device like `eth0` to use, as you discovered trying to configure winbind, so by all means report them, especially if none of these options work.

**Comment by Reedbeta** [comment]
It looks to me like the Windows side is using WINS. `nslookup` doesn't find the other machine on either CMD or bash, but `nbtstat -r` in CMD shows it. I can also do `net view \\machinename` in CMD (or enter `\\machinename` in Explorer) and see its shares. I can also ping it by name from CMD.

In bash, pinging the machine by name returns "unknown host". I've also tried using svn from bash to access an SVN server running on the other machine and again, that works using its IPv4 address, but not using its hostname.

I guess manually adding the other machine's IP to my hosts file is the least bad solution on the table at the moment. That means I'll have to set up a static IP on my router as well. Bit of a pain.

Still, to any MS folks who may be reading, I think it would be preferable to have WINS support built-in somehow to LXSS. I imagine that's going to be a commonly wanted feature for LXSS users, so they can talk to the other Windows machines already on their networks.

**Comment by rodrymbo** [comment]
I think I read that Windows nowadays will check DNS before WINS (I could be wrong). 

Some DHCP servers will automatically enroll a dynamic IP address with a DNS name when the IP  changes. That would only work if your DNS resolver is your DHCP server (and the DHCP server cooperates). But making it "reserved" on the server is a good workaround. "Static" would work too, but is harder to manage if (when) your LAN needs to change.

Just curious: if you put the other machine's IPv6 address as the only one in /etc/hosts, does that work?

**Comment by charles-vomacka** [comment]
I am having the same issue. It seems to be because WSL does not know the local domain's name. Try, for example, nslookup localmachine.localdomain and it will work. Have not yet figured out how to set the local domain name in WSL. Normal linux configuration methods do no seem to work.

**Comment by charles-vomacka** [comment]
Ok. I figured it out. I had made a typo when editing the config file. Add your local domain name to /etc/resolv.conf 

For example add this line:   domain example.net 
substitute example.net with your local domain name.

**Comment by charles-vomacka** [comment]
Sorry, correction again. WSL overwrites resolv.conf, so editing it is useless.

**Comment by rodrymbo** [comment]
@charles-vomacka - I would suggest checking `ipconfig /all` from CMD and confirm that the "DNS Suffix Search List" is set properly. If it then is not being properly entered into the automatically-generated resolv.conf, that might be a bug to report. (It seems to be doing it okay on my machine.)

Still, I'd guess that even when WSL's DNS knows to use it as the default DNS Suffix, it won't necessarily be able to resolve the host name.

**Comment by charles-vomacka** [comment]
Thanks for the tip, that helped. I had changed the network adapter a few days ago, and the DNS suffix was not set for the adapter. Everything had worked on the Windows side - only had a problem on the WSL side - so I figured it was a problem in WSL. It appears that Windows will use the computer's primary DNS suffix, and WSL only uses the adapter's DNS suffix. Maybe this should be changed.

**Comment by rodrymbo** [comment]
@charles-vomacka - If WSL is using the settings for a particular adapter, but a connection (and its DNS) is supposed to use a different route (e.g. a second adapter, a tun/tap/vpn, whatever) that could definitely be a problem. Gives me a headache trying to figure out how best to handle it, though. 

I've confirmed that when Windows routes connections through a VPN, so does WSL. If WSL starts before a VPN that changes the routing table, DNS, and/or default DNS suffix, how do those changes get relayed to WSL? If it starts after a VPN makes those changes, what happens when the VPN is closed and everything returns to "normal"? Maybe that's why WSL doesn't even try to show adapters/interfaces, yet. 

If one is trying to connect to shares on the local network, wouldn't one need to have `samba` or something installed? Doesn't that come with WINS?

It would make things easier if the Windows side would allow the Linux side to use it as a resolver. Then one could just use "localhost" in `resolv.conf` -- assuming that the resolver on the Windows side would use both DNS and WINS and pass back IP addresses appropriately.

**Comment by philippbeckmann** [comment]
You can add a "search" entry in resolv.conf by setting the DNS suffix in the windows network adapter settings. It can be found in the adapter settings -> IPV4 -> Advanced -> Tab "DNS".

**Comment by wench** [comment]
To get WINS resolution working you use winbindd from samba. Do:

1. `sudo apt install libnss-winbind` 
2. add wins to the hosts line in `/etc/nssswitch.conf` eg: `hosts:          files dns wins`
3. edit `/etc/samba/smb.conf` and set the interfaces setting to your ip/mask

**Comment by Reedbeta** [comment]
@wrench, as mentioned in the very first message in this thread, winbind doesn't work in Linux-on-Windows.

**Comment by wench** [comment]
@Reedbeta that's because you need to do step 3 in my steps. Samba\Winbind can't find network interfaces, so you need to specify the IP to bind on and the netmask using an interfaces line eg in /etc/samba/smb.conf:
`interfaces = 10.0.0.51/24 127.0.0.1/8`
And then it will work

**Comment by Reedbeta** [comment]
Thanks for the clarification @wrench, that works after all! It still does require static IPs on the local network (else I'd have to edit smb.conf every time my IP changed), but that's okay.

**Comment by uishon** [comment]
> @Reedbeta that's because you need to do step 3 in my steps. Samba\Winbind can't find network interfaces, so you need to specify the IP to bind on and the netmask using an interfaces line in /etc/samba/smb.conf. eg:
> `interfaces = 10.0.0.51/24 127.0.0.1/8`
> And then it should work (I'm using 14942 with Xenial and it works)

I'm trying it now. Doesn't work for me :-(
Could you please explain what IP/mask I should be using?

This is my `ifconfig` output on WSL

    eth1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500

        inet 192.168.253.97  netmask 255.255.255.240  broadcast 192.168.253.111

        inet6 fe80::68d9:59ec:1931:e8e8  prefixlen 64  scopeid 0xfd<compat,link,site,host>
        ether 00:15:5d:36:62:47  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

    lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 1500
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0xfe<compat,link,site,host>
        loop  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

    wifi0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.117  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::354b:ae48:5d:8443  prefixlen 64  scopeid 0xfd<compat,link,site,host>
        ether 24:ee:9a:54:c3:dd  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`

**Comment by mhagnumdw** [comment]
Is there any other solution? I've tried several.

**Comment by MyGg29** [comment]
The resolv.conf is overwritten by WSL unless you put this in /etc/wsl.conf
```
[network]
generateResolvConf = false
```
Once you created the wsl.conf file, restart WSL. You should have a brand new `resolv.conf` file ready to have your DNS entries.
For some reason, my new `resolv.conf` was sym-linked to `/run/resolvconf/resolv.conf`.
I just deleted the file and created another one without the sym-link. 

It works like a charm now
