### ISSUE TITLE
settings set time and date crashes

### ISSUE THREAD

**Issue by markgross** [Microsoft/BashOnWindows#912]
when I go to time and date settings dialog box it starts and exits before rendering the control elements of the window

* Expected results
provide a UI for me to set the time on my computer.  Note: I'm currently traveling to China at trying to change the time zone for my computer.

* Actual results (with terminal output if applicable)
Window opens, doesn't finish drawing and exits.

* Your Windows build number
14901.rs_prerelease.160805-1700

* Steps / commands required to reproduce the error
Windows key, enter "set time", hit enter, watch dialog window open for 3 seconds and then close before rendering any control elements.

Sorry about entering this in the bash on windows issue tracker.  Its the only issue tracker I'm familiar with. :(

**Comment by benhillis** [comment]
@markgross Thanks for reporting this. Since this isn't WSL-specific I'm going to go ahead and close this out.  I see some threads internally and they're aware of the bug.

In the future the right place for general Windows 10 issue reporting is the "Windows Feedback" app that's installed as part of the preview program.
