### ISSUE TITLE
Unable to install java-8-openjdk

### ISSUE THREAD

**Issue by creeve4** [Microsoft/BashOnWindows#934]
I am attempting to install java-8-openjdk using the following commands:

```
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-8-jdk
```
Installation progress until:

`Installing new version of config file /etc/java-8-openjdk/jvm-amd64.cfg ...`

At this point installation stops/hangs.

**Comment by russalex** [comment]
Are you running the Anniversary Update (14393) or are you part of the Insider program (14905)?

We have some known issues in 14393 when running Java which have been fixed in 14905.  Just ran the commands above on the current Windows Insider build and java installed correctly.  Marking as fixed from an insider perspective (need a better way to mark where things are fixed, thinking of using the milestone field for that).

Additionally, linking this one to #857, #746, and #315.

**Comment by ericblade** [comment]
FWIW, installing openjdk-7-jre worked for me from AU, as well as installing the icedtea-7-plugin, but i have not actually tried it with anything except a java program that doesn't work due to other reasons.  It did at least start the app, but then the app aborts because other things fail that are unrelated.

**Comment by creeve4** [comment]
I am running the Anniversary Update (14393).

**Comment by dyanakiev** [comment]
I run latest public build, i install default-jdk works very well i upgraded to java 8 following this guide: http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html

**Comment by sunilmut** [comment]
Closing this issue since it is fixed in the insider builds.
