### ISSUE TITLE
File system inconsistency

### ISSUE THREAD

**Issue by SRGOM** [Microsoft/BashOnWindows#956]
First off- I completely understand that this is not a supported use case, its a very weird case (although real and not artificial). So I don't expect anything to be actually done about it but I'm noting it for documentation.

* Description

A file created on WSL side but deleted on Windows side becomes unusable. 

* Steps

Create a file on the WSL side `touch x`. You see it fine on the Windows Side. Now delete from Windows side `del x`.  `ls x` on Windows side shows that the file is still there. `vim x` on the Windows side will not allow you to save it. `vim x` on the WSL side will not allow you to save it. Basically you can no longer do anything to the file from either side, the only option is to remove it using Win+X -> a -> rm. 

* Your Windows build number

[Version 10.0.14393]

**Comment by aseering** [comment]
Just to clarify -- is this in DrvFs or VolFs?

**Comment by SRGOM** [comment]
@aseering : I don't know what either means, yet. I'll read this https://blogs.msdn.microsoft.com/wsl/2016/06/15/wsl-file-system-support/ when I get some time. and update this comment. The file is inside my home directory on WSL side. So `/home/mememe/SomeFolder/theFileImTalkingAbout`

**Comment by aseering** [comment]
@SRGOM -- ah, ok.  Hopefully that doc helps to explain things.  In any case, that path would be in VolFs.  Stuff under /mnt/ is DrvFs.

What you're seeing is probably due to the same root cause as #403 ; there are a few other related tickets if you poke around.  In short, WSL stores Linux attributes as NTFS metadata; many Windows applications don't recognize that metadata and clobber it.

The recommendation is that, if you're working with a file in both Windows and Linux, you store it in a folder on the Windows side and access it through /mnt/ within WSL.  That strategy does have some limitations, though.  There's some more information in the blog post that you mentioned and some more information on the above ticket.

**Comment by SRGOM** [comment]
Thanks, I've merged this into #403.
